### ISSUE TITLE
wgsl: Literals are context dependent

### ISSUE THREAD

**Issue by cloudhan** [gpuweb/gpuweb#2149] opened 2021-09-29 04:17 UTC
As of https://github.com/gpuweb/gpuweb/blob/c524adb545de5ac6ee9c37729888c0ce7d4598cc/wgsl/index.bs#L390-L392

the `-?` as a prefix of `DECIMAL_FLOAT_LITERAL`, `HEX_FLOAT_LITERAL` and `INT_LITERAL`'s regex pattern makes them context dependent.

```
a -2     # token stream is IDENT, MINUS, INT_LITERAL
a - -2   # token stream is IDENT, MINUS, INT_LITERAL
```

**Comment by cloudhan** [comment] 2021-09-29 04:23
Take mature language as examples,

For python, see https://docs.python.org/3/reference/lexical_analysis.html#integer-literals, and for C++ https://eel.is/c++draft/lex.icon both don't treat leading sign as part of literal.

**Comment by dneto0** [comment] 2021-09-29 13:47
This issue is already acknowledged by #775, where we've been calling it the A-5 problem.

**Comment by dneto0** [comment] 2021-09-29 13:57
Closing as a duplicate of #775

**Closed by dneto0** 2021-09-29 13:57 UTC
Labels: wgsl, wgsl:tokens
