### ISSUE TITLE
Assignment operators (e.g. `+=`) in wgsl

### ISSUE THREAD

**Issue by jespertheend** [gpuweb/gpuweb#1518] opened 2021-03-13 16:44 UTC
Are there any plans for adding assignment operators? I.e `+=`, `-=`, `*=`, `/=` etc.
I'm not sure if this would only serve as syntactic sugar or if there's a performance benefit as well.

Either way `pos /= pos.w;` seems a lot cleaner than.
```
pos.x = pos.x / pos.w;
pos.y = pos.y / pos.w;
pos.z = pos.z / pos.w;
pos.w = 1.0;
```
Or is there a better way?

**Comment by alan-baker** [comment] 2021-03-15 14:14
It's not so much the expression combined with assignment that is missing as it is the lack of a vector splat operation. The following is simpler than what you wrote, but still lacks a vector splat.

```
const w : f32 = pos.w; // for convenience, can be forward substituted.
pos = pos / vec4<f32>(w,w,w,w); // ideally, this could be just pos.w.
```

**Comment by jespertheend** [comment] 2021-03-15 14:19
Ah I see.
`pos = pos / pos.w` is what I tried at first and it failed. I wasn't aware these are called vector splats.
Should I create a separate issue for vector splats? Or is this something we likely won't be seeing before MVP anyway?

**Comment by alan-baker** [comment] 2021-03-15 14:23
I don't think it hurts to record a user desire for these features, so I would file the issue (or rename this one). Right now, WGSL supports this only for `vec * scalar` because it has a direct mapping to a SPIR-V instruction.

**Comment by kvark** [comment] 2021-03-17 15:26
Let's postpone `+=` and friends till after MVP?

**Comment by litherum** [comment] 2021-03-17 15:53
I’ve seen this called “broadcast” rather than “splat”

**Comment by ben-clayton** [comment] 2021-03-17 16:35
I'm familiar with splat for this type of thing.
I'd be hesitant to use broadcast, as it [has a different meaning in SPIR-V](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpGroupBroadcast).

**Comment by dneto0** [comment] 2021-03-18 16:23
The vector-constructor-from-scalar PR #1527 landed without having to make up jargon for the concept.  I don't think we need to decide on a name.  (That's one of the four hardest things in computing: naming, off-by-one errors, and cache invalidation)

I always considered "splat" to be jokey internal jargon among compiler folks.  I only meant to fix a term for discussion within specific issues, not to write in the WGSL spec.

> I'd be hesitant to use broadcast, as it [has a different meaning in SPIR-V.](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpGroupBroadcast)

Those are the _uniform_ variants, which are in OpenCL (with cl_khr_subgroups), but not in Vulkan SPIR-V.  

HLSL shader model 6  has the concept non-uniform "broadcast".  
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-0-features-for-direct3d-12#wave-broadcast   There are two operations WaveReadLaneAt and WaveReadLaneFirst.

These correspond to  SPIR-V instructions for _non uniform_  broadcast: [OpGroupNonUniformBroadcast](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpGroupNonUniformBroadcast) and [OpGroupNonUniformBroadcastFirst](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpGroupNonUniformBroadcastFirst).  Those are available in SPIR-V 1.3, usable by Vulkan (when the subgroup-ballot feature is supported and enabled)

**Comment by jdashg** [comment] 2021-06-01 08:09
Statements not expressions here, I think. Expressions should be treated (with vanilla `=`) separately.

**Comment by kainino0x** [comment] 2021-06-15 16:54
FWIW: I think the example above could, simply be written `pos = pos / pos.wwww`? Without the need for a `vector / scalar` overload.

BTW, I had a hard time finding this section: https://gpuweb.github.io/gpuweb/wgsl/#vector-access-expr
and ended up finding it by searching `.zy`. Perhaps it should mention the word `swizzle`, and maybe common swizzles like `.xyz` and `.rgb`.

**Comment by dneto0** [comment] 2021-06-15 19:53
Discussed in the [2021-06-15 meeting](https://docs.google.com/document/d/1UCGtXd7tSrG7C2xTM3fs_NeBALBGYA1D4xbuqUKiZfk/edit).

The group confirmed the decision to defer further work until after MVP.

**Comment by jdashg** [comment] 2021-06-15 20:08
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-06-15-Minutes#-assignment-operators-eg--in-wgsl-1518httpsgithubcomgpuwebgpuwebissues1518">WGSL meeting minutes 2021-06-15</a></summary>



*    MM: Defer to post-MVP
*   JG: Agree
*   DN: Agree


</details>

**Comment by dneto0** [comment] 2021-11-16 22:30
This was re-raised in #2241 
That has active discussion, so closing this one.

**Closed by dneto0** 2021-11-16 22:30 UTC
Labels: wgsl
