### ISSUE TITLE
wgsl: vec2 shouldn't be a keyword; disambiguate parsing of type construction expr `vec2<i32>(0,1)`

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3739] opened 2023-01-13 19:08 UTC
We previously agreed that user declarations can shadow predeclared types and builtin functions.
So, for example type names like `i32` should not be keywords.
There outstanding work to remove them from the spec. See #3277.

At that time, we agreed that types that use parameterizations should still have their introducing name be a keyword. Things like vec2, array, and mat2x4.

This is bad for a few reasons:

1. This introduces an unsettling irregularity to the language: Why are some types special and others not?
For example, `texture_external` would not be a keyword, but `texture_1d` would be a keyword since it's instantiated as `texture_1d<f32>`

2. We expect a future where user-declared functions can be parameterized, and calls can have overload parameterization at the call site.
So this problem extends to user-declarations, not just a handful of types known to us now.

3. What if we want to introduce more predeclared type in a future version of WGSL.  Do we have to reserve their base names as keywords now?  This seems fragile.

It's better to decide *now* that `array` `vec2`, and things like them (a name followed by type parameterizations) should *not* be keywords, and deal with the problems this raises now, in time for v1.

In more detail, here's the problem:

## Spelling types where an expression is expected

Example:

        type ha = i32;
        const y = 1 + vec2<ha>().x

When parsing `1 + vec2<ha>().x`   the use of `<` is ambiguous because it looks like a less-than operator.  We would need too much lookahead, up to the open-parenthesis, to see that it's a type-constructor expression of a two-element vector.

WGSL allows creation of a value of a specific type via a type constructor expression: https://gpuweb.github.io/gpuweb/wgsl/#type-constructor-expr 

Basically, the expression is the type name followed by a parenthesized list of components.
See https://gpuweb.github.io/gpuweb/wgsl/#syntax-call_phrase where a "callable" is one of these things:

call_phrase :
| [callable](https://gpuweb.github.io/gpuweb/wgsl/#syntax-callable) [argument_expression_list](https://gpuweb.github.io/gpuweb/wgsl/#syntax-argument_expression_list)

callable :
| [ident](https://gpuweb.github.io/gpuweb/wgsl/#syntax-ident)

| [type_specifier_without_ident](https://gpuweb.github.io/gpuweb/wgsl/#syntax-type_specifier_without_ident)

| [vec_prefix](https://gpuweb.github.io/gpuweb/wgsl/#syntax-vec_prefix)

| [mat_prefix](https://gpuweb.github.io/gpuweb/wgsl/#syntax-mat_prefix)

| ['array'](https://gpuweb.github.io/gpuweb/wgsl/#syntax_kw-array)

This is unambiguous when:
* The type name is just an identifier
* We use keywords to introduce any type that takes type parameters surrounded by `<` and `>`.
      * This is why `array`, `vecN` forms, and the `matMxN` forms are keywords.

If `vec2` is no longer a keyword, then we get the ambiguity shown above.
The essence of the problem is that `<` is a binary operator that can appear immediately after an identifier.

## Alternatives

Each of these assumes things like `vec2` are not keywords, and can be shadowed by a user declaration.

### Parsing Layering violation
 When parsing, resolve the identifier to know what kind of thing it is, so we know how to parse the next token.
  
I think this is a bad solution. Layering violations are fragile, and have to be replicated in all tools that need to process WGSL.  Also, out-of-order declarations make it much more involved and hard to read.

### Add introducer token

Introduce a keyword like `make` to say "in the thing that follows is a type constructor expression where the next  `<` token is read as introducing a type parameterization"

    const y = 1 + make vec2<ha>().x

and  later introduce `call` for calls to user-declared overloads.

      let x = call mytemplated_func<f32>(12.0f);

### Use !< instead of < for introducting type parameterization

Where `<` would be ambiguous, use token `!<` instead:

    const y = 1 + make vec2!<ha>().x

Alternative:  **Always** use `!<` for introducing a type parameterization list.

Maybe these aren't so terrible because perhaps authors will use the shortcuts we've provided, e.g. `vec2f`, which don't need this solution.

Note: This works because `!` is a unary operator that can't appear right after an identifier.

### Use D's syntax  !( ... )

Change all type parameterization to be like   foo!(a,b) instead of foo<a,b>

        type ha = i32;
        const y = 1 + vec2!(ha)().x

(This is nicer for text editors where you can bounce between matching parens, like vi's % action)
    

----------
edit: remove the stray "make" in the last example.

**Comment by mehmetoguzderin** [comment] 2023-01-13 19:54
Would this change bear similar implications for `bitcast` too, where the spec can drop it from the syntax itself?

**Comment by dneto0** [comment] 2023-01-13 22:00
> Would this change bear similar implications for `bitcast` too, where the spec can drop it from the syntax itself?

It opens up the possibility, but it's a different kind of thing.  It could be a predeclared builtin function, but we would have to indicate the destination type somehow.  I could see `bitcast!(f32)(i32)` working.

**Comment by mehmetoguzderin** [comment] 2023-01-13 23:13
@dneto0 Would comma suit to simplify as `bitcast!(f32, i32)`, where first would be "to, destination" type and second would be "from, source" type, with at least source type being able to be inferred, instead of each type creating a parenthetical chain?

**Comment by dneto0** [comment] 2023-01-13 23:26
> @dneto0 Would comma suit to simplify as `bitcast!(f32, i32)`, where first would be "to, destination" type and second would be "from, source" type, with at least source type being able to be inferred, instead of each type creating a parenthetical chain?

Right, sorry I meant to write something like:  `bitcast!(f32)(15i)`  The first set of parentheses are for destination type, and then consider it taking a single value as an argument.

So far in the spec a functions arguments are always *values*, and have rules about when they are evaluated, and they also play a role in uniformity analysis.

**Comment by mehmetoguzderin** [comment] 2023-01-13 23:53
Right, I was thinking in lines of `bitcast!(to, from)(value)` since I thought that i32 was typename, leading to a third parenthetical `bitcast!(to)(from)(value)`. So, the arguments would still be values only

**Comment by dneto0** [comment] 2023-01-15 20:18
One more thing about D's syntax: If the template argument is a single token then you don't need the parenthesis.
[reference](https://dlang.org/spec/template.html#TemplateSingleArgument:~:text=If%20the%20TemplateArgument%20is%20one%20token%20long%2C%20the%20parentheses%20can%20be%20omitted%3A)

So this would be allowed:

         vec2!(f32)
         vec2!f32   // same thing

See the D grammar here: https://dlang.org/spec/template.html#explicit_tmp_instantiation

**Comment by teoxoy** [comment] 2023-01-17 15:35
Considering we now have abstract types + constructors that take and return those, we could remove the constructor forms that take in those scalar "generics".

Thughts?

**Comment by ben-clayton** [comment] 2023-01-17 17:33
> Considering we now have abstract types + constructors that take and return those, we could remove the constructor forms that take in those scalar "generics".

That wouldn't help with language evolution. We'd still be stuck if we wanted to add a new templated type to the core language (without `enable`), or to add support for user-declared templated functions / types.

**Comment by mehmetoguzderin** [comment] 2023-01-17 19:22
In case the direction goes for angle brackets, Rust's syntax for GenericArgs `a::<b, c>` is also a good balance: https://doc.rust-lang.org/reference/paths.html#paths-in-expressions

**Comment by ben-clayton** [comment] 2023-01-17 19:36
> In case the direction goes for angle brackets, Rust's syntax for GenericArgs `a::<b, c>` is also a good balance: https://doc.rust-lang.org/reference/paths.html#paths-in-expressions

Turbofish imposes constraints on template expression arguments, which some have objected to:

> Const arguments must be surrounded by braces unless they are a [literal](https://doc.rust-lang.org/reference/expressions/literal-expr.html) or a single segment path.

**Comment by mehmetoguzderin** [comment] 2023-01-17 19:45
But I think that kind of shows there is a robust solution if the issue of parsing ambiguity for expressions as (const) generic arguments arises. Of course, not objecting if such a scenario in the future is not a surprise for the heuristic model.

**Comment by mehmetoguzderin** [comment] 2023-01-17 19:47
For reference, the following page lists the cause of that: https://doc.rust-lang.org/reference/items/generics.html#const-generics

> A const argument in a [path](https://doc.rust-lang.org/reference/paths.html) specifies the const value to use for that item. The argument must be a [const expression](https://doc.rust-lang.org/reference/const_eval.html#constant-expressions) of the type ascribed to the const parameter. The const expression must be a [block expression](https://doc.rust-lang.org/reference/expressions/block-expr.html) (surrounded with braces) unless it is a single path segment (an [IDENTIFIER](https://doc.rust-lang.org/reference/identifiers.html)) or a [literal](https://doc.rust-lang.org/reference/expressions/literal-expr.html) (with a possibly leading - token).
>
> **Note**: This syntactic restriction is necessary to avoid requiring infinite lookahead when parsing an expression inside of a type.

**Comment by ben-clayton** [comment] 2023-01-17 20:02
I understand why it's done, but it's a fudge to constrain what can be used as an expression in a particular place - and this is something that people have explicitly stated they object to.

note: I'm aware that it is very similar to the fudge we currently have on the `array` count argument.

[#3746](https://github.com/gpuweb/gpuweb/issues/3746) has the nice property that expressions are always just expressions, and there's no weird limitations in certain places in the grammar.

**Comment by kdashg** [comment] 2023-01-18 17:53
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-01-17-minutes#wgsl-vec2-shouldnt-be-a-keyword-disambiguate-parsing-of-type-construction-expr-vec2lti3201-3739-">WGSL 2023-01-17 Minutes</a></summary>

* Ambiguity parsing: `A ( B &lt; C, D > ( E ) )`
    * `A ( B &lt; C, D > ( E ) )`
    * `A ( B &lt; C, D > ( E ) )`
* DN: Spawned lots of internal discussion. Trying to be respectful of future. Example from BC, if we have generic templates, and have 3 things (oo declarations, shadowing and user templates) get into corner. Looking for options. Provided 3 which change syntax, all kind of distasteful in one way or another. BC has proposal from an hour ago [https://github.com/gpuweb/gpuweb/issues/3746](https://github.com/gpuweb/gpuweb/issues/3746)  on how to use algorithm to disambiguate to favour the template interpretation. Was just [playing with toy grammar to look at this](https://github.com/gpuweb/gpuweb/issues/3746#issuecomment-1385897818) .Current state of mind, think we should think about this, or we don't panic or change and defer. Hard problem is anticipating user declared templates, but we've also said use JS in the past. Not resolved within Google but want to raise and cause a dustup as now is the best time to do it.
* KG: Agreed. We should figure this out.
* JB: At moz we were friendly to the suggestion that WGSL follow D syntax. Haven't had a chance to look at proposed heuristics. Doesn't sound good to me that we can't clearly tell users how to write one or the other. Think having heuristics which go above and beyond sounds like ti would create a delicate situation. Understand it appears to work fine on existing corpus. Don't understand it yet. I think that if we take as a given that we must have c++ constructor syntax then that's just a stringent requirement. It doesn't make a lot of sense to me. The world isn't made of c++ or this one thing. The fact is, things do not explode when you make a minor variation in the notation. Don't want to be boxed out of considering new syntax. We already know the consequences and we are talking because they are unpalatable. If we choose new syntax we can use the same for both declarations and constructors as it's a service to users to have a single syntax. It is difficult to do that if we accept the straight jacket of c++ syntax. Feel like the folks who are saying we must use c++ syntax haven't' given much room to negotiation. When say what want, say why like it, not just my way or the highway.  Can folks giving objections provide the conditions and what they're open to negotiations on.
* KG: Thanks, that's valuable.
* BC: Internally contemplated the various proposed syntaxes. `!&lt;` that seems more palatable with certain people as it's more c++ like. Does suffer from some ambiguity on the terminator. Can ! the start &lt; but  but still suffer from &lt; boolean. Can do nicely with D syntax as it handles the nesting, good for parser simplification, folks don't like it. Looks weird. Major complaints, if you have a template list followed by user function. Type like array&lt;f32, 2> if used syntax `array!(f32, 2)(2, 2)` that `)(` seems to be what upsets people. Counter to that for single param you can remove the parens like `bitcast!f32(2)` For folks with c background, looks like a c function pointer. Criticism is taking features from many languages and have c syntax, and rust syntax and now adding d syntax. Folks raising concerns is that our general population of shader writers will be up in arms about it being a late change (Google was trying to ship this year). Changing types now would upset folks. The primary contender for change folks aren't keen on. If it parse easily or not, folks like c++ template signature. As for the don't know if it will parse, the way written is possibly not the most elegant but is fully deterministic. No magic determination based on identifiers, pure parse based on tokens. Tried to lookup c# which has same problem, and think what I’m proposing is the same as they have. Written c# for many years and never had it go the wrong way. Ran through 50k WGSL shaders and 2 went the wrong way in pathological cases doing bad things with for loops. Moderately confident the heuristic parse wouldn't be a major foot-gun and easy to guide users into fixing. Fix is to add parens and would have had weird parens anyway. Already require parens for binary ops and associativity.
* JB: If it is true that this is what c# has done, that is encouraging. If there is something we can take off the shelf that has burn time on someone else's dime that changes my feelings a lot. **We need to take some time to read the proposal**. Someone else can understand the c# approach and maybe that's the way forward. 
* BC: Not absolutely certain it matches c# perfectly. Tried to find other languages that solve this and took inspiration from c#.

</details>

**Comment by mehmetoguzderin** [comment] 2023-01-20 02:29
For illustration of how turbofish does not bloat too much in spec examples, I've got this demo up: https://github.com/gpuweb/gpuweb/pull/3765
Preview: http://raw.githack.com/gpuweb/gpuweb-pr-previews/c9b1abb88711b3d9cef07aaa981602c139afd68b/gpuweb/gpuweb/3765/wgsl/index.html

**Comment by vincentisambart** [comment] 2023-01-25 11:24
Not sure if it's useful but here's what I thought as an outsider reading [this week's meeting minutes](https://docs.google.com/document/d/1RNQUP-K8-jWVnvrbsVEFaUbK31NYr3YWjyBDvX_Lyso/edit).

- I have nothing against the C++ syntax for templates by itself, but I did not understand the attachment to the C++ syntax, especially with a lot of syntax already being not very C++ (function and variable declaration being the most obvious, but even the `switch` statement is pretty different from a C++ `switch`). And I'm not sure how many of the people using WGSL are going to be C++ programmers, but I would not be surprised if a lot of those C++ programmers would just be cross-compiling from SPIR-V/GLSL/HLSL (and so the syntax would probably not matter much for them). Also as someone used to switching between multiple languages, you get used to most simple syntax differences pretty quickly, even if they seem foreign at first.
- If you keep the current syntax and go with the heuristic route, it looked like to me that parsing would just get more complicated. It seemed like some work was done to make most of the syntax parsable using a parser generator, but such a heuristic might break that. It would probably make writing new WGSL tools a bit harder. And if a user ends up with a corner case not handled well by the heuristic, you would likely need good error messages to understand what's going on. Changing a bit the syntax breaking current users is unfortunate but I think you should think longer term here.
- If you made whitespace significant, (leaving aside how it feels,) parsing should not be too hard, and you would probably end up with code that's easy to read, but I'm afraid a lot of people would often see compilation errors because they forgot to put a space around operator, especially when trying something quickly or debugging.
- If you decide to close the door for user declared templates in the future to remove the grammar ambiguity, I think that would be a big mistake, not worth keeping the current syntax. And using a diffent syntax for user declared syntax would makes things harder to grasp to the user.
- If you go with another syntax, I think that syntax being the turbo fish `vec4::<f32>()`, something like `vec4!<f32>()`, or D's `vec4!(f32)()`, would not really matter. Even if you find the one chosen strange at first, it will propably grow on you pretty quickly (though if you go with D's syntax, I don't think you should allow both `vec4!(f32)()` and `vec4!f32()`, having multiple ways to express the same thing just to win a few characters does not seem worth it)

**Comment by kdashg** [comment] 2023-01-31 01:30
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-01-24-minutes#wgsl-vec2-shouldnt-be-a-keyword-disambiguate-parsing-of-type-construction-expr-vec2lti3201-3739-">WGSL 2023-01-24 Minutes</a></summary>

* [Lookahead disambiguation of less-than vs template argument list (v2) #3770](https://github.com/gpuweb/gpuweb/issues/3770) 
* [Is it intended that keywords can not be identifiers? #3692](https://github.com/gpuweb/gpuweb/issues/3692) 
* DN: BC posted v2 of pre-tokenization. Goes through source and identifiers that are template lists. Things in various contexts allowing nested expressions. Wondering folks opinion on interposing a thing which changes the meanings of certain &lt; > signs to be TemplateIntroducer and TemplateTerminator
* JB: Moz was excited for maybe borrowing the solution from c# and it seems like c# just has a (???) keyword. We're not stoked that the commitment to looking like c++ is so strong that we are adding infinite lookahead with heuristics. We have to pay infinite lookahead and don't get a firm answer, it's ambiguous in some places. That seems severe dedication to a fixed syntax. Personally it's hard to say the sky will fall if we don't match c++. What all this heroic effort says to me is that Google needs to re-consider whether or not it's open to the idea of making a small change to the syntax. It was drafted to use turbofish, we don't use it in other places but it's analogous to d syntax. It's pretty severe, adding a new pass, can't tokenize as we go, and doesn't disambiguate, just heuristic. `x &lt; y >> z`. Ordinary expression, nothing contrived. I think we're in a difficult situation as we talk about differing syntaxes if it isn't c++ folks won't use it, and that's just not true. Think we need to step back on negotiating positions and be more open to syntax changes.
* BC: c# does have something similar, can give links to where it does the lookahead. Infinite lookahead is one way of phrasing, the second draft is that it's a token transform, but it's a pass of the tokens. Not easily pipeline-able. Example of `a &lt; b >> c` I replied and we already have precedence. If that &lt; was a bitshift you'd need `()`s. Ordinary expression maybe, but WGSL already requires parens, don't see a substantial difference if you need parens to disambiguate.
* JB: Like the way that we require parens in the precedence chart. Think that's a good move for clarity. Just seems like with the parens for associativity we actually asked for that and had the option to not have that and thought it was a positive benefit. Introduced by permitting fewer combinations on purpose. This is a set of parens that are required because we can't bear the glares of our co-workers because they want what they're used to.
* KG: Don't think it's entirely that, just preference for it
* AB: Don't allow expressions in array already. Already have restrictions on expressions
* JB: Apologize, taking workers' opinions into consideration.
* KG: This will become a discussion issue. Spitball idea earlier was something simpler which may break down in complicated situations. One of the ways I parse things as I'm reading and a natural difference to how to write `&lt;` binary expressions and template types and generics is in regards to the whitespace involved. Such that almost always, but not entirely, it's common for there to be whitespace on either side of the &lt; sign. In which case it's almost always a &lt;. Don't remember the last time I saw a template argument that had space on both sides. Commonly there is space on the interior but almost never on the exterior. (`Identifier&lt;  >)` right heuristic, but might disambiguate in different contexts. 
* JB: `identifier&lt;` generic `identifier &lt;` less than?
* KG: Maybe a way to differentiate would be needed
* DS: Whitespace significant makes me sad
* MM: If we make it significant then we say all binary ops require on both sides.
* KG: Not sure that entirely follows but think it's different for arithmetic vs logical
* EG: What about tab
* KG: Counts as blankspace, we have grammar for blankspace. It's not that we never ignore blankspace, it already separates identifiers, not like it's never used, but this would be an expansion of that. 
* DN: Glad you raised it, also have the allergic response to it. Rant against python, one of those points. It's on the record. Pre-tokenization is one solution, new syntax is another solution, another thing at play is either "never have user declared templates' or allowing 2 different syntaxes for this kind of thing. So vec2 stays as it is, the set we have is a good base, user declared templates have a different mechanism with a different look .Not sure if we want to open either of those
* BC: More than user, any core types that take arguments, don't want different syntax for that and have to hope we have them reserved.
* JB: Not sure if it came up or not, already have the case where we ???.So we could say you don't get to use &lt;> as type parens unless you put `new` in front. `new vec3&lt;f32>()`. Or `vec2()` don't get generic args unless you said new.
* BC: So, `new` has heap allocation connotations. With pointers would strongly advise a new prefix. Doesn't solve the need for user generics. Would you prefix the call to user generic function?
* JB: Maybe have inference for those arguments as well.
* BC: Not everything can be inferred.
* KG: Glad to have this on the record, think we've realized none of the things we have are super appealing to everyone. Didn't realize new had parsing value like this, so that's new to me. Interesting in the context of languages that do use and require it. Like having that in the solution space.
* DN: To firm up Jims solution Are you allergic to long lookahead of pre-tokenization?
* JB: Upset about mis-characterizing Googles opinion, I apologize
* DN: It's ok, want to sharpen position
* JB: It seems like heroics, it's clearly heroics given you've worked so hard for so long and now to just give in. The other side of the trade off which is preserving the syntax just doesn't seem worth it to me. Obviously we can't in this meeting take absolute positions because we have to leave things open for discussion but you're spending a lot, is that really the balance you want? The balance seems bad to me. I don't absolutely object but it's expensive.
* EG: Wanted to ask for what other options were
* DN: New syntax
    * backing away from user declared having similar syntax
    * Or not having user declared templates.
* EG: May have mis-understood something said `using` syntax?
* DS: We have aliases for somethings like `vec4f` but not for things like `texture_storage_2d`
* KG: You could write an alias for that and then it would be in expression context.
* BC: It's a combination of people not being fond of the alternative but possibly more weighted is changing the language will throw us off. Thursday is the branch for last chrome release where we can do deprecations. If we're changing syntax we'll delay the chrome v1 which is pretty disruptive.
* KG: Understandable. The main reason we're talking about this now is, since we do want generics in the future we need something in place we have confidence we'd move towards in the future. It's hard to have that confidence in something like this without having a solution. What we're doing here is we want a solution in mind that is prototype-able in v1 even if we don't ship in v1. Something we can go to moving forward, even though there are no generics in v1. Does that sound like the right amount of caution?
* BC: **That's the stance we're going**. The proposal for the lookahead has landed in tint and we've made it a hard error for ambiguous cases. **Wanted to get feedback**. Primes us if we go down this path to do this without disrupting shaders at a later date. Need a solid plan for language evolution.

</details>

**Comment by litherum** [comment] 2023-01-31 02:49
Our opinions are very mild.

- We don't think `vec2` (& co.) should be a keyword. Our strongest opinion is that we don't want to give the parser knowledge about type names to decide how to parse things.
- We don't expect lookahead to be a real performance problem on real content (we have semicolons, and lines usually aren't that long)
- If there is a performance problem on crafted content, there are already facilities to report an uncategorized error, which allow us to interrupt the compilation
- We're not super thrilled about inventing new syntax, or reusing syntax from another language.
- If the CG is going to use new syntax (contrary to our above desires), we'd prefer `vec2!<T>(...)` or `make vec2<T>(...)`.
- Alternatively, we could also go the Haskell route: types must start with an uppercase letter, variables must start with a lowercase letter.

**Comment by greggman** [comment] 2023-01-31 05:04
> Alternatively, we could also go the Haskell route: types must start with an uppercase letter, variables must start with a lowercase letter.

WGSL seems to intentionally allow CJK identifiers where there's no upper/lower cases. Isn't having to stick other unrelated characters in front at odds with that?

**Comment by mehmetoguzderin** [comment] 2023-01-31 05:28
It sounds like the bangfish `!<>` might be a good balance. And it is only one character that's not heavy on the eye, so even optionality is not essential for the type_specifier variant.

**Comment by dneto0** [comment] 2023-01-31 16:10
Thanks @litherum for the perspective.

Regarding one point:

> Alternatively, we could also go the Haskell route: types must start with an uppercase letter, variables must start with a lowercase letter. 

I think this does not address a potential future where there are templated calls to user-declared *functions*.

**Comment by munrocket** [comment] 2023-01-31 21:54
Sorry, is there any alternative to  `!<>` syntax? Maybe some another solution without unusual syntax?
```
array!<vec3f, 30>
atomic!<i32, 2>
```
It is bad if `array` `atomic` and `vec2`,`vec3`,`vec4` will be a keywords in wgsl?

**Comment by mehmetoguzderin** [comment] 2023-01-31 22:05
@munrocket at today's meeting, consensus was to certainly keep existing generics as-is (no bangfish, no turbofish). So, they'll stay as `array<>`, `atomic<>`, but will probably have a more generalized expression in grammar which matches the behavior of them being keywords. 

Minutes: https://docs.google.com/document/d/1OzbsdZTaUaNLIXp4DFFAk-dJfTOGsj2Wq7wllsG3vd8

**Closed** 2023-02-24 15:29 UTC
Labels: wgsl
