### ISSUE TITLE
Determine limits for point size

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#263] opened 2019-04-04 23:30 UTC
We should figure out how to set the point size. In Metal, the size is set by the vertex shader. GL has `glPointSize()`. I don't know what the other APIs use.

**Comment by magcius** [comment] 2019-04-04 23:31
`glPointSize()` is deprecated. In GLSL `gl_PointSize` is used, HLSL has the `PSIZE` semantic.

**Comment by litherum** [comment] 2019-04-04 23:32
Yep.

Also, we'll need to figure out what the limits on the point size are. IIRC some implementations don't let you set very large points.

**Comment by litherum** [comment] 2019-04-04 23:38
WHLSL already has `PSIZE` (and it works properly) so I suppose this issue is resolved.

**Comment by Kangz** [comment] 2019-04-05 15:03
The problem is that the behavior for clipping points larger than one texel differs between hardware. IIRC AMD clips as soon as the center of the point is outside of the scissor region while other hardware clips if the circle is completely outside the scissor region.

That's why WebGL chose to limit the point size to be 1 at max.

**Comment by jdashg** [comment] 2019-04-15 18:54
I thought it was for a different reason, like d3d9 support.

**Comment by jdashg** [comment] 2019-04-15 18:56
Also, WebGL definitely lets you have point size >1.0! It's just not
required.
That said, these days support for gl_PointSize=100.0 is nearly universal:
https://webglstats.com/webgl/parameter/ALIASED_POINT_SIZE_RANGE

**Comment by kvark** [comment] 2019-04-22 21:22
@Kangz I guess we can enforce a specific behavior here: the vertex shader knows both the output position and the size. We can check if the center is outside of the screen and just move it away completely.

**Comment by Kangz** [comment] 2019-04-23 08:03
@kvark good point, although I'd argue that's the least useful of the two options.

**Comment by Kangz** [comment] 2021-09-02 13:02
Closing. WebGPU only has points of size one and it is not possible to control the size (WGSL doesn't have a point_size builtin)

**Closed by Kangz** 2021-09-02 13:02 UTC
