### ISSUE TITLE
vec4<f32> is too hard to type on the keyboard

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#736] opened 2020-04-30 02:25 UTC
We should consider renaming this to `float4` or `vec4` (and ditto for `uint4`, etc.)

We also may want to use the `<>` syntax for something else in the future.

**Comment by Kangz** [comment] 2020-04-30 08:09
IMHO the explicitness is a good thing. With type aliases, it should be possible for people to have these shorthands in a "prelude" in their shader:

```
type float4 = vec4<f32>;
type uint4 = vec4<u32>;
```

**Comment by lain-dono** [comment] 2020-05-02 01:39
At least in Rust, C++ and TypeScript `<>` syntax is used to denote compilation time parameters (generics, templates, etc.). In addition, readability is more important than writeability.

**Comment by kainino0x** [comment] 2020-05-02 01:45
Agreed, if we wanted to use `<>` for generics that would be fine; this is just a compiler-specialized generic.

**Comment by litherum** [comment] 2020-05-02 17:21
This name has 3 digits in it, and makes you press the shift key twice. This is difficult for typists to type for a term that will be one of the types that will be most common to write. No existing shading language makes authors do this.

Yes, authors can make their own aliases, but we should also pick good defaults so authors don’t have to do that. The defaults matter.

In this thread, there have been arguments why it’s _acceptable_ to use vec4<f32>, but no arguments why it’s better. I have provided an argument why it’s actually worse.

One way to resolve this is to follow HLSL and have both forms. We can make the typedefs implicit so authors can just use whichever form they prefer.

**Comment by grovesNL** [comment] 2020-05-02 17:54
A possible argument for why it's better is that it's consistent with all of the other types, e.g. `matNxM<T>`, `array<E,N> `, `struct<T1,...,Tn>`.

> One way to resolve this is to follow HLSL and have both forms.

If we eventually want to have shorthand, then maybe we could proceed with the current form for the MVP, and later consider exposing implicit typedefs or an optional prelude that contains them.

**Comment by dj2** [comment] 2020-05-04 14:28
We can always add extended forms later if they're requested. We can't remove them if they aren't useful.

The benefits I see to `vec4<f32>` are:
 * Consistency, it's the same syntax for vector, matrix, array, etc
 * Extensible, when we add `vec4<f16>` does it also get a second name? What about int8, int16, int64, etc?
 * Can already be shortened by `type vec4 = vec4<f32>;` if desired
 * The explicitness makes it easier to understand.

**Comment by munrocket** [comment] 2020-05-09 19:33
vec4<f32> - for pianists. f32x4 like in wasm or classic vec4 looks better for such basic word.

>Consistency, it's the same syntax for vector, matrix, array, etc

Then you should add also 
```
alias loop = while
alias entry_point = pink_pony
```
after that we can make the truly unreadable shaders that looks like a poems

**Comment by othermaciej** [comment] 2020-05-09 20:06
Many programming languages that use `foo<bar>` as a generic/template syntax have predefined aliases for commonly used types. For example, C++ `std::string` is actually `std::basic_string<char>`. The alias is provided by the standard library and the long form is almost never used here.

I think it may be valuable to have some predefined aliases. This is better for readability than each shader defining its own alias. Perhaps a certain set of predefined aliases could be considered part of the standard library rather than the language proper. It's ok if not every specialization of a generic type has an alias.

**Comment by dneto0** [comment] 2020-05-11 15:47
I want to amplify @dj2's point that whatever we do has to scale up to future types like vectors of 16bit floats.  It's best if that's done in a very regular way.

For example, note the potential confusion over int16 (which in OpenCL C is a 16-element vector of 32 bit signed ints) vs int16_t which is something else in C.

The SPIR-V disassembler by default constructs somewhat regular names for scalar and vector types.   E.g. that disassembler's  `v4float`  is the same as WGSL's `vec4<f32>`
By comparison, LLVM assembly language has `<4 x float>`.

Separate point: the use of < and >  means we don't eat into the programmer's namespace.    Preserving the programmer's namespace is a component of the "plan-for-the-future" topic: #600

**Comment by dneto0** [comment] 2020-05-14 20:02
Here's one example of bad scaling:

floating point types:
- float vs. double :  two very closely related types, but 'float' describes its having a floating point representation. But then "double" is about a size.
- float vs. half.  Once you've committed yourself to a sizing description, half is natural-ish.  But then that again conflicts with 'float'.     On its own "half" appeared non-sensical to me.

An example of good scaling:  LLVM's  i1, i8, i16, i32.  In fact it's iN where N is non-zero; it all just works as you'd think.  Regularity is a big win.   (I *have* used iN with very nonstandard N.)

Bad scaling, IMHO:    GLSL's  vec4 vs. ivec4 vs. uvec4.    It truly begs the question what 'vec4' meant in the first place, and requires you to carry another piece of context in your head.

**Comment by litherum** [comment] 2020-05-19 17:28
`float`, `double`, and `half` are terms-of-art, though.

**Comment by dneto0** [comment] 2020-05-19 17:39
So are `real` and `single`.  C was the oddball at the time in choosing "float".

**Comment by johnkslang** [comment] 2020-05-20 04:41
A lot of lines of shader code are:

- write once (maybe twice or three times)
- debug lots (tends to take longer than typing)
- read many many many times

For an explicit language that will be targeted by your favorite sugar-full HLL, this seems okay.

I also suspect almost all such problems can be worked around by a clever m4 header (probably even `for`-loop support), but that should be left outside the API, keeping what crosses the API explicit.

**Comment by litherum** [comment] 2020-05-26 17:34
@dj2

> The benefits I see to `vec4<f32>` are:
> 
> * Consistency, it's the same syntax for vector, matrix, array, etc
> * Extensible, when we add `vec4<f16>` does it also get a second name? What about int8, int16, int64, etc?
> * Can already be shortened by `type vec4 = vec4<f32>;` if desired
> * The explicitness makes it easier to understand.

I don't understand the consistency & extensibility argument. Adding built-in aliases for `float4` / `half4` / `double4` / `int4` / `short4` / `byte4` / `uint4` / `ushort4` / `ubyte4` seems pretty consistent and extensible to me.

Regarding the user-defined typedefs, I should probably have mentioned that this issue isn't motivated by abstract desire for familiarity in languages; it's a request from one of our internal teams trying to use WGSL. We know that we can make our own typedefs, but that doesn't work for documentation / forums / blog posts, etc.

I disagree that `vec4<f32>` is more explicit, but even if you disagree with me, I'm proposing adding typedefs to the standard library, which will still allow people to use the `vec4<f32>` if they really want to. So I don't think the explicitness argument makes sense either.

**Comment by dj2** [comment] 2020-05-26 17:50
What was the request from the internal team? That it's too hard to type? Not the same as other languages? What is their issue that is trying to be solved with this request?

**Comment by litherum** [comment] 2020-05-26 17:59
From our team (author's name omitted to protect the innocent):

> This vec4<f32> is really hard to type compared to float4, and much less readable.
> I find this much easier to debug.  The template machinery overwhelm the important type.   There’s only one letter difference for me to extract the differences.
> `ubyte4` -> `vec4<u8>`
> `ushort4`  -> `vec4<u16>`
> `uint4`  -> `vec4<u32>`
> `float4` -> `vec4<f32>`
> It's not readable or the norm.

**Comment by aloucks** [comment] 2020-05-26 18:22
```
ubyte4 ->  vec4<u8>
ushort4 -> vec4<u16>
uint4 ->   vec4<u32>
float4 ->  vec4<f32>
```

I find the items on the right easier to both read and to type. I guess it's subjective.

The prefix is also always the same which has a benefit of everything lining up and looks much more consistent.

**Comment by litherum** [comment] 2020-05-26 18:32
Issue about namespaces: https://github.com/gpuweb/gpuweb/issues/777

**Comment by litherum** [comment] 2020-05-26 18:39
Issue about expansion: https://github.com/gpuweb/gpuweb/issues/600

**Comment by kainino0x** [comment] 2020-05-26 18:41
Re: @kvark's comment about blanket imports (e.g. `import * from type_aliases`). We could disallow them and require, say,
`import { fvec2, fvec3, fvec4 } from type_aliases`

This makes adding items to namespaces non-breaking, at the cost of `O(number of different types)` boilerplate (an improvement over `O(number of usages)` with no change from the current spec).

**Comment by kainino0x** [comment] 2020-05-26 18:53
I think we agreed already, but here's another reason not to use e.g. `int4`: not only does it sort of mentally conflict with `i32`, it also mentally conflicts with C's `int32_t`.

Also `vec16<f32>` may be within the realm of possibility (wider SIMD) and `float16` would suddenly be extremely confusing. `hvec16` would be clear.

Another thing: there's unfortunately no obvious name for `vec4<i8>`. `bvec4` ('byte') conflicts with `vec4<bool>`, `cvec4` ('char') is weird.

**Comment by grorg** [comment] 2020-05-26 19:02
Discussed at the [2020-05-26 meeting](https://docs.google.com/document/d/1KuWVqle7kNaQgjcPxk_iqBZYCbgP9yIg_Ek7t7D8k3w/).

**Comment by grorg** [comment] 2020-05-26 19:04
Basic summary of position at the end of the meeting:

- Add the namespacing mechanism
- ivec4, bvec4, fvec4 dump into a namespace
- allow that namespace to be imported
- something like “using” to allow the namespace to be used without prefixes

@litherum is tasked to write that up more formally (not necessarily a PR). @kainino0x also had a comment to make (maybe that was the one above?)

**Comment by kainino0x** [comment] 2020-05-26 19:19
Yes, it was the first one above (and then I had another) :)

**Comment by CrazyPython** [comment] 2020-06-24 23:43
I propose the syntax `vec4!f32`. The arguments after the ! are equivalent to what's inside `<` and `>`. Parentheses are optional for one argument. For arrays, it would be `array!(int, 4)`. This also has the advantage of being easier to parse.

**Comment by litherum** [comment] 2021-02-23 04:49
Options:
1. What [MSL](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#//apple_ref/doc/uid/TP40014364), [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-vector), [CUDA](https://developer.nvidia.com/blog/cuda-pro-tip-increase-performance-with-vectorized-memory-access/), and [`simd/simd.h`](https://developer.apple.com/documentation/accelerate/simd) have: `{bool,int,uint,half,float}{2,3,4}`
2. What [GLSL has](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.html#basic-types): `{vec,bvec,ivec,uvec}{2,3,4}`
3. What [Intel assembly has](https://docs.microsoft.com/en-us/cpp/cpp/m128?view=msvc-160): `__m128`, `__m128i`
4. What [ARM NEON assembly has](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/neon-programmers-guide-for-armv8-a/optimizing-c-code-with-neon-intrinsics/program-conventions): `{int32,uint32,float32}x{2,3,4}_t`
5. What [Swift](https://developer.apple.com/documentation/swift/swift_standard_library/numbers_and_basic_values/simd_vector_types) has: `SIMD{2,3,4}<{UInt32,Int32,Float16,Float}>`
6. A proposal [above in this thread](https://github.com/gpuweb/gpuweb/issues/736#issuecomment-634217336): `{ivec,bvec,fvec}{2,3,4}` (possibly with `uvec{2,3,4}` too)

We also would have to decide if we're going to give the same treatment to matrices too.

**Comment by litherum** [comment] 2021-02-23 04:50
Given the popularity of option 1, I think that one is the clear winner.

**Comment by kvark** [comment] 2021-02-23 05:07
The problem with (1) is that WGSL, unlike MSL/HLSL/CUDA, doesn't have separate `int`/`uint`/etc types. Our types are `i32`/`u32`/etc, so blindly following this popular option would be inconsistent with WGSL today. In that sense, option (2) fits slightly better: both `i32` and `ivec` have a clear common prefix, at least
Clearly though, (4) is most consistent with WGSL: `i32x2`, `f32x4` are straightforward derivatives from our scalar types, although it's a scheme we are not used to.

**Comment by parasyte** [comment] 2021-02-23 06:36
My two cents:

Types with names like `float4` are not self-documenting. Rhetorically, how many bits does such a type require for storage? `f32x4` is comparatively more reasonable in this regard. `vec4<f32>` is also reasonably self-documenting, even if it is more to type. (Also to note, the reason for C choosing names like `int` and `float` is that the language was designed at a time when memory resources were very precious. Languages that inherited syntax from C did so for familiarity reasons; laziness can be a feature. There is nothing wrong with that _per se_, but these were all missed opportunities to make improvements.)

On the subject of typing, programming is more about communicating ideas well than optimizing for fewer or easy-to-reach keystrokes. This is why code-golf is always a bad idea for production code. See also: https://blog.codinghorror.com/is-writing-more-important-than-programming/ Readability and writability of a language are in direct conflict with one another, and often subjective. Some people prefer to measure "maintainability" instead of "readability" when evaluating a language, and for good reason.

I personally lean toward addressing  _other issues_ that affect the readability or maintainability of code. For instance, type inference would be an obvious improvement even without changing the name of vector/matrix/array types. Compare:

```wgsl
var velocity : vec2<f32> = vec2<f32>(0.0, 0.0);
```

```wgsl
var velocity = vec2<f32>(0.0, 0.0);
```

It is my opinion that _just renaming the types_ does not move the needle forward:

```wgsl
var velocity : f32x4 = f32x4(0.0, 0.0);
```

While this line is shorter than the original, there is still unnecessary redundancy. Because of that, it is still longer than the line with type inference and the longer type name. It also appears (to me) that this is also harder to read and harder to maintain; changing the type still requires changing it in (at least) two places, and potentially in several other places throughout the code.

**Comment by kainino0x** [comment] 2021-02-23 06:55
I agree we might be able to solve this with other solutions aside from aliases/renames. Implicit types for vars/consts is one.

More we could pursue:
- "Infer" the type param of `vec4<T>` & co. `var velocity = vec2(0.0, 0.0);`. This should be very straightforward with #723.
- Add a highly-overloaded helper called `vec` which figures out the type via overload resolution. `var velocity = vec(0.0, 0.0);`. Cool but probably not very much benefit.

I personally agree with whoever said this in the meeting today: We should pursue other improvements before deciding that `vec4<f32>` is too onerous.

**Comment by juj** [comment] 2021-02-23 08:34
> On the subject of typing, programming is more about communicating ideas well than optimizing for fewer or easy-to-reach keystrokes. This is why code-golf is always a bad idea for production code. See also: https://blog.codinghorror.com/is-writing-more-important-than-programming/ Readability and writability of a language are in direct conflict with one another, and often subjective. Some people prefer to measure "maintainability" instead of "readability" when evaluating a language, and for good reason.

100% disagree with the contrast between readability and writability that is attempted to be made here. It is not necessarily at all the case that longer code is more readable, but those two can be very separate. If you take the example

```
var velocity : vec2<f32> = vec2<f32>(0.0, 0.0);
```
versus a
```
float2 velocity(0, 0);
```
the second is much more readable than the first, much faster to scan with human eyes, and much easier to type as well. The first one is filled with redundancies, and appears idiosyncratic to anyone who has prior rendering experience with WebGL or OpenGL, or JS/C/C++.

> Types with names like `float4` are not self-documenting. Rhetorically, how many bits does such a type require for storage?

Float4 is extremely self-documenting, I don't understand where this comes from? Float4 is "four floats". A massive improvement over `var velocity : vec2<f32>`, where
 - one first has an artificial word `var`, raising misdirecting questions/assumptions like
     - *is it like a JS var?*,
     - *what else can go there?*,
     - *could I also have `let velocity : vec2<f32>`?*,
     - *or `const velocity : vec2<f32>`?*
 - then it comes with `:`, an awkward token needed to satiate parsing rules of the language, which is a smell of a language parsing design failure,
 - then it comes with the type `vec2<f32>`: oh, now we see what it is, after one just took the time to read and parse `var x :`. It would have been more readable to just have `vec2<f32> = `, both shorter, and faster to read and mentally process. Identical information value carried.
 - then an assignment operator `=`: wholly unnecessary, but the easiest token here to parse, as it already maps to a well known construct from other languages, and not something alien,
 - then again a long `vec2<f32>`: redundant repetition necessitated due to language rules, a human reader does not need any of this information repeated to parse the proper intent of the line, it is just to satisfy parsing rules,
 - finally `(0.0, 0.0);`: a visually difficult combination of `.,` characters: in the absence of syntax highlighting or different numbers, recognizing it is not e.g. a `0,0, 0.0` or `0,0, 0,0` can be hard and make one squint, again slowing down readability. (note that human parsing e.g `(0.5, 0.9)` is much easier than repeated zeros, since the mind can make quick assumptions from particular sequences of numbers. Humans don't need zeros to be suffixed with a `.0` to understand it is a zero, so this is again a redundancy to satisfy language rules. The first mental mapping from `(0.0, 0.0)` will be that it is a `0,0, 0,0`, and it can actually rather be the whitespace, not the punctuation, that gives the reader the clue that it is two zeros, and not four.

I.e. fusing initialization as C++ ctor-like calls and implicit literal parsing of int vs float really bring readability. (A bit surprised these have not been discussed before in this context, when readability is being so vocally brought up?)

When did anyone ever see a serious conversation in C/C++/C#/Java/HLSL/any other language that has keyword `float` where developers would say the language is hard to use (or hard to get into) because it's unreadable since they can't know how many bits a `float` had? Never. People learn float and move on. WGSL could easily just tap on to that learned common knowledge.

It seems as if that kind of thinking is trying to cater to an imaginary set of developers that would either not be able to hold in their mind an association that a keyword "float" means a 32-bit single precision floating point, or this is their first ever programming language that they are learning all of this from scratch (it is not, nobody starts writing WGSL before knowing anything else).

Thinking that the reader must be mentally shielded from not needing to know `float` is 32-bits, or `float4` is four of such floats, and come up with `vec4<f32>` to fix it, the same kind of contrived reduce-to-absurdness issues still persist:
 - what is that 'f' there supposed to mean?
 - since it is a vec, can I push_back to it like std::vectors?
 - are these four-bit elements, or an array of 32 elements?

There will *always* be ways for someone to blindly misunderstand, and one cannot expect the basic primitive language syntax to teach the definitions of the primitives. If you try to apply such design, you'll end up with absurd `fixed_vector<length=4,floating-point,width=32bits>`. Now that's pretty self-explanatory at least! :)

If the root issue is that `float4` is no longer fancy since it's been done before, then at minimum, please go for
```
f2x32 velocity(0, 0);
```
or if improving readability with ctor-like initialization is not on the table, with
```
f2x32 velocity = f2x32(0, 0);
```
or if improving readability with literal type parsing is not on the table, with
```
f2x32 velocity = f2x32(0.0, 0.0);
```
Though I would argue both of the above readability improvements should be put on the table, if readability indeed is a primary point here(?)

To me
```
var velocity : vec2<f32> = vec2<f32>(0.0, 0.0);
```
reads like the syntax of that junior programmer who barely just got their first parser up, but then does not have any more stamina/capacity to further improve the ergonomics around the language, and moved on to working on some other thing.

**Comment by jdashg** [comment] 2021-02-23 08:49
Please let's be at least two of kind/true/necessary in our comments.

In my mind, type inference is a given at this point. We've explicitly made steps to make our expression result types unambiguous.
`var velocity : vec2<f32> = vec2<f32>(0.0, 0.0);`
`var velocity = vec2<f32>(0.0, 0.0);` (type inference)
`var velocity = fvec2(0.0, 0.0);` (consensus direction from today's meeting, to be drafted by Myles)
`var velocity = fvec2(0, 0);` (discussions elsewhere about special treatment for coersion of literals)

In C++ I would write `auto velocity = fvec2{0,0};` so I'm pretty happy with where we're headed.

**Comment by juj** [comment] 2021-02-23 10:06
> Please let's be at least two of kind/true/necessary in our comments.

Apologies, I did not at all mean any offense in my post.

> In my mind, type inference is a given at this point.

If that is already decided, it makes me happy!

> In C++ I would write `auto velocity = fvec2{0,0};`

Curious, why would you prefer that over `fvec2 velocity = {0,0};`? (or `fvec2 velocity(0,0);` depending on how the type had been implemented) In general I would use `auto` only when I don't want to spell out the type in code, but here you are already writing out the type, so it does not win that?

**Comment by parasyte** [comment] 2021-02-23 10:33
@juj Honestly I don't know where to begin to address this comment. It reads more like a proposal to throw out the existing variable declaration syntax than the original spirit of the ticket, which is basically just bikeshedding the name of the vector types. I'm not arguing for or against the existing syntax, but that's clearly a very large scope that completely changes the direction of this discussion.

**Comment by lain-dono** [comment] 2021-02-23 17:20
C-style is awful. Among other things, it makes parsing difficult. Please note that there are IDEs, analyzers, etc.

The only thing I agree with is the removal of `:`.

**Comment by dneto0** [comment] 2021-02-23 20:13
While we're in generative mode, here's more options:

7.   For vector types, `v`*N* *S*  where N is 2,3,4 and T is a scalar type.  So:    `v2f32` is `vec2<f32>`.  This  generalizes obviously and ties in with existing naming style.


8. Putting a number to what @kvark said:      i32x4   f32x2

9-ish.  GLSL also has [GL_EXT_shader_explicit_arithmetic_types.txt](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_shader_explicit_arithmetic_types.txt)
*  Among other things, adds a pattern that cleaves to GLSL heritage, e.g.    `f32vec3` for `vec3<f32>` and `f16vec2` for `vec2<f16>`

**Comment by dneto0** [comment] 2021-02-23 20:26
About 1: (This is mostly for colour.  I'll come back later with opinions).

I always found it amusing that C-heritage languages have the progression:  half, float, double.  This makes no sense to a newcomer.  Where is 'single'?  Oh, that's in another language  (Pascal, at least).

Floating point types are still a rich source of innovation.  In addition to float and double, LLVM has had forced upon it:  half, fp128, x86_fp80 ppc_fp128.
Now Microsoft has add MSFP12 and MSFP16 for small size shared-exponent processing for ML workloads.  See https://www.microsoft.com/en-us/research/blog/a-microsoft-custom-data-type-for-efficient-inference/ 

Also, 'float8' and 'float16' are 8-element f32 and 16-bit f32 (respectively) in certain  GPU languages.  (I stated this as part of my rationale for going with the easily-generalized pattern initially.)

**Comment by frzi** [comment] 2021-02-25 00:15
FWIW I think `f32x4`, `i32x4` and `boolx4` look the cleanest. The matrix types should undergo the same change then, which'll bring types like `f32x4x4` (or maybe `f32x44`?). All of which are shorter than `vecN<T>` or `matNxM<T>` and don't require the shift key.

**Comment by kainino0x** [comment] 2021-02-25 00:51
nit: f32xMxN is kind of unclear if it means (f32xM)xN or f32x(MxN) - it's the latter, because matrices are matWxH (COLSxROWS)

**Comment by kvark** [comment] 2021-02-25 16:21
Good point! In this sense, (7) is more robust. `v3f32` and `m23f32` are less ambiguous, since the order of major to minor goes left to right.

**Comment by dj2** [comment] 2021-02-25 16:23
`m23f32` just looks like someone mashed the keyboard. It's _very_ unreadable. The extra characters maybe slightly more typing but the make the code easier to read. Making identifiers more dense doesn't add much, at least to me.

**Comment by litherum** [comment] 2021-02-25 17:57
Other options are: don’t give this treatment to matrices at all, or only give this treatment to square matrices.

**Comment by kvark** [comment] 2021-02-25 18:13
@litherum is it an option for you to simply postpone this until we get the basic type inference? Maybe it will end up being a non-issue to specify the types without shortcuts, at all, after that.

**Comment by aloucks** [comment] 2021-02-25 20:05
@kvark makes a good point. Would the following work with type inference? Would this be acceptable?

```rust
fn double(v: vec3<f32>) -> vec3<f32> {
  return vec3(v.x * 2.0, v.y * 2.0, v.z * 2.0);
}

var x = double(vec3(1.0, 2.0, 3.0));
```

**Comment by kainino0x** [comment] 2021-02-25 21:52
That would work in the type inference I envision, yes. https://github.com/gpuweb/gpuweb/issues/736#issuecomment-783955277

**Comment by vorg** [comment] 2021-08-06 23:05
I was all for `vec3<f32>` until i started writing real world code. I looks like WGSL code below is mostly `vec3<f32>` with few numbers sprinkled between :) I would rather avoid type aliases to keep the language small and i think lack of automatic casting is bigger issue here. 

```c
// https://www.shadertoy.com/view/MsS3Wc
// via: https://thebookofshaders.com/06/
float4 hsb2rgb(float3 c) {
  float3 rgb = clamp(abs(((c.x * 6.0 + float3(0.0, 4.0, 2.0)) % 6.0) - 3.0) - 1.0, 0.0, 1.0);
  rgb = rgb * rgb * (3.0 - 2.0 * rgb);
  float3 o = c.z * lerp(float3(1.0, 1.0, 1.0), rgb, c.y);
  return float4(o.r, o.g, o.b, 1);
}
```
    
```rs
fn hsb2rgb(c: vec3<f32>) -> vec4<f32> {
  var rgb: vec3<f32> = abs(((c.x * 6.0 + vec3<f32>(0.0, 4.0, 2.0)) % vec3<f32>(6.0)) - 3.0) - 1.0;
  rgb = clamp(rgb, vec3<f32>(0.0), vec3<f32>(1.0));
  rgb = rgb * rgb * (3.0 - 2.0 * rgb);      
  var o: vec3<f32> = c.z * mix(vec3<f32>(1.0, 1.0, 1.0), rgb, vec3<f32>(c.y));
  return vec4<f32>(o.r, o.g, o.b, 1.0);
}
```

I hope in the future we could write `clamp(rgb, 0.0, 1.0);` instead of `clamp(rgb, vec3<f32>(0.0), vec3<f32>(1.0));`;

**Comment by kvark** [comment] 2021-08-07 02:39
> I looks like WGSL code below is mostly vec3<f32> with few numbers sprinkled between :)

1. You don't have to specify the type for variables that are initialized, i.e. you can do `var o = ...;`
2. You can do `type float3 = vec3<f32>;` once and roll with `float3` type without any language additions

**Comment by munrocket** [comment] 2021-10-15 12:00
Reserved word, `vec4f` suggested by @morganbarrett looking good.

**Comment by munrocket** [comment] 2021-10-15 15:45
7. What [OpenCV has](https://docs.opencv.org/4.5.3/dc/d84/group__core__basic.html): `{vec,mat}{2,3,4}{f,d,b,i}`

**Comment by davidar** [comment] 2022-04-06 00:47
> 2. You can do `type float3 = vec3<f32>;` once and roll with `float3` type without any language additions

The spec currently lists `float3` et al as [reserved words](https://www.w3.org/TR/WGSL/#reserved-words), though none of the parsers I've used seem to be enforcing this at the moment. Does that mean there's a risk these type aliases will break at some point?

**Comment by kdashg** [comment] 2022-04-06 17:41
As reserved words, yes, `type float3 = vec3<f32>;` is therefore invalid wgsl and will stop working when parsers update.

**Comment by kdashg** [comment] 2022-04-06 17:43
We should probably de-reserve these, and it sounds like we have consensus for removing these type names from reserved words.

**Comment by kdashg** [comment] 2022-05-13 20:18
We do still reserve e.g. fvec3, I see.

**Comment by kdashg** [comment] 2022-05-31 06:44
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-24-minutes#vec4ltf32-is-too-hard-to-type-on-the-keyboard--issue-736">WGSL meeting minutes 2022-05-24</a></summary>



* MM: Still feel is valuable and don’t want to close. Internal discussion and we think that vec4&lt;f32> is too hard to type. Last time made a compromise proposal to add short names to some of the types but not others. Would still be acceptable but feel now if that’s actually a compromise or just a better solution. So, if the group thinks it’s reasonable to name sone and not others that’s fine. But leaning towards naming all of them and we like uniformity.
* BC: Since originally filed we have literal unification adn type inference for vec constructors so the only place to type vec4&lt;f32> is on a member of a struct or as a parameter. Every other place can be informed
* MM: Or local var?
* BC: No, can do `let a = vec4(1., 2, 3, 4)`
* MM: That has vec4
* KG: No &lt;>’s
* MM: Oh, hte f32 is inferred
* AB: vec3(1.0,2,3)    gives you a vec3&lt;f32>(1.0f, 2.0f, 3.0f)
* KG: Above gives float definition?
* AB: Yea, can’t convert a float into an integer so it prefers float
* BC: Only time need to type brackets in two places, so we feel it’s unnecessary.
* MM: Little scared of line of code. Function param isn’t written same way. Function param and local variable to be spelt the same way have the long way. Either have different or have the same but names are long.
* KG: Always felt we should have basic fvec, ivec, bvec and not go two wild about having all of them. Think it’s fine for gradual complexity if you want more complicated things. Feel wanting to name things vec4f is common enough that it would be nice if you coudl do it as a shorthand. Happy to say we do for a few things but not all.
* MM: Would be fine with that too. Have no opinions on names. Just don't’ want &lt;>’s in names
* DN: When you say all of them, not clear on what that is. Would like to know what that means exactly. F16 on horizon, could have i16.
* MM: So, all of them would be cartesian product of float, half, int, uint with 2, 3, 4. If group prefers some subset would be ok.
* AB: Intentionally leaving out boolean?
* MM: Boolean too.
* BC: Vocal against typedefs but lost battle on suffexts. Have alphabet soup with ‘h’ suffix. Talked about holding back. Have ‘i’, ‘u’ , ‘f’, ‘h’. If doing should make consistent so if adding would be vec3f, vec3h. Would be unfortunate if we didnt’ do all
* MM: Sounds alright
* KG: If we do this, don’t have to do this for all things in the future. Might not add the ease of use alias.
* DS: Couldn’t these be type aliases
* KG: Would have to do that in all programs. Do you want standard shorthand?
* MM: Important that code snippets that we all agree on how these things are named. Think HLSL is good example where they have both names but shorter ones are common
* BC: Assume not keen on extension in order ot not pollute namespace unless opt-in
* KG: This is a value add.
* MM: Because we reserve float4, agree with KG that this is the same pollution problem 
* DN: Stopped reserving words that are types in other shader languages
* KG: But we did it for weeks
* DN: We did but decided not to as it becomes impossible to do aliases. Doesn’t change direction
* MM: Point still stands. Also every other shading language has short / consiste global namespace names.
* KG: So, go back to making PR to add and just pick one?
* DN: **Would like a week to discuss internally**.
* KG: Ok.
* MM: One of the interesting questions to discuss is would you prefer to have the common names named or all of them named. 
    * Any names
    * All the names
    * Common names
* MM: And could define what common means

</details>

**Comment by kdashg** [comment] 2022-05-31 19:11
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-31-minutes#vec4ltf32-is-too-hard-to-type-on-the-keyboard--issue-736">WGSL meeting minutes 2022-05-31</a></summary>



* Previously
    * DN: Would like a week to discuss internally.
* DN: Said we’d talk internally, none of us particularly happy with this. Don’t think great to have same way to write same thing. See strong desire to add this. Don’t want there to be a generic rush to add for every scalar types (i.e. i8). Do see utility in matching to suffixes in language so far. Don’t want to add more suffixes. What we have seen is vec4f, vec4u, vec4i in game engines. If we get these, think it should be spelt that way. So, under process but in spirit of agreement think that spelling would be livable.
* MM: Sounds great. Right now, listed 3 of 4, what about ‘h’, does it extend to h?
* DN: Yes.
* MM: Happy to agree with that.
* KG: Cool. Names?
* MM: Ones he said are fine?
* DN:**vec3i, vec3u, vec3f, vec3h**
* KG: **Let it be so**.
* MM: **Not vec1f** right, just vec2f, vec3, vec4f
* DN: Correct.
* KG :Matrices?
* MM: **Not worried about matrices**.


</details>

**Comment by kainino0x** [comment] 2022-05-31 21:59
Not to throw a wrench in things, but for `double`, that's going to come out as `vec3d`, which is confusing (looks like "3D"). Why not `{f,u,i,h}vec{2,3,4}` as in the GLSL `ivec3`?

**Comment by ben-clayton** [comment] 2022-05-31 22:52
> Not to throw a wrench in things, but for `double`, that's going to come out as `vec3d`, which is confusing (looks like "3D"). Why not `{f,u,i,h}vec{2,3,4}` as in the GLSL `ivec3`?

(a) This keeps the use of `{f,u,i,h}` as a suffix for both literals and the vector type. This enforces self-consistency in the language.
(b) There's already a discrepancy with WGSL's `f`-suffix for `f32` literals and GLSL's no-prefix for a vector of float32, so looking almost-like GLSL is probably worse than looking entirely different.
(c) `vec{2,3,4}{f,u,i,h}` has a number to separate the alpha suffix from the alpha run of `vec`.
(d) We have no extension for 64-bit float types. The group have expressed no desire to add any additional literal suffixes, nor type alias suffixes, so there is no plan for `vec3d`.
(e) `vec3f`, `vec4i`, etc is exceptionally common in the games industry as C++ vector types.

**Comment by litherum** [comment] 2022-06-01 00:18
We would be A-OK with not adding a suffix (in either type aliases or literals) for doubles. We don't even support them in the first place.

**Comment by kainino0x** [comment] 2022-06-01 03:51
OK with me then.

**Comment by dj2** [comment] 2022-08-08 13:40
Given that we've added the `vec3(1, 1, 1)` form which will become a `vec3f(1., 1., 1.)` if used in a float32 context, why do we still need these aliases? They seem like they're just adding more things to confuse users as we now have 3 different ways to declare a float vector.

This seems like it's been outdated by other changes to the languages.

**Closed** 2022-11-28 18:16 UTC
Labels: wgsl, editorial

**Comment by greggman** [comment] 2022-12-14 20:36
so I see `vec4f` etc and `mat4x4f` have been added, what about `texture_2df` for consistency?

**Comment by kdashg** [comment] 2022-12-14 20:54
Personally I feel like doing so for textures is unnecessary. I feel like there is an order of magnitude less of them than vecs or mats, and I'm comfortable drawing the line there in terms of what we provide by default.
