### ISSUE TITLE
[wgsl] Define what bijective to SPIR-V means

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#582] opened 2020-02-29 13:32 UTC
We need to come up with a definition and guidelines as to what we mean when we say WGSL is bijective to SPIR-V. This would the help guide the language evolution.

**Comment by tangmi** [comment] 2020-03-01 20:27
I agree this is important to help understand the purpose of WGSL. I believe this will affect most syntax-related issues, like #577, #579, #580, #581

Here's a couple options I can think of:

- WGSL is intended to be more or less a textual representation of SPIR-V (where `fn convert(wgsl) -> spirv;` is a bijective function).
  - Syntax sugar in WGSL may have a hard time existing, because SPIR-V doesn't have syntax sugar.
  - Without syntax sugar, WGSL _may_ be a more difficult language to hand-write (however, shadering languages, out of all types of programming, seem the most straightforward to write "machine" code for).
  - WGSL could be a target of even higher level languages (via SPIR-V), with its direct usage more limited to ad-hoc shader authoring.
- Syntax sugar exists, the bijection is only defined after the WGSL is desugared.
  - This could create a disconnect between the parts of the language designed for machine use vs human use.
  - There could be some opportunity to pattern match in the `spirv -> wgsl` case to "re-sugar" the source
    - This could cause problems in ambiguous cases, like the `unless` keyword.
- WGSL is made easier to write (i.e. make "sugar" part of the language, like replacing `break if`/`continuing` with a `for` loop)
  - We would have to take care ensuring that every bit of "high-level" or "sugar"ed syntax maps losslessly(?) to and from SPIR-V.

Here are my assumptions that drive this reasoning:
- The point of WGSL is not just to have another target for shader compilation, but to e.g. allow one to write an HTML page with WebGPU/WGSL content without being required to use offline tooling to process their source.
- WGSL maps to some subset of SPIR-V and that mapping is (i.e. should be) reversible. But, not all SPIR-V maps losslessly to WGSL? It seems once SPIR-V has run through SPIRV-Tools its e.g. `OpMemoryModel` is no longer compatible with WGSL?

**Comment by magcius** [comment] 2020-03-01 21:02
I think the reasonable expectation here is that for any SPIR-V, the transformation SPIR-V -> WGSL -> SPIR-V is lossless (meaning byte-for-byte identical).

This does not imply that WGSL -> SPIR-V -> WGSL is not guaranteed to be lossless, implying WGSL can be a superset of SPIR-V.

**Comment by othermaciej** [comment] 2020-03-01 22:14
I think the requirement should only be that there exists a SPIR-V -> WGSL -> SPIR-V transform that is semantically equivalent, but not necessarily byte-for-byte identical. Or if that's not sufficient, someone should motivate why it isn't.

I'm lost in the double negatives, but I think the above comment suggests that there need not exist a WGSL -> SPIR-V -> WGSL transform that is byte-for-byte identical. I agree that we don't need that.

**Comment by magcius** [comment] 2020-03-01 22:36
Oops, I had an extra negation in my wording. Fixed now.

> Or if that's not sufficient, someone should motivate why it isn't.

Obviously, there are tradeoffs to be made. But I can offer several arguments for:

1. The most obvious is that from a spec writing standpoint, how do you define "semantically equivalent"? WGSL is designed to use SPIR-V's semantics to save time, and so we'd have to define why two things are semantically equivalent.

2. For developers expecting to go SPIRV -> WGSL, on platforms that would prefer to do a transform from WGSL -> SPIRV, this aides debugging. You are guaranteed to get exactly what you put in. Debugging of graphics APIs is already a large time-sink, and with multiple transforms in between you and renderdoc, it can be finnicky to understand if the shader you're debugging is correct. This is already a major hazard with WebGL, and I would like to reduce it. I guarantee you, there will be bugs in browsers, and in WGSL implementations, and anything we can do to lessen that impact, the better.

3. Reduces the possible impact of driver bugs & optimizations. Drivers definitely optimize and pattern-match for current SPIR-V toolchains. Again, on platforms that go SPIRV -> WGSL -> SPIRV, this ensures that the driver sees exactly what the toolchain output. While drivers should be fixed and improved, we can also choose to eliminate this hazard.

And several against:

1. It can introduce several awkward syntax elements for things that seem unnecessary or silly, like the "regardless" block, which are basically artifacts of the structured flow control system.

2. It constrains language design by needing to be a compile target, as well as a high-level shading language.

(These are obviously not exhaustive, just ones I can think of)

**Comment by othermaciej** [comment] 2020-03-01 22:50
> 2. For developers expecting to go SPIRV -> WGSL, on platforms that would prefer to do a transform from WGSL -> SPIRV, this aides debugging. You are guaranteed to get exactly what you put in. Debugging of graphics APIs is already a large time-sink, and with multiple transforms in between you and renderdoc, it can be finnicky to understand if the shader you're debugging is correct. This is already a major hazard with WebGL, and I would like to reduce it. I guarantee you, there will be bugs in browsers, and in WGSL implementations, and anything we can do to lessen that impact, the better.

Why is this essential for SPIR-V, but irrelevant for Metal, HSLS, DXIL, or anything else that could be a platform shader format? On the two most popular desktop platforms and one of the two most popular mobile platforms, SPIR-V is not what will get sent to the driver. Is this debugging aid much more important on Linux and Android? 

> 3. Reduces the possible impact of driver bugs & optimizations. Drivers definitely optimize and pattern-match for current SPIR-V toolchains. Again, on platforms that go SPIRV -> WGSL -> SPIRV, this ensures that the driver sees exactly what the toolchain output. While drivers should be fixed and improved, we can also choose to eliminate this hazard.

Again, why is this important only on the platforms where the graphics system accepts SPIR-V? Are Vulkan drivers expected to be more buggy than Metal or DirectX ones?

**Comment by mehmetoguzderin** [comment] 2020-03-01 22:51
Does the group have to go forward with a term choice that's as mathematically strong as bijectivity? Is there even a transpile-able language that's genuinely bijective while staying on the lines of being pleasant? Wouldn't a looser coupling such as "trivially convertible to and from SPIR-V by x, y, ... and ..." work more truthful to the nature of the effort?

**Comment by litherum** [comment] 2020-03-02 00:16
Interesting questions:

Is it okay for a SPIR-V -> WGSL compiler to be required to insert additional variables which were not present in the source language? How about inserting additional functions? How about reordering independent loads/stores?

**Comment by othermaciej** [comment] 2020-03-02 00:48
Perhaps overly fussy technicality: the property desired here is not a requirement on compilers, but a property on the spec that compilers meeting certain properties are possible. And that in particular, it's possible to make a pair.

So in that light, the question is whether it's ok if there are SPIR-V constructs where translation to WGSL would inevitably need to insert extra variables or functions, or perform reordering, or what have you.

It seems clearly ok as long as it's possible to write a compiler in the other direction that reverses the transformation. But this leaves some open questions:
- Must the result of reversing the transformation be byte-for-byte identical? Or is there some looser constraint on what it must produce? (With formal definitions of semantics, like denotational semantics, it's possible to formally define "semantically equivalent" and write proofs about it, but SPIR-V isn't defined to that level of rigor.)
- If two SPIR-V programs are functionally identical but differ in some irrelevant way (order of constant declaration for example, or presence of a superfluous variable), must the round-trip mapping leave them distinct?

**Comment by litherum** [comment] 2020-03-02 21:39
One extreme is that the SPIR-V -> WGSL -> SPIR-V round-trip can be byte-for-byte identical. The current WGSL spec already does not satisfy this. I agree with comments made above that we should not even pursue this.

The other extreme is that only the behavior is identical, and performance / similarity to the original source is irrelevant. I'd actually prefer this, but I'm willing to compromise in order to make forward progress.

So, how do we (the CG) pick a happy medium? What strategy should we use when picking? What is our philosophy? How do we know if it's okay for the round trip to require introducing an additional construct A but not an additional construct B?

Echoing my [other comment](https://github.com/gpuweb/gpuweb/issues/580#issuecomment-593632000): I think we should be data-driven, and make our decisions here based on facts, rather than opinions. We need to come up a way to judge whether or not constructs A and B affect users. We need to be more rigorous than "let's just as some people what they think."

**Comment by dneto0** [comment] 2020-03-03 18:51
Thanks everyone for the good discussion on this.  

I should explain where I'm coming from:

The reason people use GPUs is to make certain programs faster and to access certain hardware (e.g. a framebuffer/surface).  When it comes down to it, performance is essentially a function of:

*  ALU operations, 
* memory operations, and
* achievable parallelism.   Because of the way operations are scheduled between cooperating threads/invocations, a good proxy for this often the size of thread-private registers. (function and private variables)

Everything else is orchestration of the above.  To achieve high performance, developers have to achieve a balance of the three metrics.  (E.g. see "roofline analysis" for balancing arithmetic and memory bandwidth, or NVIDIA has a big guide on analyzing and getting to peak performance which goes into quite a bit of deatil. https://devblogs.nvidia.com/the-peak-performance-analysis-method-for-optimizing-any-gpu-workload/)

The three metrics above are kind of fuzzy.  But GPU programmers care about them, some GPU programmers care desperately about them.  They tune their shaders to balance one way or another, with massive effect. (Some call it "getting the last 5x of performance"). 

The medium in which they tune is the shader/kernel language, changing the shape, scheduling, interfacing, etc.    Talk to a performance-tuning graphics developer and they will express deep frustration in how all the layers below them (toward the GPU) are fickle, and the more complex those layers are, the more frustrating it is to them.  

One of the things devs wanted from SPIR-V was to have more control in their own hands, to achieve a lower level or better control over the expression of their algorithm.  They get far enough to express a particular orchestration (algorithm) in SPIR-V, and then cross their fingers that it survives down toward the GPU.

Now, we have three fuzzy metrics and very fickle tooling.   I think its our (my) responsibility to preserve their expressed program intent as far as possible.  *The concept of "bijectivity" tries to make those 3 fuzzy metrics crisp by taking it even further.* Yes, there are lots of things that we can agree are immaterial.   @othermaciej and @litherum both alluded to a good starting set.

I think there is a reasonable function canonicalization function Canon mapping SPIR-V to SPIR-V which strips away the unimportant aspects, and then we can have:

```
  A = SPIR-V   -->  WGSL --> B = SPIR-V
```

Then Canon(A) = Canon(B)

I'm also willing to back off on perfect quality, and instead allow a fuzzy-compare provided that fuzzy-compare is truly immaterial.

**Comment by dneto0** [comment] 2020-03-03 18:52
Addressing some earlier points:

*  SPIR-V  -->  WGSL --> SPIR-V is the more important one to me
*  Therefore yes, language features used in the other round trip ( WGSL -> SPIR-V -> WGSL )  is essentially sugar.

**Comment by grorg** [comment] 2020-03-03 20:06
Discussed at the [2020-03-03 teleconference](https://docs.google.com/document/d/15Pi1fYzr5F-aP92mosOLtRL4qLczmVRWQaomfQmGNzo).

Resolution was that @litherum will make a pull request that addresses the discussion at the meeting and on this issue.

**Comment by othermaciej** [comment] 2020-03-03 22:52
A bit of math nerdery for anyone writing a PR to address this issue: bijective is the wrong mathematical term to use here, even setting aside fuzziness. A bijection is a mapping that's one-to-one and onto, or equivalently, one-to-one in both directions. But we agree that WGSL may have syntactic sugar that causes different WGSL programs to map to the same SPIR-V. So the SPIR-V to WGSL mapping is not onto, it's only one-to-one. Let's say "one to one mapping from SPIR-V to WGSL" if we want to use math jargon. Or something like "approximately one to one mapping from SPIR-V to WGSL", since we agree some irrelevant differences may not need to be preserved.

(Also, shouldn't the PR land before the issue is closed? Closing the issue first seems likely to lose track of agreed changes, as recently happened with the context name.)

**Comment by Kangz** [comment] 2020-03-04 10:06
It's pretty clear that we are talking about a bijection in the quotient set of `SPIR-V / is-similar-up-to-irrelevant-differences`, not SPIR-V itself.

**Comment by kvark** [comment] 2020-03-04 15:18
I agree that closing this is a little premature if there is a PR expected.

**Comment by dneto0** [comment] 2020-03-06 00:18
I agree with @othermaciej in general about the use of "bijectivity" vs. 1-to-1 and onto.  

I started the various conversations using the "bijective" term, including my own starting position of "no sugar in WGSL".  But with discussion on this issue and in the most recent meeting it's evolved to what @Kangz said.  And of course the "similar up to irrelevant differences" is to-be-defined, and that's on me.

**Comment by othermaciej** [comment] 2020-03-06 01:39
@Kangz even so I think we're talking about a one-to-one mapping from that quotient set to WGSL, not a bijection (which would be one-to-one and onto).

**Comment by pjoe** [comment] 2020-03-06 07:02
Just a suggestion: maybe try to get some input from @hanskristian-work from https://github.com/KhronosGroup/SPIRV-Cross on the whole SPIR-V <> WGSL thing.

**Comment by HansKristian-Work** [comment] 2020-03-06 09:27
Well since I was pinged ... Would be good to know what the strategy is going to be for using WGSL from a developer point of view. If WGSL is targeting a 1:1 mapping with SPIR-V, will this live in SPIRV-Tools as a slightly more sugary version of SPIR-V assembly?

**Comment by dj2** [comment] 2020-03-06 14:20
WGSL won't be a 1:1 mapping with SPIR-V. The SPIR-V accepted by WebGPU is already a constrained set of SPIR-V.

**Comment by tangmi** [comment] 2020-03-10 01:14
Is WGSL intended to be a compilation target or a hand-writable language?

If the former, then one could argue a lot of the discussion around the specific syntax doesn't matter. If it's the latter, I could argue that the WGSL -> SPIR-V path is the critical path (and the intention is for devs to port their shaders to WGSL).

If it's a little bit of both (which I suspect it is!), it's probably very important to specify how much of each (conflicting) goal WGSL intends to support. (The [current goals](https://github.com/gpuweb/gpuweb/blob/8377eff9595cbd888996b80727d62a1199254948/wgsl/index.bs#L41-L47) in the bikeshed seem to imply more of a "compilation target" language.)

**Comment by litherum** [comment] 2020-03-10 01:41
> Is WGSL intended to be a compilation target or a hand-writable language?

It's both.

**Comment by othermaciej** [comment] 2020-03-10 01:46
>  If it's the latter, I could argue that the WGSL -> SPIR-V path is the critical path (and the intention is for devs to port their shaders to WGSL).

WGSL -> MSL and WGSL -> HLSL (and/or DXIL) are also critical paths. WebGPU must be implementable and efficient on non-Vulcan targets.

**Comment by litherum** [comment] 2020-03-10 02:23
I just made a [pull request](https://github.com/gpuweb/gpuweb/pull/599) with what I believe is the result of this conversation. Feedback is welcome.

**Comment by kdashg** [comment] 2022-01-24 23:46
We have sort of moved away from this, haven't we?
@dneto0 ?

**Closed** 2022-02-08 20:51 UTC
Labels: wgsl
