### ISSUE TITLE
shaders: floating point widths other than 32 bits

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#272] opened 2019-04-17 17:52 UTC
For MVP we decided to only have 32-bit floating point.  See #230 
Revisit post-MVP, considering 16-bit and 64-bit floating point.

**Comment by litherum** [comment] 2020-05-13 21:07
Duplicate of https://github.com/gpuweb/gpuweb/issues/658

**Closed by litherum** 2020-05-13 21:07 UTC
Labels: programming model
