### ISSUE TITLE
Is it intended that keywords can not be identifiers?

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#3692] opened 2022-12-15 01:38 UTC
WGSL seems to take much of its inspriation from rust

all of these work in Rust but not in WGSL.

```
fn foo(i32: i32) -> i32 { return i32 * 12; }
```

```
struct Foo {
   i32: i32,
};
...
   f: Foo;
   f.i32 = 123;
```

```
let i32: i32 = 123;
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fec10a512eda60ae93b7d4df18792c2c

**Comment by dneto0** [comment] 2022-12-15 23:35
There is already consensus that predeclared type names (like i32) should not be keywords.
But spec is not yet updated:  #3277 and #3280

(And keep in mind that Tint tends to only implement something when it's spec'd.)

(Regarding "inspiration"  a lot of folks seem to think it's from Rust, but not really.  Rust and WGSL both draw from a lot of common practice in the last 20-30 years.  )

**Comment by dneto0** [comment] 2022-12-16 16:14
This is a good case though: where a formal parameter name shadows the return type.
```fn foo(i32: i32) -> i32 { return i32 * 12; }```

Currently the spec says 

>The identifier is [in scope](https://gpuweb.github.io/gpuweb/wgsl/#in-scope) until the end of the function.

That should be changed to say it's in scope for the entire body of the function.

**Comment by dneto0** [comment] 2023-02-24 17:17
The last one should be 'const' instead of 'let'.

```
const i32: i32 = 123;
```

**Comment by dneto0** [comment] 2023-02-24 17:25
Huh.

```
fn foo() { 
  const i32: i32 = 123;
}
```
This is fine.  Inside a function, the declaration is in scope immediately after the declaration.

However, consider:
```
const i32: i32 = 123;
```
A declaration at module scope is in scope for the entire source.  That's by design, to allow for order-independent declarations at module scope.
And therefore the second "i32" is in scope of the declaration, and you end up with a dependency loop from a declaration to itself.
So that's actually banned by the spec.

Tint errors out:

```
$ tint x.wgsl
x.wgsl:1:7 error: cyclic dependency found: 'i32' -> 'i32'
const i32: i32 = 123;
      ^^^

x.wgsl:1:12 note: const 'i32' references const 'i32' here
const i32: i32 = 123;
           ^^^

```

So that's works-as intended.

Additionally, this works just fine:
```
const i32: f32 = 123;
```

So I think everything is sorted.  Closing.

**Closed by dneto0** 2023-02-24 17:25 UTC
Labels: wgsl
