### ISSUE TITLE
Build: tree sitter still flaking sometimes

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4274] opened 2023-08-18 21:03 UTC
@mehmetoguzderin's changes to the GitHub Actions mostly fixed this (it used to flake on like 50% of builds) but apparently it's still there:
https://github.com/gpuweb/gpuweb/actions/runs/5905634973/job/16020116196?pr=4271

```
Traceback (most recent call last):
  File "/github/workspace/wgsl/wgsl_unit_tests.py", line 150, in <module>
    sys.exit(main())
             ^^^^^^
  File "/github/workspace/wgsl/wgsl_unit_tests.py", line 144, in main
    if not run_tests(options):
           ^^^^^^^^^^^^^^^^^^
  File "/github/workspace/wgsl/wgsl_unit_tests.py", line 106, in run_tests
    language = Language(options.shared_lib, "wgsl")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tree_sitter/__init__.py", line 83, in __init__
    language_function = getattr(self.lib, "tree_sitter_%s" % name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: grammar/build/wgsl.so: undefined symbol: tree_sitter_wgsl
```

**Comment by mehmetoguzderin** [comment] 2023-08-18 21:06
@kainino0x Indeed I'm on this, planning to focus on it soon. Thank you very much for the reference to this specific run! Until then, rerunning should green the PR

**Comment by kainino0x** [comment] 2023-08-18 22:46
Thanks!

**Comment by mehmetoguzderin** [comment] 2023-08-31 13:02
In reproduction environment, I was able to stop occurence of this issue by tentatively disabling parallel execution of WGSL's makefile.

https://github.com/gpuweb/gpuweb/pull/4276

Next step is making sure we can enable parallel make for WGSL again and reproduce the error more deterministically

**Comment by mehmetoguzderin** [comment] 2023-09-06 11:45
Same issue resurfaces: https://github.com/gpuweb/gpuweb/actions/runs/6089679344/job/16522995583?pr=4279

**Comment by mehmetoguzderin** [comment] 2023-09-26 16:15
PR https://github.com/gpuweb/gpuweb/pull/4303 presents significant progress in triangulating a few classes of fail sources due to grammar CI. I'm not closing the issue immediately, but if we don't face the same issues again on PRs with latest main based (so that they have changes) for maybe 3-4 weeks, then we can act to consider as resolves as long as Actions environment don't change drastically to introduce a new error

**Comment by mehmetoguzderin** [comment] 2023-10-04 09:01
Since all workflows seem to go without any negative influence in Actions for a short while now, I'm closing the issue. Thank you very much @kainino0x and everybody during this process for your patience!

**Closed by mehmetoguzderin** 2023-10-04 09:01 UTC
Labels: editorial
