### ISSUE TITLE
`textureSampleLevel` arguably doesn't work on Intel Mac in compute shaders

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4818] opened 2024-08-16 19:43 UTC
So...... I am finding that `textureSampleLevel` doesn't really work on Intel Mac in compute shaders

If I make a texture with 2 mip levels with the larger mip level (0,0,0,0) and the smaller mipLevel (1,1,1,1) and I sample between them using `textureSampleLevel(texture, sampler, coord, level)` for various values of the level parameter, a *normal* gpu would effectively return the same value as the level parameter.  Pass in 0.5 for mip Level, get back mix(black, white, 0.5) = 0.5 etc... a linear interpolation.

So for example, M1 Mac

```
mipLevel  result
--------  --------
0         0       
0.0625    0.0625  
0.125     0.125   
0.1875    0.1875  
0.25      0.25    
0.3125    0.3125  
0.375     0.375   
0.4375    0.4375  
0.5       0.5     
0.5625    0.5625  
0.625     0.625   
0.6875    0.6875  
0.75      0.75    
0.8125    0.8125  
0.875     0.875   
0.9375    0.9375  
1         1       
```

But this is intel Mac

```
mipLevel  result(intel)
--------  --------
0         0   
0.0625    0   
0.125     0   
0.1875    0   
0.25      0   
0.3125    0   
0.375     0   
0.4375    0.25
0.5       0.5 
0.5625    0.75
0.625     1   
0.6875    1   
0.75      1   
0.8125    1   
0.875     1   
0.9375    1   
1         1 
```

note: this is only in compute shaders. In fragment and vertex shaders I get more normal values. 

What to do?

* nothing. maybe this is expected/ok?
* document `textureSampleLevel` has these large differences in implementations (currently it says linear interpolation but these devices are not doing linear interpolation)
* make `textureSampleLevel`'s level parameter an integer? (kind of late for that)
* `round` the level parameter to integers?
* `round` the level parameter to multiples of 0.5?
* don't support Intel GPUs on Mac?
* rename `'linear'` in [`GPUMipmapFilterMode`](https://gpuweb.github.io/gpuweb/#enumdef-gpumipmapfiltermode) to `'linear-like-maybe'` and deprecate `'linear'`
* other...?

Note that AMD Mac also has quirks here. Its mip level filtering is also non-linear.

```
 mipLevel     result(AMD)
 --------    ----------
 0             0
 0.0625        0
 0.125         0.03125
 0.1875        0.109375
 0.25          0.1875
 0.3125        0.265625
 0.375         0.34375
 0.4375        0.421875
 0.5           0.5
 0.5625        0.578125
 0.625         0.65625
 0.6875        0.734375
 0.75          0.8125
 0.8125        0.890625
 0.875         0.96875
 0.9375        1
 1             1
```

Both Chrome and Firefox see these results for AMD but Safari sees the more standard results. It's not clear what Safari is doing differently.

Just for clarity: What **"linear"** filtering looks like

![image](https://github.com/user-attachments/assets/720379f5-33c8-4fc3-8f81-5c5ed376cdf5)

Here's AMD Mac

![image](https://github.com/user-attachments/assets/632cf4e8-a649-4da6-9938-29193d129e64)

And here's Intel Mac

![image](https://github.com/user-attachments/assets/d4ed85a0-7432-4e66-a811-aff838f2fb39)

Note: I'm on a MacBook Pro 16-inch 2019 with Intel UHD Graphics 630

Here's a test: https://jsgist.org/?src=bcd9d93aa4e4d12f7b2a98551ec6d8b1

**Comment by Kangz** [comment] 2024-08-19 13:47
Looking at various specs, it seems that precision should be:

For Vulkan 4 bits of values:

> `mipmapPrecisionBits` is the number of bits of division that the LOD calculation for mipmap fetching get snapped to when determining the contribution from each mip level to the mip filtered results. 2mipmapPrecisionBits is the actual number of divisions.

For D3D 8 bits of values (from [7.18.10 Mipmap Selection](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#7.18.8%20Linear%20Sample%20Addressing:~:text=more%20behavioral%20effect.-,7.18.10%20Mipmap%20Selection,-Suppose%20the%20task))

> First, the LOD is converted to at least [8](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#D3D11_MIP_LOD_RANGE_BIT_COUNT).[8](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#D3D11_MIP_LOD_FRACTIONAL_BIT_COUNT) fixed point (if not already in fixed point form). Call this fxpLOD.

I couldn't find any details for Metal.

Overall this looks like drivers are doing an optimizations that might not be spec-compliant but also might not matter visually in games: when the LOD is close to an exact level it is snapped to it such that there is less memory traffic. This could be useful when mapping a texture to another with almost perfect coordinate computation (but not exact due to precision issues) so that this case samples a single level and not two. Or it can be done WAY more aggressively like on your Mac Intel system.

IMHO we can treat this as drivers being bad in compute shaders and out of spec and still ship WebGPU on them (but still shame them about it!)

**Comment by greggman** [comment] 2024-08-19 22:40
> IMHO we can treat this as drivers being bad in compute shaders and out of spec and still ship WebGPU on them (but still shame them about it!)

I feel like this might so far off as to not be entirely ignorable. If I made a photo editing program and expected linear filtering and got what Intel is returning, effectively my app doesn't work. But, I get no indication from this API of that. Maybe I'm doing a blur by generating the next smaller mip level and letting you mix by doing `textureSampleLevel(t, s, uv, mixLevel)`. It appears to work on my local device but on the user's device it effectively doesn't function.

One way is deal with it is to just mention it in the spec. Another though, would be to deprecate `linear` in `GPUMipmapFilterMode`, and change it to something else so you know you're not getting linear filtering. Deprecation wouldn't break old code, you just get this annoying warning until you acknowledged that you can't count on linear filtering by changing from `mipmapFilter: 'linear'` to `mipmapFilter: 'implementation-defined-mix'` (or whatever word to use there).

I've used mip level mixing for simulations. The simulation gets the average value from an area by user settable radius but instead of sampling the entire area I sample the mips which effectively increases the area without having to do extra sampling. It's not perfect but the Intel results here are way out of line with what's expected and would clearly influence the simulation.

**Comment by mwyrzykowski** [comment] 2024-08-20 04:00
Do we know if this issue reproduces on all Intel Mac drivers or is it limited to the UHD Graphics 630? I do know Chrome ships quite a few versions back on macOS so the 630 is probably still quite prevalent, but just trying to understand what percentage of devices we are trying to work around.

**Comment by Kangz** [comment] 2024-08-20 11:47
What about working around it in implementations by emulating the filtering between mip levels manually in compute shaders on these bad drivers?

**Comment by mwyrzykowski** [comment] 2024-08-27 18:27
To help this issue, this is the codegen from Safari:
```
#include <metal_stdlib>
#include <metal_types>

using namespace metal;

template<typename T, typename U, typename V = conditional_t<is_scalar_v<U>, T, U>>
V __wgslDiv(T lhs, U rhs)
{
    auto predicate = V(rhs) == V(0);
    if constexpr (is_signed_v<U>)
        predicate = predicate || (V(lhs) == V(numeric_limits<T>::lowest()) && V(rhs) == V(-1));
    return lhs / select(V(rhs), V(1), predicate);
}

struct __ArgumentBufferT_0 {
    texture2d<float, access::sample> global0 [[id(0)]];
    sampler global1 [[id(1)]];
    device array<vec<float, 4>, 1>& global2 [[id(2)]];
    unsigned __global2_ArrayLength [[id(3)]];
};

[[kernel]]  void function0(vec<unsigned, 3> parameter0 [[thread_position_in_threadgroup]], constant __ArgumentBufferT_0& __ArgumentBuffer_0 [[buffer(0)]])
{
    sampler global1 = __ArgumentBuffer_0.global1;
    unsigned __global2_ArrayLength = __ArgumentBuffer_0.__global2_ArrayLength;
    texture2d<float, access::sample> global0 = __ArgumentBuffer_0.global0;
    device array<vec<float, 4>, 1>& global2 = __ArgumentBuffer_0.global2;
    float local0 = (float(parameter0.x) / 16.);
    vec<unsigned, 2> local1 = uint2(global0.get_width(), global0.get_height());
    vec<float, 2> local2 = vec<float, 2>(((0.5 + local0) / float(local1.x)), 0.);
    global2[min(parameter0.x, (__wgslDiv(__global2_ArrayLength, 16u) - 1u))] = vec<float, 4>(global0.sample(global1,vec<float, 2>(0., 0.), level(local0)).r, global0.sample(global1,local2, level(0.)).r, 0., 0.);
}
```

compared to tint:

```
#ifdef __clang__
   #pragma clang diagnostic ignored "-Wall"
#endif
#include <metal_stdlib>

using namespace metal;

template<typename T, size_t N>
struct tint_array {
    const constant T& operator[](size_t i) const constant { return elements[i]; }
    device T& operator[](size_t i) device { return elements[i]; }
    const device T& operator[](size_t i) const device { return elements[i]; }
    thread T& operator[](size_t i) thread { return elements[i]; }
    const thread T& operator[](size_t i) const thread { return elements[i]; }
    threadgroup T& operator[](size_t i) threadgroup { return elements[i]; }
    const threadgroup T& operator[](size_t i) const threadgroup { return elements[i]; }
    T elements[N];
};

struct tint_symbol_14 {
  /* 0x0000 */ tint_array<float4, 1> arr;
};

struct TintArrayLengths {
  /* 0x0000 */ tint_array<uint4, 1> array_lengths;
};

void tint_symbol_3_inner(uint3 tint_symbol_4, texture2d<float, access::sample> tint_symbol_8, device tint_array<float4, 1>* const tint_symbol_9, const constant TintArrayLengths* const tint_symbol_10, sampler tint_symbol_11) {
  float const tint_symbol_5 = (float(tint_symbol_4[0]) / 16.0f);
  uint2 const tint_symbol_6 = uint2(tint_symbol_8.get_width(), tint_symbol_8.get_height());
  float2 const tint_symbol_7 = float2(((0.5f + tint_symbol_5) / float(tint_symbol_6[0])), 0.0f);
  (*(tint_symbol_9))[min(tint_symbol_4[0], (((*(tint_symbol_10)).array_lengths[0u][0u] / 16u) - 1u))] = float4(tint_symbol_8.sample(tint_symbol_11, float2(0.0f), level(tint_symbol_5))[0], tint_symbol_8.sample(tint_symbol_11, tint_symbol_7, level(0.0f))[0], 0.0f, 0.0f);
}

kernel void tint_symbol_3(texture2d<float, access::sample> tint_symbol_12 [[texture(0)]], device tint_symbol_14* tint_symbol_13 [[buffer(0)]], const constant TintArrayLengths* tint_symbol_15 [[buffer(30)]], sampler tint_symbol_16 [[sampler(0)]], uint3 tint_symbol_4 [[thread_position_in_threadgroup]]) {
  tint_symbol_3_inner(tint_symbol_4, tint_symbol_12, &((*(tint_symbol_13)).arr), tint_symbol_15, tint_symbol_16);
  return;
}
```

For some reason Safari's behavior on AMD matches Apple M1 Mac, whereas Chrome does not.

**Comment by mwyrzykowski** [comment] 2024-08-27 18:27
It may not be a codegen issue, in which case comparing the generated metal won't lead us anywhere

**Comment by dneto0** [comment] 2024-08-27 18:33
> It may not be a codegen issue, in which case comparing the generated metal won't lead us anywhere

I stared at the generated AIR from both cases (with the same metal compiler) and didn't see material differences.
I suspect it's something at the API level.

**Comment by kdashg** [comment] 2024-08-27 18:41
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐08‐27-Minutes#texturesamplelevel-arguably-doesnt-work-on-intel-mac-in-compute-shaders--issue-4818">WGSL 2024-08-27 Minutes</a></summary>

* Moz: what a well-filed issue - thanks to Greg for the comparisons, numbers, and plots
* JB: It’s so strange that it’s only in compute shaders and not graphics shaders; only certain platforms. It falls within our responsibility as implementors to provide portability.  Agree with suggestion to implement workaround on those platforms.
* KG: In the spec we commit to be better than our implementations are, and better than the CTS tests make us be.  CTS should match the spec.
* MM: Difficulty in characterizing.  If spec is going to describe some are ok and some are not, that’s going to be tricky.
* JB: Well the polyfill just samples on integer boundaries and lerps.
* MM: Your proposal is the AMD mac behaviour is also not acceptable?
* JB: Yes.
* MW: Gregg says WebKit is getting better results on AMD.  Let’s get to root cause here before we move.
* JB: I’m concerned that it does work on graphics pipeline, but not in compute pipeline. If everyone is getting good results on graphics pipeline we should give good service.
* JB: These are the operations that _don’t _do derivatives: you supply the level specifically.
* MM: Since the author has to invoke these special functions that give explicit levels/graidents, these are going to be common in compute shaders.
* MM: Seems the AMD case should good enough. Rather than paying twice the cost to do two fetches.
* KG: There’s a sliding scale of acceptability.  The AMD result is strictly better than the Intel result.
* JB: _put the decision in the hands of the implementor how far out of spec you’re comfortable with._
* MW: Apple’s implementation on AMD precisely matches M1 mac.  So would not require a polyfill.  Maybe some difference in implementations.  The AMD issue is solvable without a polyfill. The Intel UHD 630 issue; should see if that reproduces outside the 630.
* KG: If the spec says it’s linear, CTS should verify that (within some tolerance). 
* AB: Gregg was creating the test when this came up.
* MM: Also the function should be monotonic.
* **DN: 1. Get to root cause difference between Chrome and WebKit on AMD.  2. Find out if other intel drivers/devices are affected.**
* KG: Amusingly, in practice there appears to be a consensus constraint, but it is quite loose: e.g. 0->0, 0.5->0.5, and 1->1!

</details>

**Comment by mwyrzykowski** [comment] 2024-08-27 19:34
> > It may not be a codegen issue, in which case comparing the generated metal won't lead us anywhere
> 
> I stared at the generated AIR from both cases (with the same metal compiler) and didn't see material differences. I suspect it's something at the API level.

This is the result I see in Safari from macOS Sequoia Beta on Intel UHD 630:
![PNG image](https://github.com/user-attachments/assets/5ddd57d4-b184-4c15-b62d-e48102d97237)

which looks correct, right? That implies we don't need to polyfill Intel, rather we just need to determine what is different between Chrome/Firefox and Safari.

We didn't specifically do anything different, the only thing I'm aware of is set at the AB flag on the sampler but it would be surprising if that was it:
https://github.com/WebKit/WebKit/blob/f98593ede9ba7582dedf768fb4f8d11cadb279ce/Source/WebGPU/WebGPU/Sampler.mm#L212

**Comment by Kangz** [comment] 2024-08-28 12:35
Looking at the public [Intel hardware specifications](https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/hardware-specs.html) volume 2d for Tiger Lake page 858 (for the definition of `SAMPLER_STATE`) there is a `MIP Linear Filter Quality` member with various options that could look similar to what @greggman is seeing. Intel Gen 10 has a similar, more loosely defined, `Allow low quality LOD calculation`.

Overall it seems that things that would fix the bad behavior we see are part of the `SAMPLER_STATE` which should appear only once per sampler in the argument buffer, and be the same for FS / VS and CS. So maybe setting `supportArgumentBuffers = true` will fix the issue (even if we don't use argument buffers), but using argument buffers should definitely fix it.

Thanks @mwyrzykowski for the details! It helped point in that direction and we should be able to fix it in Chromium.

**Comment by mwyrzykowski** [comment] 2024-08-29 19:12
Yes confirmed with @greggman that using argument buffers fixes the issue on Intel, while setting the flag alone does not. I suppose this is needed for bindless, which we haven't spec'ed yet, but is presumably coming at some point?

**Comment by Kangz** [comment] 2024-08-30 08:59
Chromium could (and wants to) use argument buffer even for the current implementation of the API, we don't at the moment because we previously supported macOS versions that didn't have argument buffers. But that's no longer the case and we should switch to AB if only for the CPU performance gains (and because it fixes this issue). Closing this this is now only an implementation issue.

**Closed by Kangz** 2024-08-30 08:59 UTC
Labels: wgsl

**Comment by c0de517e-rblx** [comment] 2024-10-28 23:19
Texture sampling is never ever going to be identical across GPUs / drivers / settings. What you are looking at here is a common technique, sometimes called "trijuicing" "brilinear" "trylinear" "trilinear optimization" etc, it always ends up being a way to avoid having to do trilinear on every single access, allowing for part of the range to be entirely in one mip level or the other, so that in many cases you can avoid having to fetch both.

This is absolutely a key thing to do, even more so when doing anisotropic. Anisotropic itself will do all kinds of tricks to avoid doing too many samples all the time, and the same applies to cube mapping, volume textures etc etc etc. Also interpolator precision might vary, TLDR, never ever expect texture operations to be identical across HW.
