### ISSUE TITLE
Can value of visibility attribute in GPUBindGroupLayoutBinding be NONE ?

### ISSUE THREAD

**Issue by shaoboyan** [gpuweb/gpuweb#405] opened 2019-08-12 02:57 UTC
In current spec, value of visibility attribute in GPUBindGroupLayoutBinding could be ShaderStage NONE, which means that the resource cannot be access by any shader stage.

Is there any use cases cover this usage?  

If not, shall we request that value of visibility attribute cannot be NONE in GPUBindGroupLayoutBinding if it is used to create a GPUBindGroupLayout?

**Comment by kvark** [comment] 2019-08-12 03:43
I don't see a use case that would involve `NONE` there, so I agree that we should require it to have some bits.

**Comment by litherum** [comment] 2019-08-16 16:06
See also: https://github.com/gpuweb/gpuweb/issues/193

**Comment by kainino0x** [comment] 2019-08-16 17:27
Thanks for remembering that. We should be consistent between the two. Also, I think that the argument I made there in favor of keeping NONE (or at least allowing 0) applies here too.

**Comment by beaufortfrancois** [comment] 2019-10-08 08:52
I think we can close this issue now since https://github.com/gpuweb/gpuweb/pull/461 has been merged

**Comment by kvark** [comment] 2019-10-08 13:59
@beaufortfrancois `NONE` is gone but 0 can still be passed in, which is what this issue is about.

**Comment by Kangz** [comment] 2021-10-18 19:19
Consensus: Allow NONE

**Comment by kvark** [comment] 2021-11-24 13:41
Do native APIs allow this? Specifically, Vulkan and D3D12?
If we have to work around this, I'd rather just forbid it instead.

**Comment by Kangz** [comment] 2021-12-07 16:32
I'm not sure for D3D12, but at least Vulkan should support it. And even calls it out in the spec:

> VUID-VkDescriptorSetLayoutBinding-descriptorType-01510
> If descriptorType is VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT and descriptorCount is not 0, then stageFlags must be 0 or VK_SHADER_STAGE_FRAGMENT_BIT

**Comment by kainino0x** [comment] 2021-12-08 02:38
Isn't the workaround trivial anyway? Just add an arbitrary bit if it's 0.

**Comment by kvark** [comment] 2021-12-14 17:55
Confirmed it's fine for Vulkan. And I believe it's fine for Metal argbuf and non-argbuf paths as well.

> Isn't the workaround trivial anyway? Just add an arbitrary bit if it's 0.

It's not that simple. Adding a bit there would make it count towards the per-stage limits.

**Comment by kvark** [comment] 2021-12-14 18:00
Confirmed it's fine on DX12 as well. So we can have NONE for free on all backends.

**Comment by Kangz** [comment] 2021-12-14 18:38
Great!

**Closed by Kangz** 2021-12-14 18:38 UTC
Labels: enhancement, question
