### ISSUE TITLE
Dealing with holes in the pipeline layout.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2043] opened 2021-08-17 12:43 UTC
Let's say that for some reason I would like to create a pipeline that only uses bind groups 0 and 2. This could happen for example if I choose BG 1 to be for the fragment data and BG 2 for vertex data, and want to render without an FS. (but many other reasons).

Because `GPUPipelineLayoutDescriptor.bindGroupLayout` is non-sparse, right now to create the pipeline I need to do the following:

```js
const bgl0 = device.createBindGroupLayout(...);
const bgl2 = device.createBindGroupLayout(...);

const layout = device.createPipelineLayout({
    bindGroupLayouts: [
        bgl0,
        device.createBindGroupLayout({entries: []}), // This is the important part
        bgl2,
    ],
});
const pipeline = ...;
```

But then to draw with this pipeline I need to set an empty `GPUBindGroup` at group index 1 to satisfy ["validate encoder bindgroups"](https://gpuweb.github.io/gpuweb/#abstract-opdef-validate-encoder-bind-groups). This is an annoying to just "unset" a bindgroup.

I'd like to suggest that we allow either `GPUPipelineLayoutDescriptor.bindGroupLayout` to be sparse, or during validation, treat the empty bindgrouplayout the same way as requiring no bind groups.

**Comment by kvark** [comment] 2021-08-17 19:05
Let's see how native APIs deal with this:
  - Vulkan requires `const VkDescriptorSetLayout*    pSetLayouts;` to be provided in `VkPipelineLayoutCreateInfo`. So it requires consecutive bind groups, essentially.
  - Metal doesn't have a pipeline layout concept natively
  - DX12's root signature is virtualized, so it doesn't care about the gaps in the pipeline layout.

Given that WebGPU's binding model is closest to Vulkan, it makes sense to consider how it's used in Vulkan land. Since it's impossible to create a gap in the pipeline layout, people aren't doing it. Therefore, what motivates us to consider having special logic here?

Those coming from Vulkan aren't doing it. For those who want a gab, they can create an empty BGL/BG and use it.

**Comment by kainino0x** [comment] 2021-08-17 22:29
vaguely related: #1250

**Comment by Kangz** [comment] 2021-08-18 13:15
> Since it's impossible to create a gap in the pipeline layout, people aren't doing it. Therefore, what motivates us to consider having special logic here?

In Vulkan land people have to make holes using empty VkDescriptorSetLayouts. Compared to Vulkan, developer-friendliness is more important in WebGPU and why I raised this issue.

**Comment by kvark** [comment] 2021-08-18 15:06
Is the developer-friendliness argument based on real feedback, or just threoretical?
I'd put this feature into "worth looking after MVP" category, since it's non-essential and involves API complexity.

**Comment by Kangz** [comment] 2021-08-18 15:08
For now it is mostly theoretical. I ran into it a couple times but that was to write tests so not very real-world.

**Comment by Kangz** [comment] 2021-08-24 11:56
As discussed in the last meeting, here's an example of what the validation looks like at draw time at the moment (in pseudo code,  actual validation is different in Dawn for a mix of optimization and historical reasons):

```cpp
class State {
  void OnSetBindGroup(int index, BindGroup* group) {
    mBindGroups[i] = group;
  }
  void OnSetPipeline(PipelineBase* pipeline) {
    mPipeline = pipeline;
  }
  MaybeError ValidateBindGroupsForDraw() {
    int bglCount = mPipeline->GetBindGroupLayoutCount();
    for (int i = 0; i < bglCount; i++) {
      if (mBindGroups[i]->GetLayout() != mPipeline->GetBindGroupLayout(i)) {
        return VALIDATION_ERROR("Blah");
      }
      // Check the buffer sizes if needed if minBindingSize wasn't used.
    }
    return {};
  }

  BindGroup* mBindGroups[4];
  PipelineBase* mPipeline;
};
```

Adding the fact that a null bindgroup can be used with the empty pipeline layout (or null layout) requires changing the condition to something like:

```diff
-if (mBindGroups[i]->GetLayout() != mPipeline->GetBindGroupLayout(i))
+BindGroup* bg = mBindGroups[i];
+BindGroupLayout* bgl = mPipeline->GetBindGroupLayout(i);
+if (bg == nullptr || bg->GetLayout()->IsEmpty()) {
+  if (!(bgl == nullptr || bgl->IsEmpty())) {
+    return VALIDATION_ERROR("Blah");
+  }
+} else if (bgl != bg->GetLayout()) {
+  return VALIDATION_ERROR("Blah");
+}
```

However if we decided to canonicalize null BGLs to the empty BGL at pipeline creation, then we can do the following, which isn't too bad (it tracks BGLs in `OnSetBindGroup` and canonicalize to the empty bind group layout when possible):

```cpp
class State {
  void OnSetBindGroup(int i, BindGroup* group) {
    mBindGroups[i] = group;
    if (group == nullptr) {
      mBGLs[i] = EmptyBindGroupLayout;
    } else {
      mBGLs[i] = group->GetLayout();
    }
  }
  void OnSetPipeline(PipelineBase* pipeline) {
    mPipeline = pipeline;
  }
  MaybeError ValidateBindGroupsForDraw() {
    int bglCount = mPipeline->GetBindGroupLayoutCount();
    for (int i = 0; i < bglCount; i++) {
      if (mBGLs[i] != mPipeline->GetBindGroupLayout(i)) {
        return VALIDATION_ERROR("Blah");
      }
      // Check the buffer sizes if needed if minBindingSize wasn't used.
    }
    return {};
  }

  BindGroup* mBindGroups[4];
  BindGroupLayout* mBGLs[4];
  PipelineBase* mPipeline;
};
```

There's a very slight difference in the validation cost which I don't think will be measurable, so this shouldn't be a concern.

**Comment by kvark** [comment] 2021-08-24 13:51
I think, conceptually, we already have null BGL entries - it's all of the entries after the set provided by the user. Correspondingly, the behavior of `setBindGroup(N, X)` for N >= number of entries of the current pipeline would be the same as for N corresponding to a null entry. So this change is not complicating the pass state in theory.

**Comment by Kangz** [comment] 2021-08-24 14:22
It's not 100% clear if these are different: currently WebGPU doesn't require that unused bindgroups past `pipeline->bindgroupLayoutCount` are the empty bindgroup. However it is not clear if for wholes in the pipeline the bindgroup should be ignored, or if we require them to be null/empty.

**Comment by frguthmann** [comment] 2021-08-25 09:09
I've hit this issue in our engine as well but it might be because of a bad design decision regarding bindgroups. Moving from WebGL is not trivial, please let me know if I missed a simpler solution here.

The first thing I did to support bindgroups was to attribute a static index to all of our bindgroups. There's an enum somewhere that looks like PER_PASS : 0, PER_MATERIAL : 1, PER_DRAW : 2. These are used to identify data when building pipeline layouts for example. Then I wrote a bunch of ubershaders that will use some or all of theses bindgroups. The ubershaders are specialized at runtime based on what the current pass is or what features the material has. ( Think #ifdef MUST_TONEMAP, #ifdef HAS_CLEARCOAT or whatever )

Because of this runtime specialization, I cannot know in advance which bindgroups will be used. It is entirely possible that a shader module will use the PER_PASS and PER_DRAW bindgroups but not the PER_MATERIAL bindgroup. This means that if I write these static indices in the shader code, there will be a hole in the indices.

The first solution I used to solve this problem was to generate dynamic indices and to procedurally write the IO code for our shaders at runtime. In the previous example, PER_PASS would remain 0 but PER_DRAW would be remapped to 1. At the time I was using this solution, I was not caching shader modules separately but rather couples of vs + fs, a shader "program" in the WebGL terminology.

This was convenient because I would get the pipeline layout at module creation time. I would look at the code of both vs and fs, identify the bindgroups needed by both, remap the indices and then create two shader modules. It worked well but would trigger redundant shader module compilations. For example, for the two programs vs0 + fs0 and vs0 + fs1, I would compile vs0 twice.

To avoid the redundant compilations, I decided to cache shader modules separately. But if I do that, I don't get the entire pipeline layout at module creation time, which means it is impossible to remap bindgroup indices. Let's say for example the VS uses PER_PASS and the FS uses PER_DRAW. At module creation time, both would get their indices remapped to 0 because each shader only knows about its own layout. 

I would defer this index remapping operation at pipeline creation time but since I need to hardcode bindgroup indices in the shader code, that would mean deferring shader modules creation at pipeline creation. My solution to this was to go back to using static indices. At pipeline creation time I figure out the pipeline layout based on the layouts of my two modules, I figure out if there are holes and whenever I'm drawing I bind an empty bindgroup where there is a hole.

Because of the way my code is written, allowing empty bindgroups was super easy. it just feels weird to do it. Also, if you don't have proper caching in place you might end up creating quite a few empty bindgroups.

**Comment by Kangz** [comment] 2021-08-25 11:25
Thank you for the detailed explanation of how you hit this in practice! I think that having PER_PASS/MATERIAL/DRAW statically assigned to 0/1/2 is a good approach but like you said it will give rise to empty bindgrouplayouts that need to match with an empty bindgroup bound at runtime. This is a small papercut that we could remove from the API for minimal additional validation cost.

**Comment by magcius** [comment] 2021-12-21 16:49
From my understanding, the issue is that they need to fill the missing bind group with resources they don't have, because there's no way to bind nothing. If PER_MATERIAL has slots for 16 textures, they must fill in a bind group with 16 textures even if the shader does not use that bind group, which is unfortunate.

**Comment by kvark** [comment] 2021-12-21 18:27
Right. The author has a choice:
  1. treat these shaders as a special group with a separate pipeline layout that only has PER_PASS and PER_DRAW groups (assigned to indices 0 and 1)
  2. treat these shaders as if the material is dummy, so the relevant material bind group is still created and bound

**Comment by magcius** [comment] 2021-12-21 18:44
There is a third choice, if accepted by the WebGPU committee:

3. Since it is known the shader does not access the PER_MATERIAL bind group, allow setting it to null.

This requires some extra draw-time validation, but it would mean that the user would not have to create a dummy bind group. It is possible the performance tradeoff of this solution is deemed unacceptable, but consider that 1. is also a performance trade-off, since layouts cannot be shared, but it is the easier of the two approaches.

**Comment by kvark** [comment] 2021-12-21 21:01
We had a good discussion about this with @magcius , in particular about how Vulkan users take advantage of this.
Here is the TL;DR:
  - Vulkan still requires the pipeline layout to not have holes.
  - If the current pipeline doesn't use a group at index N, Vulkan allows this group's binding to be anything.

So that second part is what allows users to avoid creating empty bind groups (Vulkan descriptor sets). This is more general than just having the holes, and it can work without holes. This is an idea that WebGPU could relax its binding model requirements in a similar way:
> If the current pipeline doesn't use group number N, then there is no requirement on anything bound to `set_bind_group(N, ..)`.

Here are some questions to move forward:
  1. Need to double check if it's fine on D3D12 and Metal. My preliminary analysis suggests that it is fine for our implementation at least.
  2. Is the group positive about moving in this direction?
  3. How much work would it be for implementations? Seems like a little bit of work so far.
  4. How much overhead would that have on draw time validation?

**Comment by Kangz** [comment] 2021-12-22 10:54
Thanks for the summary.

 1. For Dawn I think it wouldn't be all that much effort. We already use a "bitmask" of groups that are set when doing things, and already need to handle pipeline layout invalidation.
 2. If it wasn't clear from my opening the issue I'm slightly in favor of doing this.
 3. Almost free for Dawn I think. However we would need fairly good CTS tests there and that would be a couple days to a week of work to do.
 4. Almost none for us, we already iterate over the bitmask of BGLs of the pipeline layout (though it could slightly more optimal to iterate over a dense range).

**Comment by kdashg** [comment] 2023-02-28 07:44
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#post-v1-dealing-with-holes-in-the-pipeline-layout-2043">GPU Web F2F 2023-02-16/17</a></summary>

* CW: now you can reset BGs to null / uninitialized. Right now have to fake up empty BGLs. Have to create empty BG.
* MM: instead of doing that, can do a null BG, same as creating an empty one.
* CW: even better if BGL sequence can be sparse.
* MM: careful about terminology. 3 levels. 1) all things need indices which increase by 1 every time (dense). 2) use any number. 3) Choose a number between 0 and 8, but can have a 3 without a 2.
* CW: here, talking about (3).
* MM: sounds great.
* CW: to be clear, this is post-V1.
* MM: also great.
* KG: V1 is dense?
* CW: right now, yes. If you create an empty BGL, unbinding the BG doesn't do it.
* MM: that's fine for V1. Make it sparse later.
* CW: point of process. This is the first agreed upon post-V1 feature. When do we put it in the spec?
* MM: spec will have a bunch of features. Not all are in V1. Not all in V7. Some list saying "V2 is this".
* CW: not a hardware feature. Won't be an optional feature.
* KN: needs to be feature detectable.
* KG: everything is, by checking errors. :)
* MM: would like to see the code for that. If more than ~15, that's unfortunate.
* CW: push/pop error scope, await a thing.
* KG: need dummy resources to bind?
* CW: no, just create empty BGL. Empty pipeline layout with nothing in 0 adn that in 1. push/pop error scope, await. ~6 lines.
* BJ: make it a new limit. maxGapBetweenBindGroupLayoutIndices. :)
* KG: just land it. Then canIUse has a breakdown. Who supports sparse BGLs?
* MM: worth having a discussion - e.g. in CSS, feature detection's @supports . For us, granularity's non-obvious. Spec'ing several different entry points for a new feature - if I test one of those, does it mean all of them are there? Yesterday, wgsl resolution - each feature gets a name, written down. Have deliberate discussion about feature detection?
* BJ: check feature? Feels heavyweight. If dividing things into post-V1, we have a way to name features.
* MM: not suggesting giving a name. One particular solution. Features feature - if device doesn't request one of them, have to act as if it's disabled. Not what we want here.
* BJ: I foresee a lot of contentious future debates. Which bucket does a future feature fall into? Easy to look at HW caps, definitely a feature, might not be universal. Stuff like this - more palatable to say, we can implement it as we go. Making it feature detectable is important. Don't rely just on canIUse. Want to check at runtime.
* MM: every option here has feature detectability. Not should things be feature detectable - what should the developer experience be? Maybe we don't define any granularity. Try stuff, push/pop error scopes. THa'ts one extreme. OR, do it like hardware features. Possibility.
* CW: we'll have helper libraries. Here's something that does feature detection. Something we could produce.
* MM: reasonable. Once we talk about creating new community group documents, that's where charter gets involved. We could write a JS function that does the feature detection.
* CW: procedurally - members "happen" to maintain another repo.
* MM: that'd be fine.
* KR: comment about Modernizr and not wanting to create random WebGPU devices just for feature detection, like it did for WebGL. Also, github.com/webgpu org doesn't have the same charter as the CG, so helper libraries can go there.
* AE: right now, setVB will throw an exception due to the Web IDL.

</details>

**Comment by greggman** [comment] 2024-02-06 20:13
There might be another solution but this is affecting my ability to write a CTS test.

I'm trying to write a test for `maxBindGroupsPlusVertexBuffers`. There are 2 places this limit is checked. One, when calling `drawXXX`. The other, when creating a render pipeline. 

In this second case, the spec says

> layout.[[[bindGroupLayouts]]](https://gpuweb.github.io/gpuweb/#dom-gpupipelinelayout-bindgrouplayouts-slot).length + vertexBufferCount is ≤ this.[[[device]]](https://gpuweb.github.io/gpuweb/#dom-gpuobjectbase-device-slot).[[[limits]]](https://gpuweb.github.io/gpuweb/#dom-device-limits-slot).[maxBindGroupsPlusVertexBuffers](https://gpuweb.github.io/gpuweb/#dom-supported-limits-maxbindgroupsplusvertexbuffers), where vertexBufferCount is the maximum index in descriptor.[vertex](https://gpuweb.github.io/gpuweb/#dom-gpurenderpipelinedescriptor-vertex).[buffers](https://gpuweb.github.io/gpuweb/#dom-gpuvertexstate-buffers) that is not undefined.

So, there are arguably 2 things to test here.

1. creating a pipeline with `layout: 'auto'`
2. creating a pipeline with a manually created pipeline layout.


1 is easy. Create a shader module that uses some high index group, effectively this

  ```
  @group(maxBindGroups - 1) @binding(0) var<uniform> u: f32;
  @vertex fn vs(@location(0) v: vec4f) -> @builtin(position) vec4f {
    _ = u;
    _ = v;
    return vec4f(0);
  }
  ```

  This gives me a sparse pipelineLayout. I can assign a high vertex buffer index to the attribute and test the validation succeeds or fails.

2 is not easy. Because I can't make a sparse pipeline layout via `createPipelineLayout`, currently my only option is to make a non-sparse pipeline layout. A non-sparse pipeline layout ends up being troublesome because there is no limit on `maxBindGroups`. Say it's 1000. Suddenly I can't fill up bindGroups because other settings limit the number of each type of resource (maxSamplersPerShaderStage, maxSampledTexturesPerShaderStage, maxUniformBuffersPerShaderStage, maxStorageBuffersPerShaderStage, maxStorageTexturesPerShaderStage). Even if those extra limits add up to maxBindGroups you end up having to make a way to generate bind groups that use all the various kinds of resources since any one type may not be enough to reach the limit.

On the otherhand, if you could create sparse pipeline layouts manually like you can with `layout: 'auto'` then this becomes a simple test. You just make an array of `bindGroupLayouts` that's all empty except for index `maxBindGroups - 1` as in

```
const bindGroupLayouts = new Array();
bindGroupLayouts[maxBindGroup - 1] = bindGroupLayout
```

Does this suggest sparse pipeline layouts should be moved up to v1? They already exist via `layout: 'auto'` so it seems like this is mostly just an IDL change since the backends are already handling this.

**Comment by kainino0x** [comment] 2024-02-06 22:27
> A non-sparse pipeline layout ends up being troublesome because there is no limit on `maxBindGroups`. Say it's 1000. Suddenly I can't fill up bindGroups because other settings limit the number of each type of resource (maxSamplersPerShaderStage, maxSampledTexturesPerShaderStage, maxUniformBuffersPerShaderStage, maxStorageBuffersPerShaderStage, maxStorageTexturesPerShaderStage).

It should be possible to fill it up with empty bind groups.  The "auto" [default pipeline layout](https://gpuweb.github.io/gpuweb/#abstract-opdef-default-pipeline-layout) algorithm doesn't actually generate pipeline layouts with holes, it fills the holes with empty bind group layouts.

**Comment by greggman** [comment] 2024-02-06 22:40
> It should be possible to fill it up with empty bind groups. The "auto" [default pipeline layout](https://gpuweb.github.io/gpuweb/#abstract-opdef-default-pipeline-layout) algorithm doesn't actually generate pipeline layouts with holes, it fills the holes with empty bind group layouts.

Wouldn't that then require binding empty groups to pass validation at draw time?

https://gpuweb.github.io/gpuweb/#abstract-opdef-validate-encoder-bind-groups

**Comment by Kangz** [comment] 2024-02-07 13:21
> Wouldn't that then require binding empty groups to pass validation at draw time?

It does, which is what this issue is about: the pipeline layout should get empty bind group layouts, but we should require users to actually bind empty bind groups there. However I don't think we should count the number of non-empty BGLs for `maxBindGroupsPlusVertexBuffers`, only the largest group index used (+1) IMHO. (plus I still believe this limit will never actually be able to be hit in any browser)

**Comment by greggman** [comment] 2024-02-07 18:27
Ok, I was unaware of the empty bind groups stuff. Thanks for clarifying.

Is it spelled out that all empty bindgroups are compatible with each other? Usually, bind groups from a `layout: 'auto'` are not compatible even if they would appear to be. But, in the case of an empty bindgroup, it appears any empty bind group will do. That's great! Just didn't find it in the spec.

Here (https://gpuweb.github.io/gpuweb/#default-pipeline-layout) there's a note:

> NOTE: Default layouts are provided as a convenience for simple pipelines, but use of explicit layouts is recommended in most cases. Bind groups created from default layouts cannot be used with other pipelines, and the structure of the default layout may change when altering shaders, causing unexpected bind group creation errors.

But a quick test seems to be that if the bind group layout is empty then even from a default layout it's compatible.

Actually, layouts from 2 different pipelines generated with default layouts are compatible with each other even though the spec seems to say they are not supposed to be. Is that a bug in Chrome?

**Comment by kainino0x** [comment] 2024-02-07 22:45
> Is it spelled out that all empty bindgroups are compatible with each other? Usually, bind groups from a `layout: 'auto'` are not compatible even if they would appear to be. But, in the case of an empty bindgroup, it appears any empty bind group will do. That's great! Just didn't find it in the spec.

I don't think that's spelled out, I don't even think it was intentional. Both things you found are probably bugs in Chrome - though for empty bind groups we might consider making an exception in the spec for convenience.

**Comment by Kangz** [comment] 2024-10-25 17:20
Since I'm hoping to discuss this at the upcoming F2F, here is a concrete proposal.

 - Change `GPUPipelineLayoutDescriptor.bindGroupLayouts` to be `required sequence<GPUBindGroupLayout?>` (the change is the addition of the `?`)
 - Change the algorithm for createPipelineLayout to reify an empty BGL to "null" instead.
 - Change [Validate encoder bind groups](https://gpuweb.github.io/gpuweb/#abstract-opdef-validate-encoder-bind-groups) to clarify that it iterates over the non-null BGLs in the pipeline layout.

**Comment by beaufortfrancois** [comment] 2024-10-31 10:41
@Kangz I've started https://github.com/gpuweb/gpuweb/pull/4946

**Closed** 2024-11-01 23:45 UTC
Labels: api resolved, api

**Comment by Kangz** [comment] 2024-11-19 18:53
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-10-F2F#dealing-with-holes-in-the-pipeline-layout-2043-corentin">GPU Web WG 2024-10-29/30 Mountain View F2F</a></summary>

* CW: If you have a GPU pipeline layout, and you want to leave an empty bind group layout, you have to add a bindgroup with zero bindings. That’s annoying.  Proposal has three parts:
    * Change `GPUPipelineLayoutDescriptor.bindGroupLayouts` to be `required sequence&lt;GPUBindGroupLayout?>` (the change is the addition of the `?`)
    * Change the algorithm for createPipelineLayout to reify an empty BGL to "null" instead.
    * Change [Validate encoder bind groups](https://gpuweb.github.io/gpuweb/#abstract-opdef-validate-encoder-bind-groups) to clarify that it iterates over the non-null BGLs in the pipeline layout.
* JSP +1
* BJ +1
* TT: +1
* KG: Sure +1
* CW: Next step is make a PR, CTS, prototype, ship

</details>
