### ISSUE TITLE
Adding support for rgba16unorm texture format

### ISSUE THREAD

**Issue by ankit040683** [gpuweb/gpuweb#3333] opened 2022-08-16 03:45 UTC
All the backend APIs support this (rgba16unorm), so this needs to be exposed to WebGPU clients

**Comment by kainino0x** [comment] 2022-08-16 18:03
Vulkan supports rgba16unorm (R16G16B16A16_UNORM), but it doesn't require it. This came up recently for rg16unorm as well although I don't remember why. To add this it would have to be an optional feature flag.

Adding this requirement to our vulkan support [query script](https://github.com/kainino0x/gpuinfo-vulkan-query) shows the following:

```
Requirement "rg16unorm sampled" loses 9 (and partially loses 3) further deviceNames:
  In ALL reports (9 deviceNames):
    x Adreno (TM) 504: 6 (8629 9137 10642 11160 11664 12378)
    x Adreno (TM) 505: 26 (4259 4457 4489 4824 6129 7394 7550 8516 8922 9025 9063 9355 9501 9798 10174 10776 11057 11789 12203 12269 12277 12342 13211 14230 14771 14913)
    x Adreno (TM) 506: 48 (3851 4541 4680 4724 4916 4956 5006 5250 5990 6044 6058 6151 6814 7023 7137 7612 8841 9054 9060 9935 10294 10314 10414 10431 10513 10542 10810 10941 10997 11017 11346 11423 11493 11526 11656 12201 12360 12454 12578 12618 12636 12785 12953 13423 13426 13508 13618 14282)
    x Adreno (TM) 508: 9 (4452 6680 8652 10383 10442 10589 12379 13414 14872)
    x Adreno (TM) 509: 14 (4924 6120 8358 9062 9064 11486 11487 11488 11673 11820 12108 12678 13230 14911)
    x Adreno (TM) 510: 1 (6786)
    x Adreno (TM) 512: 38 (3724 4394 4400 4683 4768 5679 6063 6787 7385 8566 8697 10195 10204 10546 10608 10638 10656 10700 10775 11177 11237 11326 11399 11452 11475 11605 11663 11933 12813 13364 13421 13578 13616 13837 14233 14625 14716 14916)
    x Adreno (TM) 530: 48 (3183 3597 3603 3765 3907 4359 4363 4773 4999 5019 5103 5210 5314 5399 5402 6072 6100 6215 6285 6560 6841 6885 7313 7542 7601 8268 8483 8544 9061 9332 10486 10681 10827 10838 10958 11034 11724 11874 12263 13278 13802 13934 13964 14311 14312 14364 14491 15081)
    x Adreno (TM) 540: 63 (3422 3450 3532 3571 4071 4145 4433 4503 5102 5150 5215 5259 5383 5632 5811 5866 6046 6068 6083 6163 6208 6405 6796 7584 8603 8977 9008 9251 9354 9705 10284 10347 10597 10728 10752 10784 10786 10819 10844 10908 11101 11225 11338 11350 11485 11498 11665 11669 12292 12489 13097 13246 13294 13482 13577 13751 14142 14175 14369 14844 15188 15241 15257)
  In SOME reports (3 deviceNames):
    ~ Adreno (TM) 615: 3 of 15 (5944 6088 7898; ok: 6436 7927 8903 9147 9184 9422 10427 11275 12085 12583 12996 13171)
    ~ Adreno (TM) 616: 5 of 14 (4986 5287 6492 9756 11712; ok: 7806 10393 10604 11072 12858 13327 13564 14753 14828)
    ~ Adreno (TM) 630: 48 of 110 (2801 3024 3138 3305 3442 3665 3687 3754 3755 3795 3810 3927 4134 4140 4249 4270 4366 4403 4413 4486 4525 4563 4599 4628 4632 4915 4926 5175 5253 5800 6032 6038 6056 6107 6162 6234 6266 6704 6996 7057 8585 8951 10285 11026 12775 13424 13749 13963; ok: 5886 6434 6788 6987 7108 7374 7949 8473 8577 8907 9097 9267 9471 10287 10291 10300 10302 10303 10351 10371 10424 10460 10551 10672 10678 10730 10770 10813 10966 11016 11035 11120 11464 11602 11670 11695 11914 11922 12213 12280 12363 12429 12430 12667 13256 13428 13552 13642 13675 13676 13752 13991 14092 14393 14463 14523 14608 14610 14611 14717 14751 14806)
Requirement "rgba16unorm sampled" loses 0 (and partially loses 6) further deviceNames:
  In ALL reports (0 deviceNames):
  In SOME reports (6 deviceNames):
    ~ Adreno (TM) 610: 2 of 70 (7037 10410; ok: 8669 9434 9524 10094 10192 10384 10412 10420 10471 10516 10572 10885 10932 11059 11076 11212 11372 11375 11384 11390 11459 11522 11701 11917 11936 11946 11974 12002 12158 12294 12350 12367 12420 12546 12897 12899 12999 13031 13080 13146 13219 13257 13262 13288 13565 13651 13763 13903 13916 14022 14043 14203 14252 14331 14392 14437 14575 14594 14636 14714 14833 14836 14896 15020 15037 15174 15224 15235)
    ~ Adreno (TM) 612: 4 of 19 (5789 6220 7986 12216; ok: 7178 9014 10707 10874 11318 11661 12084 12126 12476 14223 14301 14525 14548 15080 15106)
    ~ Adreno (TM) 615: 2 of 12 (6436 7927; ok: 8903 9147 9184 9422 10427 11275 12085 12583 12996 13171)
    ~ Adreno (TM) 618: 1 of 53 (6379; ok: 7893 9036 9037 9351 9692 9862 10286 10295 10432 10481 10488 10499 10834 10897 10945 11022 11144 11198 11217 11253 11482 11615 11796 11813 11937 12035 12055 12144 12278 12918 13032 13042 13165 13178 13238 13598 13736 13865 13866 13915 13996 13998 13999 14122 14358 14359 14423 14718 14757 14923 15200 15243)
    ~ Adreno (TM) 630: 7 of 62 (5886 6434 6788 6987 7374 10300 10460; ok: 7108 7949 8473 8577 8907 9097 9267 9471 10287 10291 10302 10303 10351 10371 10424 10551 10672 10678 10730 10770 10813 10966 11016 11035 11120 11464 11602 11670 11695 11914 11922 12213 12280 12363 12429 12430 12667 13256 13428 13552 13642 13675 13676 13752 13991 14092 14393 14463 14523 14608 14610 14611 14717 14751 14806)
    ~ Adreno (TM) 640: 26 of 100 (5552 5633 6040 6188 6239 6363 6403 6603 6820 6875 7175 7237 7595 7708 9111 10305 10380 10391 10805 10847 10921 10923 11254 11495 13753 13760; ok: 7088 9426 9503 10183 10348 10368 10465 10611 10738 10768 10940 10943 10944 11070 11168 11190 11257 11334 11368 11489 11525 11575 11666 11667 11668 11671 11773 11799 11810 11847 11876 11895 11926 12423 12604 12841 12843 12846 12931 13027 13247 13309 13412 13493 13560 13629 13743 14009 14038 14101 14105 14247 14371 14416 14419 14460 14526 14561 14566 14681 14770 14793 14944 14945 14948 14987 15008 15086 15114 15116 15145 15172 15175 15189)
```

**Comment by kainino0x** [comment] 2022-08-17 02:17
Updated the query to report results for `snorm` formats as well. They seem to be just as well supported as `unorm`. So if we add an optional feature, I would propose it add all 6 of these formats (r,rg,rgba &times; unorm,snorm).

**Comment by kainino0x** [comment] 2023-04-12 23:33
Just noticed this is a duplicate of #3001 (wow, two great issue numbers). Going to merge this in there and also generate a new gpuinfo report.

**Closed by kainino0x** 2023-04-12 23:33 UTC
Labels: feature request
