### ISSUE TITLE
Investigation: Viewport and Scissor Test

### ISSUE THREAD

**Issue by Richard-Yunchao** [gpuweb/gpuweb#120] opened 2018-11-16 10:34 UTC
# Introduction
**Viewport** is used to do the transformation right before rasterization. It transforms vertices from normalized device coordinates to window coordinates. **Scissor rectangle** is used to do scissor test right after rasterization. It ensures the rasterized fragments/pixels are within a specified rectangle. 

This document attempts to describe viewport and scissor test related features among three native graphics APIs, in order to discuss missing features in WebGPU idl.

# Native APIs
## D3D12
**Viewport**
D3D12 defines viewport via [D3D12_VIEWPORT](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_viewport). It is listed as follow:
```cpp
typedef struct D3D12_VIEWPORT {
  FLOAT TopLeftX;
  FLOAT TopLeftY;
  FLOAT Width;
  FLOAT Height;
  FLOAT MinDepth;
  FLOAT MaxDepth;
} D3D12_VIEWPORT;
```
We can set multiple viewports via [ID3D12GraphicsCommandList::RSSetViewports](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/nf-d3d12-id3d12graphicscommandlist-rssetviewports) in D3D12. And this is the only way to set viewport. Viewports are not included in `D3D12_GRAPHICS_PIPELINE_STATE_DESC` or other state descriptors in D3D12.  Function `RSSetViewports` is listed as follow:
```cpp
void RSSetViewports(
  UINT                 NumViewports,
  const D3D12_VIEWPORT *pViewports
);
```
**Scissor Test**
Likewise, we can set multiple scissor rectangles via [ID3D12GraphicsCommandList::RSSetScissorRects](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/nf-d3d12-id3d12graphicscommandlist-rssetscissorrects). And this is the only way to set scissor rectangle. Scissor rectangles are not included in `D3D12_GRAPHICS_PIPELINE_STATE_DESC` or other state descriptors in D3D12. Function `RSSetScissorRects` is listed as follow:
```cpp
void RSSetScissorRects(
  UINT             NumRects,
  const D3D12_RECT *pRects
);
```
Each scissor rectangle is defined as [D3D12_RECT](https://docs.microsoft.com/en-us/windows/desktop/direct3d12/d3d12-rect), which is RECT. RECT is defined as follow:
```cpp
typedef struct _RECT {
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
} RECT, *PRECT;
``` 
Currently D3D12 doesn't include a parameter like `scissorEnable` to enable/disable scissor test, although D3D11 and some outdated versions of D3D12 do have this parameter in `D3D11_GRAPHICS_PIPELINE_STATE_DESC` and `D3D12_GRAPHICS_PIPELINE_STATE_DESC`.

## Metal
**Viewport**
Metal can set one viewport via [MTLRenderCommandEncoder::setViewport](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515527-setviewport?language=objc), and multiple viewports (an array of viewports) like D3D12 via [MTLRenderCommandEncoder::setViewports](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/2869738-setviewports?language=objc). 

The structure [MTLViewport](https://developer.apple.com/documentation/metal/mtlviewport?language=objc) is the same as `D3D12_VIEWPORT`, which includes 6 parameters with the same meanings. 

**Scissor Test**
Metal can set one scissor rectangle via [MTLRenderCommandEncoder::setScissorRect](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515583-setscissorrect?language=objc), and multiple scissor rectangles (an array of scissor rectangles) like D3D12 via [MTLRenderCommandEncoder::setScissorRects](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/2869722-setscissorrects?language=objc). 

The structure [MTLScissorRect](https://developer.apple.com/documentation/metal/mtlscissorrect?language=objc) is similar to `D3D12_RECT`. But it is a little different, it use (uint x, uint y, uint width, uint height). Note that the data types of all 4 parameters are **uint**. But they are **long** in D3D12. And Metal uses width and height, so there is no direction issue like top < bottom or top > bottom.  

Metal doesn't include a parameter like `scissorEnable` to enable/disable scissor test.

## Vulkan
**Viewport**
Vulkan includes a viewport state named [VkPipelineViewportStateCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkPipelineViewportStateCreateInfo), in which you can initialize multiple viewports. `VkPipelineViewportStateCreateInfo` is a part of `VkGraphicsPipelineCreateInfo` in Vulkan. 

In addition, Vulkan can set multiple viewports via [vkCmdSetViewport](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#vkCmdSetViewport). It is a little bit different from setViewports function in D3D12 and Metal. Because Vulkan can update partial viewports of the viewports array in `VkPipelineViewportStateCreateInfo`, with `firstViewport` as an offset to the array. Of course, we can update all viewports by setting the `fristViewport` to 0 and `viewportCount` to the length of the array. 

The structure [VkViewport](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkViewport) is the same as `D3D12_VIEWPORT`, which includes 6 parameters with the same meaning. 

**Scissor Test**
Likewise, Vulkan can initialize multiple scissor rectangles via `VkPipelineViewportStateCreateInfo`, and it can update a part of scissor rectangles via [vkCmdSetScissor]( https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#vkCmdSetScissor), with `firstScissor` as an offset to the array. We can also update all scissor rectangles by setting the `fristScissor` to 0 and `scissorCount` to the length of the array. 

Scissor rectangle in Vulkan is like that in Metal, except that x and y parameters are int, not uint. The rectangle is described by (int x, int y, uint width, uint height) in Vulkan.

Vulkan doesn't include a parameter like `scissorEnable` to enable/disable scissor test.

# Conclusion and Proposal
1. Metal, D3D12 and Vulkan can support multiple viewports and multiple scissor rectangles. But only geometry shading will use multiple viewports and multiple scissor rectangles. WebGPU doesn't support geometry shading in its MVP (and 1.0?). As a result, supporting one viewport and one scissorRect is simple and straightforward for developers. **However, we may support multiple viewports and multiple scissor rectangles for WebVR in future.** 

2. Metal, D3D12 and Vulkan can set viewport and scissor rectangle by some functions in similar manner. Viewport and scissor test is necessary for some use cases. So I think we should add these two functions into **WebGPURenderPassEncoder**.  
```cpp
void setViewport(float x, float y, float width, float height, float minDepth, float maxDepth);
void setScissorRect(u32 x, u32 y, u32 width, u32 height);
```
Note that I propose to use uint32 for scissor rect, but D3D12 uses `long` for all parameters in scissor rect, and Vulkan uses `int32` for x and y parameters. However, a negative value makes no sense here. So I propose to use uint32 to simplify it, just as Metal does. 

3. Only Vulkan can support viewport and scissor rect in its `VkGraphicsPipelineCreateInfo`, so we might don't add viewport or scissor rect to `WebGPURenderPipelineDescriptor`.

4. Only D3D11 and some outdated versions of D3D12 can support `scissorEnable` in its graphics pipeline state descriptor, so we don't add `scissorEnable` to `WebGPURenderPipelineDescriptor`

# TODO
Update the WebGPU idl once we get consensus on this.

**Comment by Richard-Yunchao** [comment] 2018-11-16 10:40
Metal, D3D12 and Vulkan have quite similar manner on **Viewport** and **Scissor Test**, but we missed a couple of functions in WebGPU idl. So, PTAL when you have time, although you might be busy discussing shading language these days.

**Comment by kvark** [comment] 2018-11-20 14:32
Great stuff, @Richard-Yunchao , thank you!

There is one aspect seemingly missing from the investigation: how does depth clipping/clamping work?
  - is output depth clipped to [0, 1] or clamped?
  - is the final range [0, 1] or [-1, 1]
  - is the viewport depth range applied before or after that clipping/clamping?

I'm sure we mostly know the answers here, but let's make this clear in the document.

> Metal, D3D12 and Vulkan can support multiple viewports and multiple scissor rectangles.

Note that Metal's support for multiple rectangles requires a much higher baseline for OS/HW: iOS 8.0 -> 12.0, macOS 10.11 -> 10.13. I don't think we can rely on that, so we should proceed as if Metal doesn't have multiple viewport/scissors.

> Note that I propose to use uint32 for scissor rect, but D3D12 uses long for all parameters in scissor rect, and Vulkan uses int32 for x and y parameters. However, a negative value makes no sense here. So I propose to use uint32 to simplify it, just as Metal does.

I agree that it doesn't make sense to provide negative scissors, but it's also harmless. There would still be ways to screw up the scissor rect, e.g. by having the right < left. The user would typically compute a scissor rect in some computation, which likely involves integers and floats, so if we accept `u32` there we'd force the user to cast the result, or face a conversion of int -> uint somewhere. I don't know how WebIDL would handle it, I hope it's not overflowing like C does. With this in mind, I'm slightly in favor of having the scissor rect specified in signed integers.

**Comment by Kangz** [comment] 2018-11-20 14:58
Proposal LGTM. Since we're talking about more spec-like details, we need to figure out what to do with empty scissor rects as they don't work on Metal (with have a Dawn test that fails because of it).

**Comment by Kangz** [comment] 2018-11-20 17:05
Can you explain what the mistake is?

**Comment by magcius** [comment] 2018-11-20 17:21
Vulkan tried to flip everything and accidentally used a right-handed NDC with the origin at top-left. All other APIs and platforms use an NDC with the origin at the bottom left. VK_KHR_maintenance1 supports flipping viewport by setting a negative height. Beyond that all you have to do is flip the winding order. However, the screen position semantic in a pixel shader might be a bit weird.

**Comment by Richard-Yunchao** [comment] 2018-11-26 06:37
Thanks a lot for your detailed review about this, @kvark . 

> Great stuff, @Richard-Yunchao , thank you!
> 
> There is one aspect seemingly missing from the investigation: how does depth clipping/clamping work?
> 
> * is output depth clipped to [0, 1] or clamped?
> * is the final range [0, 1] or [-1, 1]
> * is the viewport depth range applied before or after that clipping/clamping?
The output depth is clipped to [0, 1], and the final range is also [0, 1]. And 0 and 1 is the default values for minDepth and maxDepth respectively in native APIs. And the viewport transformation is right before rasterization, it is before that clipping/clamping/culling. Please correct me if this is incorrect. 
> 
> I'm sure we mostly know the answers here, but let's make this clear in the document.
> 
> > Metal, D3D12 and Vulkan can support multiple viewports and multiple scissor rectangles.
> 
> Note that Metal's support for multiple rectangles requires a much higher baseline for OS/HW: iOS 8.0 -> 12.0, macOS 10.11 -> 10.13. I don't think we can rely on that, so we should proceed as if Metal doesn't have multiple viewport/scissors.
Good to know this. And multiple viewports and scissor rects are also an **optional** feature in Vulkan.
> 
> > Note that I propose to use uint32 for scissor rect, but D3D12 uses long for all parameters in scissor rect, and Vulkan uses int32 for x and y parameters. However, a negative value makes no sense here. So I propose to use uint32 to simplify it, just as Metal does.
> 
> I agree that it doesn't make sense to provide negative scissors, but it's also harmless. There would still be ways to screw up the scissor rect, e.g. by having the right < left. The user would typically compute a scissor rect in some computation, which likely involves integers and floats, so if we accept `u32` there we'd force the user to cast the result, or face a conversion of int -> uint somewhere. I don't know how WebIDL would handle it, I hope it's not overflowing like C does. With this in mind, I'm slightly in favor of having the scissor rect specified in signed integers. 
The problem is that if we use a int for parameters for scissor rect, what shall we do for Metal if developers have negative values (negative x or y)? Metal only support uint. If we clamp to 0, I think we should use uint directly for web idl. 

When we use uint like what I proposed here, we need to do a uint -> int conversion for Vulkan/D3D, but we rarely have the overflow problem, because the parameters should be not that big. For example, the maximum value of the minimum viewport size on one dimension (and texture size on one dimension, and framebuffer size on one dimension) is 4096 in Vulkan, which is much less than the value that might overflow (2^31 or greater). Even if some hardware can support a greater size, it is still much less than 2^31. So a big value for scissor test makes no sense. It is safe enough to clamp one dimension of the scissor rect to 2^31 -1 when we convert uint to int if we don't report an error for such a big value. 

BTW, we can't make the right < left for scissor rect in Metal and Vulkan, because both of them use (x, y, width, height) for scissor rect and width/height are uint in Metal/Vulkan. We can only make right < left in D3D12.

**Comment by Richard-Yunchao** [comment] 2018-11-26 06:42
Thanks a lot for your detailed review about this, @kvark .
> Great stuff, @Richard-Yunchao , thank you!
> 
> There is one aspect seemingly missing from the investigation: how does depth clipping/clamping work?
> 
> * is output depth clipped to [0, 1] or clamped?
> * is the final range [0, 1] or [-1, 1]
> * is the viewport depth range applied before or after that clipping/clamping?
> 
> I'm sure we mostly know the answers here, but let's make this clear in the document.

The output depth is clipped to [0, 1], and the final range is also [0, 1]. And 0 and 1 is the default values for minDepth and maxDepth respectively in native APIs. And the viewport transformation is right before rasterization, it is before that clipping/clamping/culling. Please correct me if this is incorrect.
> 
> > Metal, D3D12 and Vulkan can support multiple viewports and multiple scissor rectangles.
> 
> Note that Metal's support for multiple rectangles requires a much higher baseline for OS/HW: iOS 8.0 -> 12.0, macOS 10.11 -> 10.13. I don't think we can rely on that, so we should proceed as if Metal doesn't have multiple viewport/scissors.

Good to know this.
> 
> > Note that I propose to use uint32 for scissor rect, but D3D12 uses long for all parameters in scissor rect, and Vulkan uses int32 for x and y parameters. However, a negative value makes no sense here. So I propose to use uint32 to simplify it, just as Metal does.
> 
> I agree that it doesn't make sense to provide negative scissors, but it's also harmless. There would still be ways to screw up the scissor rect, e.g. by having the right < left. The user would typically compute a scissor rect in some computation, which likely involves integers and floats, so if we accept `u32` there we'd force the user to cast the result, or face a conversion of int -> uint somewhere. I don't know how WebIDL would handle it, I hope it's not overflowing like C does. With this in mind, I'm slightly in favor of having the scissor rect specified in signed integers.

The problem is that if we use a int for parameters for scissor rect, what shall we do for Metal if developers have negative values (negative x or y)? Metal only support uint. If we clamp to 0, I think it's better to use uint directly for web idl.

When we use uint like what I proposed here, we need to do a uint -> int conversion for Vulkan/D3D, but we rarely have the overflow problem, because the parameters should be not that big. For example, the maximum value of the minimum viewport size on one dimension (and texture size on one dimension, and framebuffer size on one dimension) is 4096 in Vulkan, which is much less than the value that might overflow (2^31 or greater). Even if some hardware can support a greater size, it is still much less than 2^31. So a big value for scissor test makes no sense. It is safe enough to clamp one dimension of the scissor rect to 2^31 -1 when we convert uint to int if we don't report an error for such a big value.

BTW, we can't make the right < left for scissor rect in Metal and Vulkan, because both of them use (x, y, width, height) for scissor rect and width/height are uint in Metal/Vulkan. We can only make right < left in D3D12.

**Comment by Richard-Yunchao** [comment] 2018-11-26 06:55
> Proposal LGTM. Since we're talking about more spec-like details, we need to figure out what to do with empty scissor rects as they don't work on Metal (with have a Dawn test that fails because of it).

What do you mean empty scissor rects? @Kangz . Do you mean that we don't set scissor rect at all? This remind me that what will happen if developers don't call setViewport() or setScissorRect() at all before drawing. I think we might need to say that we will set the viewport size to default framebuffer/rendertarget size if developers don't set viewport size explicitly. And we will set the scissor rect as the same of the viewport rectangle if developers don't set scissor rect. 

If empty scissor rect means that (x, y, width, height) is (x, y, 0, 0), I think the graphics APIs should handle this situation. If the graphics API can't handle it, we need to report an error and skip such a test temporarily.

**Comment by Kangz** [comment] 2018-11-26 12:00
@Richard-Yunchao the default you provided sounds good. By empty scissor rect I meant the latter. If you look in Dawn's ScissorTests you can see that we have a suppression on Metal because it doesn't support (x, y, 0, 0) correctly.

**Comment by kvark** [comment] 2018-11-28 03:31
@Richard-Yunchao I don't think it's a bug, given that Metal validation specifically detects and compains about this:
> [MTLDebugRenderCommandEncoder setScissorRect:]:2564: failed assertion `rect.height(0) must be non-zero'

**Comment by Richard-Yunchao** [comment] 2018-11-28 07:56
@kvark , good point. I don't think there is a particular rendering scenario in which an empty scissor rect is a must. So let's explicitly say that the usage of empty scissor rect is disallowed. Otherwise, we will report an error just like what Metal does.

**Comment by Richard-Yunchao** [comment] 2018-11-28 13:30
It seems that both Metal developer document and D3D12 document on MSDN don't have error section for each function like Vulkan spec. So I don't know invalid values for each parameter. For example, Metal requires that width and height of scissor rect must be greater than 0 according to the error reported by Metal driver, but Metal document doesn't say that at [setScissorRect](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515583-setscissorrect?language=objc). Do I miss some documents? And you do have such documents for Metal (@grorg and @litherum ) and D3D12 (@RafaelCintron ) like Vulkan spec?

**Comment by kvark** [comment] 2018-11-28 14:41
@Richard-Yunchao for all I know, Metal validation layer is the best specification :P
As for D3D, it has a document for IHV implementors that describes the expected behavior in greater detail, but unfortunately it's not exposed to public, AFAIK.

**Comment by kvark** [comment] 2018-11-28 15:04
@Richard-Yunchao also,

> The viewport transformation is right before rasterization. It is after clipping/clamping/culling. Please correct me if this is incorrect.

Say I'm specifying the depth range to be [-10, 10] in the viewport. Vertices produce depth = 0.0, it's getting clipped/clamped, and then gets mapped to -10 according to my specified range. How does -10 get written to the depth buffer? Is there another clipping/clamping stage after the viewport mapping?

My understanding was that the depth clip/clamp happens after the viewport transformation.

**Comment by magcius** [comment] 2018-11-28 16:42
You misunderstand the depth range parameter. The [-10, 10] value is the expected depth range of z, post-projection. So your "0" value would get transformed by the viewport transformation to 0.5 (or 0x7FFFFF or whatever space you want to be in), which is then written to the depth buffer.

**Comment by kvark** [comment] 2018-11-28 17:30
Yes, I was talking about the min/max depth in the viewport. And you are correct, it's guaranteed to be in 0-1 range in at least D3D12 and Metal, so my concern is not valid. Consider me corrected ;)

**Comment by Richard-Yunchao** [comment] 2018-11-29 03:17
@kvark , Thanks for your info. Per my understanding, Metal validation layer is just like Vulkan validation layer in its implementation. However, It is better to have a document and I can't find such a document. 

For the min/max depth in the viewport, Vulkan is also guaranteed to be in 0.0 to 1.0 (inclusive), like Metal and D3D12.

**Comment by CretaceousConstructor** [comment] 2020-12-28 06:21
@magcius But clipping happened right after a vertex is multiplied be projection matrix,and Minz and Maxz of viewPort are used to mapping depth value of vertex in NDC space from [0,1] to [Minz,Maxz] in Directx11.I just wonder why we need to do this?

**Comment by Kangz** [comment] 2021-09-02 12:42
Closing. The viewport and scissor APIs have been added, although there's still an open issue to figure out now that Metal relaxed the restrictions on the viewport #373

**Closed by Kangz** 2021-09-02 12:42 UTC
Labels: investigation
