### ISSUE TITLE
Task: Define the kill statement

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#676] opened 2020-04-01 03:45 UTC
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

We need to define the `kill` statement. In particular, we need to determine:

1. Which implementations keep killed invocations around for future group operations
2. What the performance cost is of polyfilling `kill` by _not_ killing the invocation, but instead just guarding future memory writes

**Comment by magcius** [comment] 2020-04-01 03:57
HLSL / DXIL: discard does *not* stop the current execution thread, but demotes to a helper invocation, as if the pixel was outside the rasterized 2x2 quad.
SPIR-V: OpKill stops the current execution thread. OpDemoteToHelperInvocation implemented DX-like behavior.
Metal / MSL: Unknown. As far as I can tell from reading the specification, this is unspec'd.

> What the performance cost is of polyfilling kill by not killing the invocation, but instead just guarding future memory writes

This is not as simple as first appears. `while (true) { kill; }` will terminate with a real Kill, but not by guarding future memory writes. Also note the implications on uniformity, especially with regard to derivatives. Helper invocations contribute to derivatives, but killed threads do not. If there are any killed threads, all derivatives are undefined.

**Comment by dneto0** [comment] 2020-04-02 12:54
Duplicate of #361

**Comment by dneto0** [comment] 2020-04-02 12:59
Another consideration for polyfilling:  You also have to guard against certain future reads, to avoid causing either out of bounds accesses, or data races.

**Comment by dneto0** [comment] 2020-04-02 13:09
Another wrinkle:

On some implementations, but not others, a killed invocation will terminate once all its mates in the quad are also in the killed state.  That's one way to get termination in the case of `while (true) {kill;}`.

(FYI. The Vulkan description of demote-to-helper is at https://github.com/KhronosGroup/Vulkan-Docs/blob/master/appendices/VK_EXT_shader_demote_to_helper_invocation.txt#L14 or https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_shader_demote_to_helper_invocation)

**Comment by kvark** [comment] 2020-04-02 21:55
@litherum 
> instead just guarding future memory writes

Not sure I understand how this would work, could you elaborate?
If a pipeline is supposed to produce an output color, for example, the fragment shader can't "guard the writes" unless it's really discarded/killed.

**Comment by litherum** [comment] 2020-04-03 20:33
> could you elaborate

The `kill` could be emulated by sinking it to the end of the entry point (for all such points).

**Comment by litherum** [comment] 2020-04-06 20:58
I wonder if the difference between the two models of `kill` are actually observable or not. Presumably `kill` would introduce a non-uniform control flow everywhere after the `kill`, which means derivatives/barriers/etc. would be illegal. So maybe the implementation of `kill` can be simple and not have to do any polyfilling.

**Comment by magcius** [comment] 2020-04-06 22:20
As I said previously, `while (true) { kill; }` is an observable difference in the two models.

**Comment by grorg** [comment] 2020-06-23 12:13
Closed as duplicate of #361

**Closed** 2020-06-23 12:19 UTC
Labels: wgsl
