### ISSUE TITLE
Canvas contents after device destroy or device loss

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4859] opened 2024-09-09 20:14 UTC
Previously discussed on #4294; please see there for discussion. Filing new issue to talk about canvas specifically, including non-destroy device loss too.

The key scenarios:
- Render, device loss, present
- Render, destroy, present
- Render, present, device loss
- Render, present, destroy

Some key points:
- Destroy impacts only a single device, whereas device loss is usually caused by something that impacts the whole GPU process and therefore would lose all of the canvases anyway
- Showing partial frames (due to device loss mid frame) is not good
- Some implementations may store the canvas data "inside" the device and so would need to copy it out in order to preserve it
- Destroy() is generally useful for cleaning things up, and it's reasonable to want to clean up when canvas rendering is done.
  - However various future conditions could cause that canvas's contents to be lost anyway, and in this case there would be no signal to re-render (since the device is already lost and it can't get another loss notification - we'd need some event on the _canvas_ saying its contents were lost).

Overall I think this points toward both device loss and device destroy clearing the canvas, at the expense of key point 4. (This is a change and would necessitate changing some existing reftests.)

**Comment by mwyrzykowski** [comment] 2024-09-09 20:20
It seems like there is some benefit to allowing preserving canvas contents after `GPUDevice.destroy`

This is especially important on mobile devices where memory is limited, the site / app may want to call `destroy()` to free up resources but expect the canvas contents to be preserved.

It would be great if the fourth point, `Render, present, destroy` preserved the canvas contents. And potentially, the second point too: `Render, destroy, present`

Could we consider the following?

* destroy -> preserve canvas contents
* device lost -> canvas cleared

If a device lost occurs during a call to destroy then the device lost scenario applies (canvas cleared)

**Comment by kainino0x** [comment] 2024-09-10 00:00
FWIW, here's a test of this scenario in WebGL, using WEBGL_lose_context to lose the context several seconds after displaying a frame: https://codepen.io/kainino0x/pen/rNEPoNw
Firefox: Canvas is immediately cleared
Chrome: Canvas is immediately replaced with "sad canvas" icon
Safari: Canvas is not cleared immediately but it disappears when the canvas gets re-composited (e.g. resizing the window)

@toji pointed out to me during the editors' call that there _is_ an explicit way of keeping canvas results around: just pull them out of the canvas:
- Render to `OffscreenCanvas` then `transferToImageBitmap()`, then display the image with `transferFromImageBitmap()`.
- Or similarly, use `toBlob()` or similar to copy the image to the CPU, and use that via `<img>` (this is reasonable since it's a one-time operation).

**Comment by toji** [comment] 2024-09-10 00:02
I brought up that same basic scenario on the call, which was a kind of "one shot" render where the device is spun up, a frame is rendered, and then the device is destroyed for memory purposes while the rendered image is left behind. We do have a mechanism for that: ImageBitmaps. It's a bit clunkier, but at least it's guaranteed to work all the time and won't be dependent on internal compositor structure.

**Comment by kainino0x** [comment] 2024-09-10 00:46
Oh, and as for making the breaking change in Chromium - it's unlikely anyone depends on this, but we can at least warn if a canvas with a destroyed device gets displayed, or something like that (and suggest how to avoid it: either unconfigure the canvas before destroying, or use one of the methods above for one-shot rendering).

TBD whether Chromium would use the "sad canvas" in this case. (It definitely would if simulating a real device loss, #4177).

**Comment by mwyrzykowski** [comment] 2024-09-11 19:00
Seems reasonable to me. That would also allow us to purge the IOSurfaces associated with the device upon destroy, which is arguably better for memory as maybe the website does not need the contents

**Comment by kainino0x** [comment] 2024-09-11 19:48
Resolved in the meeting, but the change will be a bit complex so I'll put up the PR for closer inspection before landing.

**Comment by kainino0x** [comment] 2024-09-17 04:45
OK, after refreshing myself on how the spec works, there are still several options to pick from. The specific thing that makes this complicated is that there are two ways the canvas contents are read: by displaying on the screen (call this "display"), or by using as an image source, e.g. `canvas2d.drawImage(webgpuCanvas)` (call this "drawImage"). In the spec today both go via the `get a copy of the image contents of a context` algorithm.

Here, I'll use "backbuffer" and "frontbuffer" as loose terms for the two images this requires us to maintain. (The current spec has just one, `[[drawingBuffer]]`, which `getCurrentTexture()` returns a view into. The change we want to make requires there to be two.) Where I say "clear alpha" I mean "clear alpha if the canvas is configured to be opaque".

Options - some of these are very reminiscent of options I came up with earlier in the design process for canvas presentation:

0. Clear the canvas when the device is lost.
1. Getting the image contents via either "display" or "drawImage" copies the backbuffer into the frontbuffer, clears alpha, then returns the frontbuffer.
   - This is a no-go because it can't be described without an _actual copy_ - we would need to maintain a copy of the most recently returned image contents just in case the device is lost between then and the time the canvas is presented, to avoid displaying mid-frame results.
2. Have "drawImage" not work anymore (return a blank image) after the device is lost, even though the canvas is still displaying the old image.
    - Implementation: Make the backbuffer nullable. "Display" returns the frontbuffer; "drawImage" returns the backbuffer, or a blank image if there is none or the device is lost.
      Presentation (before "display") moves the backbuffer into the frontbuffer and clears alpha.
    - This is inconsistent with the HTML spec's treatment of a canvas as having just a single image, and I don't think it can technically be specced without changes to HTML. (I think a previous version of our spec tried to describe this behavior, or something similar.)
3. Allow "drawImage" to observe the contents reverting - it gets the backbuffer, but then if the device is lost, it reverts to the old frontbuffer.
    - Implementation: Make the backbuffer nullable. Have "get the image contents" return the backbuffer if there is one and the device is not lost, and the frontbuffer otherwise.
      Presentation (before "display") moves the backbuffer into the frontbuffer and clears alpha.
    - Thus, "display" always returns the frontbuffer because there is never a backbuffer (either there wasn't one, or it just got moved into the frontbuffer), and "drawImage" returns the backbuffer _if_ one has been created for the current frame _and_ the device is not lost.

I think I like (3) best. I previously tried pretty hard to avoid that kind of "revert" behavior being observable, but since this new change intentionally introduces a revert, it makes some sense if it's observable.

**Comment by kainino0x** [comment] 2024-09-17 05:09
With 3, there is also a secondary decision:

- 3a. destroying the current texture just terminates write access to the texture - current behavior.
- 3b. destroying the current texture cancels the presentation, similar to device loss but temporary.

We discussed this one previously too and avoided 3b to avoid needing multiple images in flight at once. But if we want the behavior we discussed, we need multiple images anyway. 3b is a bit more natural because it allows us to make `[[currentTexture]]` a regular normal `GPUTexture` instead of today's handwavy "createTexture()... except with the GPUTexture's underlying storage pointing to [[drawingBuffer]]".

**Comment by Kangz** [comment] 2024-09-17 14:02
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-09-11#m0-canvas-contents-after-device-destroy-or-device-loss-4859">GPU Web WG 2024-09-11 Atlantic-time</a></summary>

* KN: going in same direction as last meeting. Good argument that we shouldn't make implementations keep canvases alive after the device is lost or destroyed. There's a way to manually save rendered results - ImageBitmap, etc. Proposal - change spec. When device is lost, change how the canvas is displayed.
* KG: A concrete usecase for device loss preserving data is when we kill devices in long-idle background tabs, or when we hit some global limits and want to free up space from (long-?)idle devices. In this case, the least disruptive thing for a user is showing the same canvas contents that the tab had when it was last active. Making some attempt at the browser level to preserve it. There's some desire for device destroy to behave the same as device loss, esp. for testing. If we want device destroy == device loss, want the same behavior. There are other details. Long-idle background device isn't mid-frame in rendering.
* KN: that's a good point. I was looking for reasons we'd need to support one device being lost naturally.
* BJ: in that case where you have something collected for memory reasons on long-backgrounded tab. Regardless, when you go back to the page it'll be broken. You might see the preserved image but it'll be broken - non-interactive. If developer wants to avoid that they need to handle context loss, and if they do, the page will behave correctly. I'd rather the page show blank canvas / sad canvas rather than something that looks at the surface level like it's working, but actually isn't. Sounds like we'll get bug reports like "mouse interaction's broken on this page" when in reality the device was lost.
* KN: yes, think apps should handle that, and they have a way to.
* JB: if tab's navigated away from, it stops getting rAFs. Foregrounded, it starts getting them again. so if it's foregrounded it can recover. Or if user starts interacting, it'll get the device loss callback. Not clear to me that killing the device results in broken pages when you come back to them.
* CW: here it sounds like we're only talking about losing / destroying the device after rAF. Can we agree on what happens if you destroy the device before rAF? Is that valid?
* KN: 2 options. 1) goes blank 2) never display the frame. Discard that frame, keep the old one.
* JB: in Moz's discussions, prefer to retain frame N-1. Brandon brought up in discussions that that'd constrain implementations. If we decide the behavior’s valuable, we prefer to constrain impls.
* BJ: Chrome and maybe Moz supply textures for the canvas from outside the WebGPU device. So when device goes away the texture isn't destroyed. Could say that all browsers have to do that - and good likelihood that they already are. But is this an impl detail we want to force on WebGPU implementers?
* JB: we're suggesting exactly that.
* MW: initially Safari was along the opinion of preserving contents. But allowing contents to be cleared has a benefit - device loss due to memory pressure, can also deallocate the backing store previously allocated. Depending on memory pressure severity, may need to do this to avoid the OS crashing the GPU sub-process.
* CW: this is if device is lost after rAF?
* MW: can happen at any time
* KN: relevant either way
* JB: all we're talking about is "should" vs. "must" language.
* CW: could spec what happens on device destroy. Not device loss.
* JB: OOM seems more like device loss than device destroy.
* CW: how about - if before rAF ends, you destroy the device - previous contents are displayed, new content is never displayed. (MW: OK.) If device lost after rAF, try to do same thing as device destroy, just might not be able to.
* JB: this is a portable question.
* RF: I don't care too much what we spec about manually calling device.destroy(). When it does get removed for real, there's no preserving - the old state doesn't exist any more. Read back on periodic basis? Don't think we should.
* KG: that's why I think we should say "should" in the spec. This isn't "must" behavior. There are cases where I think we should help users along.
* CW: think we agree on the two sides. Just device destroy after rAF. Suggest - if you destroy the device after rAF, previous contents are shown. Consistent.
* KN: I like it.
* MW: thumbs up
* **Consensus: device destroy either during or after rAF causes previous canvas contents to be displayed.**

</details>

**Comment by kainino0x** [comment] 2024-09-18 21:39
Updated CTS issue to track this. https://github.com/gpuweb/cts/issues/3251

**Comment by Kangz** [comment] 2024-09-24 16:05
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-09-18#m0-canvas-contents-after-device-destroy-or-device-loss-4859">GPU Web WG 2024-09-18</a></summary>

* KN: last meeting we discussed this, said it'd be good if we had the canvas revert to the previous frame if the device is lost during a frame. Number of ways this can interact with looking at the canvas's contents as an image source (draw to 2D canvas, upload to WebGL). Wrote up 4 options. See the PR.
* 0) Don't do the reverting thing we talked about last time.
* 1) First doesn't work. Requires an actual copy.
* 2) Requires us to do stuff inconsistent with how HTML spec is written.
* 3) Doesn't have these problems but does allow drawImage to see the contents reverting. In-progress with a live device, vs. the device being lost. Think it's fine, but not a trivial choice.
* GT: are we talking about destruction or loss?
* KG / KN: both, but you didn't lose the GPU process, so you still have the texture.
* KG: more limited than loss, but trying to describe both with the same language.
* CW: we spec what device.destroy() should do, but we want this to be the same as best-effort device loss handling.
* GT: I'd say we're only defining destroyed, ignoring whether the user or the browser destroys it.
* KG: useful example of device loss - you have old contexts the browser decides to freeze or close to reduce memory pressure, like on an old tab.
* GT: right, but the browser actually destroys the context in this case.
* KG: w.r.t. the spec, that's device loss.
* CW: why is option (1) a no-go? Why does it require a copy?
* KN: in that one, when we need the contents of the canvas we commit whatever you're currently working on to the canvas. Those will be the next canvas contents. If you use drawImage in the middle of a frame, you need to see those rendering results. Need to preserve the drawing buffer. Can't move it to the front, because we might keep drawing. drawImage might happen in the middle of a frame.
* KG: sound weird, but having drawImage based on current contents but compositor displaying the last committed frame conceptually makes sense.
* CW: you're saying option 3 makes sense.
* KG: yes.
* CW: is option 1 tractable with the copies? User tries to do drawImage during a rAF. Make a copy? Seems it might happen often.
* KN: based on what Kelsey said, might be something between (3) and (1). You drawImage, so you captured it, we'll commit it, put it on the display even if you lose the device afterward.
* KG: calling drawImage from a WebGPU canvas doesn't mean that's the thing you want to show up on the page. Only guaranteed way to know this is for you to leave it that way and it presents it to the screen.
* CW: makes sense, but think some people might be tripped up by that. Seems no solution that's intuitive to developers in all cases and also easy to implement by browsers.
* RC: talked about this being best-effort. Is it OK for the browser to be an under-achiever? #0, in the case where you share one context across WebGPU, canvases, etc.?
* GT: do feel there's usefulness in talking about 3 cases rather than 2. Not just destroyed and lost. Lost that the browser destroyed, lost that the user destroyed. Other thing - don't understand #3 from the user's POV. Draw B and let it get to the screen. Draw A, call drawImage, destroy, call drawImage (missed some of this) - you'll get A in first drawImage and B in second.
* KG: caution against having an M0 issue that we want fixed right now, and issues depending on it in M0. WebGL doesn't spec this that well. Don't think this is a release criterion for our spec.
* KN: would like the normal-case behavior to be well spec'd, because we have destroy(). But wasn't going to spec what happens if GPU process crashes, or GPU is unplugged.
* (agreement)
* CW: on Gregg's case - draw B, then draw A, getImage, destroy, getImage. One getImage gets A, the other B. You resort to grabbing the front buffer. Pretty surprising. Sort of a corner case. Way to handle this - getImage takes a snapshot for the use of getImage. At end of rAF, if device is alive, put back buffer in front buffer, but getImage has its own special snapshot buffer.
* KN: think this is option #2.
* KR: What had so many issues in WebGL backbuffer management in Chromium, the user destroy the device, let's simplify things and give them a blank image. Thinking about how this logic was in WebGL was extremely hard, worry about the complexity in WebGPU.
* KG: The spec for device loss will be a SHOULD instead of a MUST so that's allowed behavior.
* KN: We still have to spec how images are handled. I'm OK with option #0.
* KG: I'm advocating for latitude in UAs implementing this. How much do we think it should be required that the canvas is cleared? If we don't think it MUST be cleared then we can leave it to the UA.
* KN: we're then allowing UAs to have 1 of 2 behaviors and we need to test them. We have existing tests, have to update them.
* KG: cautioning against spec'ing something because we should. Downside of not testing this is low. "Should" we be nice?
* KR: advocating again for the simplest solution. Perry Wang from Tencent *just* contributed a fix to WebGL's back buffer to *correctly* clear it, and this caused a regression bug to be filed.
    * [Regression: Gaming Extension page getting blanked after open and close sidepanel](crbug.com/350994518)
    * [Resizing WebGL canvas does not always reset its displayed image](crbug.com/41494959)
* CW: Option 3 seems implementable at least in Chromium.
* KN: Think so too, not that different from what we implement now.
* KN: I'd do what Kelsey proposes for M0 (allow either clearing or preserving the canvas) and keep a bug open for M1.
* CW: that works.
* **Resolved**
* 
* 

</details>

**Closed** 2024-09-30 21:51 UTC
Labels: api resolved, api
