### ISSUE TITLE
Query API: What is the GPU timestamp unit on Metal?

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#1325] opened 2020-12-24 07:51 UTC
The [documentation](https://developer.apple.com/documentation/metal/mtlcounterresulttimestamp/3081724-timestamp) for `[MTLCounterResultTimestamp timestamp]` says it's "A timestamp.", but does not specify its unit.

When this feature was first supported in macOS 10.15, I saw there was a message said the timestamp is in nanoseconds if we printed the `[MTLCounterResultTimestamp timestamp]` in XCode, in the latest macOS, the message is gone. I suppose it's still in nanoseconds but it doesn't match with the perf I'm seeing (expect close to 48ms but get 0.8ms). 

I think Metal should have a factor to declare how much time passes for a timestamp value to be incremented by 1 like [Vulkan](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#limits-timestampPeriod) and [D3D12](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandqueue-gettimestampfrequency). Unfortunately, nowhere in the documentation does this. 

I did some searching about Metal GPU timers, someone also encountered the same problem and gave a solution at [here](https://feresignum.com/resolving-metal-gpu-timers/). To put it simply, call `[MTLDevice sampleTimestamps:gpuTimestamp:]`  twice to sample the timestamps from both the CPU and GPU, in order to derive the GPU timestamp period calibrated against the CPU period. Because CPU timestamps are also in *some* unit, we also need to use `mach_timebase_info()` to get the factor to convert to nanoseconds. Example code:
```
MTLTimestamp m_cpu_timestamp, m_gpu_timestamp;
MTLTimestamp cpu_timestamp, gpu_timestamp;
double m_gpu_cpu_timestamp_factor;

[m_device sampleTimestamps:&m_cpu_timestamp gpuTimestamp:&m_gpu_timestamp];
[m_device sampleTimestamps:&cpu_timestamp gpuTimestamp:&gpu_timestamp];

if(cpu_timestamp > m_cpu_timestamp && gpu_timestamp > m_gpu_timestamp)
{
    const double cpu_delta = cpu_timestamp - m_cpu_timestamp;
    const double gpu_delta = gpu_timestamp - m_gpu_timestamp;
        
    m_gpu_cpu_timestamp_factor = cpu_delta / gpu_delta;
}
```

 Assuming that `begin` and `end` are the timestamps retrieved from `[MTLCounterSampleBuffer resolveCounterRange:]`
```
const uint64_t delta = (end - begin) * m_gpu_cpu_timestamp_factor;

mach_timebase_info_data_t time_info;
mach_timebase_info(&time_info);

const uint64_t nanoseconds = delta * time_info.numer / time_info.denom;
```

The `m_gpu_cpu_timestamp_factor` is in the range of 51.978622 to 52.294118, the `time_info.numer` and `time_info.denom` are 1 on my device. Using the above perf data , the 0.8 * `m_gpu_cpu_timestamp_factor  * time_info.numer  /  time_info.denom` is about 42ms, close to the value we expected. 

Is this the correct way to resolve timestamps to nanoseconds? If not, what is the official one?

**Comment by kvark** [comment] 2021-01-04 19:55
@cwfitzgerald if we just say that GPU time stamps are on its own timeline, as you suggested on the Matrix (to avoid compute-based processing), then this issue is automatically solved :) After all, they shouldn't be compared to any absolute values. I.e. I think the only reasonable timestamp use cases are about comparing them with each other on different workflows (but the same adapter).

**Comment by kainino0x** [comment] 2021-01-05 23:42
> After all, they shouldn't be compared to any absolute values.

What if you want to compare your cpu frame time to your gpu frame time e.g. to look at your occupancy balance?

**Comment by Kangz** [comment] 2021-01-06 10:30
+1 to what @kainino0x, developers using timestamps want to be able to reason in terms of msec, so they can budget their frame. It's not just for seeing a number decreasing with optimizations.

**Comment by kvark** [comment] 2021-01-06 14:15
I don't think timestamps are a proper mechanism to reason about CPU/GPU occupancy. The latter are parallel machines, so there isn't "full" occupancy reflected by time, in general, and it's especially obvious with multiple queues in play.
I also do not doubt that developers want to know the Msec. Of course who wouldn't? But if we don't have a straightforward mechanism to give them Msec, why try to do the guesswork?

**Comment by potree** [comment] 2021-01-06 14:41
For benchmarking (e.g. to report results in publications) I'll need millisecond timestamps or durations.

**Comment by cwfitzgerald** [comment] 2021-01-06 14:51
If you can't resolve timestamp queries to a known unit (nanoseconds or whatever), we might as well not have them, they are of basically no use. I am very disappointed that metal provides no way to get this denominator without hacky testing.

This is an extension, so if we can't get the information we need from metal, I think it should just go unsupported. If metal gets around to making a proper API to get this timestamp, we can reconsider it.

**Comment by kvark** [comment] 2021-01-06 14:55
@potree 
For benchmarking you'd use `executionTime` promise that was added to command buffers in #870, it's available everywhere, 
doesn't require any features enabled.

Note: if the implementation is expected to implement them via actual timestamp queries then we have a problem - at command buffer time it's too late to insert those timestamp queries internally.

> If you can't resolve timestamp queries to a known unit (nanoseconds or whatever), we might as well not have them, as they are of basically no use.

I thought they'd still be useful: one can compare multiple code paths to see their relative performance, then pick a strategy. Notably, one can also use the `executionTime` I mentioned for this if done at initialization.

**Comment by Kangz** [comment] 2021-01-06 15:44
> Note: if the implementation is expected to implement them via actual timestamp queries then we have a problem - at command buffer time it's too late to insert those timestamp queries internally.

It isn't too late, you can introduce small command buffer before / after your main command buffer.

@kvark, I'm not sure I understand your concern with nanosecond timestamps, they seem pretty useful to break down what's inside a frame. You seem to not consider them useful for profiling, can you detail more why they aren't useful?

**Comment by kvark** [comment] 2021-01-06 16:25
> It isn't too late, you can introduce small command buffer before / after your main command buffer.

That's quite a sad way to approach this. Creating and encoding 2 extra command buffers just so the user can get the time? That's more of a hack than a proper solution.
I think it's reasonable for us to require that any operations that an implementation is expected to encode into command buffers have to be known while `GPUCommandEncoder` is active, not after that. As far as I know, that's how we rolled for years, and I don't see why those timestamps should be an exception.

**Comment by kvark** [comment] 2021-01-06 19:27
We talked about this 1:1 with @Kangz , clarified the differences between profiling and benchmarking, and how command-buffer GPU timing is useful versus the timestamps. Here are the facts we found:
  1. time stamps are in ticks on all platforms
  2. the "ticks per second" ratio is fixed on an adapter, it can be discovered on D3D12 and Vulkan but not Metal currently (as this issue states).
  3. we should probably make WebGPU to follow that - instead of exposing the time in MS, expose the ticks, and also expose the constant ratio to help users convert them into time. Running compute shaders over that, only to multiply by a scalar, seems like unnecessary work.

It's up to implementations to decide if they want to expose the extension on relevant Metal devices and do a guesswork on the scaling factors, or not expose it in the first place until Metal provides a mechanism to query the scaler.

**Comment by kainino0x** [comment] 2021-01-06 21:52
SGTM.

**Comment by cwfitzgerald** [comment] 2021-01-06 23:38
SGTM also

**Comment by haoxli** [comment] 2021-01-07 07:01
> time stamps are in ticks on all platforms

This is related to native APIs, they are ticks on D3D12,  but unclear units on Vulkan (just says it's an integer value generated by VkPhysicalDevice) and Metal (result from timestamp counter set), that's why we need the compute shader to unify them to same unit (NS). 

> the "ticks per second" ratio is fixed on an adapter, it can be discovered on D3D12 and Vulkan but not Metal currently (as this issue states).

Although we can get a same ratio, I'm not sure if they are really fixed. On Vulkan, we can query it from [`VkPhysicalDeviceLimits::timestampPeriod`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap42.html#limits-timestampPeriod) on **VkPhysicalDevice**, but on D3D12, it says we can query the GPU timestamp frequency on a **per-command queue basis**, whether that means the frequency may be different on different type of queues. Not sure what it will be on Metal, but should be similar.

Backend | Ratio | Query From | Timestamp (In NS) 
----------| -------| -------------|-------
D3D12 | frequency (HZ) |  command queue | timestamp * 10<sup>9</sup> / frequency 
Vulkan | period (NS) | device | timestamp * period
Metal | ? | ? | ?

If we expose timestamps and constant ratio, we cannot specify timestamps are exposed as ticks (may be timestamp counters on device? or whatever?) and the constant ratio should be a timestamp period which stand for the number of nanoseconds required for a timestamp query to be incremented by 1 (following Vulkan). 

Considering the support of multi-queue, the API of querying the timestamp period should be allocated on the queue (following D3D12).

**Comment by haoxli** [comment] 2021-01-07 07:57
I have a question here about Web API design, should we prefer ease of use or closer to native API?

Exposing both timestamps and period is more in line with native API for timestamp query, and save the calls of internal pipeline, make Dawn implementation easier and more efficient. This also makes it easier for native developers to write web applications. But we need more specifications to explain what the timestamps and period are and the timestamps should be converted by the period from the same queue (not sure whether more validations are needed). The API  design of getting timestamp period combine the APIs of D3D12 and Vulkan above, it may make Vulkan developer wonder why the period is obtained from the queue and D3D12 developer wonder why it's not frequency. 

In terms of ease of use, I prefer to expose the timestamps as nanoseconds like WebGL did (easy to port WebGL apps), timestamps and period cannot be used separately. 

For Metal backend, we can disabled the timestamp extension until the issue is fixed.

**Comment by Kangz** [comment] 2021-01-07 13:42
> we should probably make WebGPU to follow that - instead of exposing the time in MS, expose the ticks, and also expose the constant ratio to help users convert them into time. Running compute shaders over that, only to multiply by a scalar, seems like unnecessary work.

I don't really have an opinion there, either doing the conversion on the GPU for developer simplicity, or exposing the timestamp period somewhere seems ok.

**Comment by cwfitzgerald** [comment] 2021-01-07 15:37
> This is related to native APIs, they are ticks on D3D12, but unclear units on Vulkan (just says it's an integer value generated by VkPhysicalDevice) and Metal (result from timestamp counter set), that's why we need the compute shader to unify them to same unit (NS).

To me, "ticks" means however often the internal clock moves forward, so all of the apis work in some abstract "tick" unit.

> Considering the support of multi-queue, the API of querying the timestamp period should be allocated on the queue (following D3D12).

I would be very interested in finding out if this value is ever actually different between queues on any real hardware.

I am very strongly for exposing the timestamp period on the cpu and letting the user deal with it on their side. We can warn in the spec and API documentation that the value must be multiplied by the timestamp period. IMO it's a very minor inconvenience when most people are just going to be reading them back on the cpu anyway, we avoid extra gpu work.

On freq vs period, they are just reciprocals of each other, so I'm indifferent.

**Comment by kvark** [comment] 2021-01-07 16:42
I reached out to DX12 discord again with the question about per-queue difference in tick/time ratio. The answer is that all the queues except for a video queue are expected to have the same ratio. So maybe we don't need to expose it on a per-queue basis.

**Comment by haoxli** [comment] 2021-01-08 07:38
@kvark thanks for your information.  The video queue shouldn't support timestamps, I see the [D3D12 spec](https://docs.microsoft.com/en-us/windows/win32/direct3d12/timing) says the direct and compute queues always timestamps, copy queue optionally supports timestamps if the `D3D12_FEATURE_DATA_D3D12_OPTIONS3::CopyQueueTimestampQueriesSupported` is true.

Then can we agree on the following points:
- Expose the timestamp **period**. The reason for using period instead of frequency is that period is better understood and described, and on D3D12, to convert timestamps to time (in nanoseconds), `10<sup>9</sup> / frequency` is a fixed factor, so I think exposing period is more reasonable.
- The period query method should be on **device level** (how about `GetTimestampPeriod`?). 
- The period is returned as 1.0f if the timestamp extension is not supported. `ID3D12CommandQueue::GetTimestampFrequency` return FAIL if the queue does not supports timestamps. On Vulkan, the `timestampPeriod` is a limit on device, its [limit type](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap42.html#limits-minmax) should be duration, and if a feature is supported, the limits reported are the same whether or not the feature is enabled.

**Comment by Kangz** [comment] 2021-01-08 12:10
> The period query method should be on device level (how about GetTimestampPeriod?).

What about having it in the adapter's limits object (or close to it?) the timestamp period is really a property of the adapter, not something that can change per-device. It could not be present if the timestamp extension is not available on that adapter.

**Comment by kvark** [comment] 2021-01-08 15:22
It's rather interesting that some of the queues may support the timestamp and others will not. Since it's an extension already, maybe it should be shaped in a way that allows some queues to not have support for it? And if we go this route, we might as well have the period per queue.

**Comment by cwfitzgerald** [comment] 2021-01-08 15:39
Considering what we now know about all the queues using the same timestamp, I would also be quite surprised if some queues supported timestamp queries and some didn't. Vulkan has a boolean that says "do all compute and graphics queues support timestamp queries" which we could gate this feature on.

**Comment by kvark** [comment] 2021-01-08 15:44
Yet, Vulkan supports timestamps on transfer queues more often than on compute/graphics, right? And on D3D12 there is this "CopyQueueTimestampQueriesSupported" flag, which implies the opposite - that copy queues less often support timestamps... It's weird! I'm just thinking that it would be sad to report no timestamps on D3D12 backend if it's only the copy queues that can't get them.

**Comment by cwfitzgerald** [comment] 2021-01-08 15:47
Man, timestamp queries are weird. It's bizzare to me just how much the apis disagree on this front. I definitely agree though, D3D12 should have queries even if the copy queues don't support it. Then maybe it should be a queue method.

**Comment by haoxli** [comment] 2021-01-11 09:07
For the queues not support timestamp query, we cannot write timestamps on them,  all timestamps need to be converted should be queried from the queues support timestamp query. And on D3d12, the frequency is same on different queues (except for video queue), so I think the ratio can be a fixed value for same device or adapter.

@Kangz  It seems that there are different opinions on where to obtain the period, could you have a discussion for this on WebGPU meeting?

**Comment by kainino0x** [comment] 2021-01-11 20:50
Meeting: @litherum to get more info about the Metal issue.

**Comment by litherum** [comment] 2021-01-14 19:00
Alright, here's how it works in Metal.

Using [MTLCommonCounter.timestamp](https://developer.apple.com/documentation/metal/mtlcommoncounter/3081696-timestamp) writes an arbitrary, device-specific value. On Apple GPUs, it's nanoseconds, but on other GPUs, it doesn't have to be.

If you want to convert that into something with proper units, you have to call [`MTLDevice.sampleTimestamps()`](https://developer.apple.com/documentation/metal/mtldevice/3650248-sampletimestamps) twice. This function associates an arbitrary point in GPU time with an arbitrary point in CPU time. If you call this function twice, you can compute a linear regression to correlate GPU values to CPU values. (Aside: `MTLDevice.sampleTimestamps()` has an unfortunate signature - the `gpu` output value should not have been a `MTLTimestamp`, but instead should have been the same type as [`MTLCounterResultTimestamp.timestamp`](https://developer.apple.com/documentation/metal/mtlcounterresulttimestamp/3081724-timestamp).)

**Comment by haoxli** [comment] 2021-01-15 16:25
Thank you! @litherum.

[MTLDevice.sampleTimestamps()](https://developer.apple.com/documentation/metal/mtldevice/3650248-sampletimestamps) is supported from macOS 11.0+, should we use [MTLDevice sampleTimestamps:gpuTimestamp:](https://developer.apple.com/documentation/metal/mtldevice/3194378-sampletimestamps?language=occ) which supported from macOS 10.15+ and use [mach_timebase_info()](https://developer.apple.com/documentation/driverkit/3433733-mach_timebase_info?language=occ) to convert (cpu_timestamp_delta/gpu_timestamp_delta) to nanoseconds? It seems that the cpu timestamp is in tick units.

I used ` [MTLDevice sampleTimestamps:gpuTimestamp:]` to take 5 sets of test data (2 times for each set)  on Intel and AMD devices respectively:

Intel UHD 630

Set | cpuTimestamp1 |  gpuTimestamp1 | cpuTimestamp2 | gpuTimestamp2 | cpuDelta | gpuDelta | cpuDelta / gpuDelta
------|-------------------|--------------------|-------------------|-------------------|-----------|-----------|--------------------
1 | 6495125069 | 2629284785 | 6495135246 | 2629284907 |10177 | 122 | 83.418033
2 | 6511806067 | 2629484957 | 6511810727 | 2629485012 | 4660 | 55 | 84.727273
3 | 6577719601 | 2630275920 | 6577728809 | 2630276031 | 9208 | 111 | 82.954955
4 | 6594688492 | 2630479546 | 6594694530 | 2630479618 | 6038 | 72 | 83.861111
5 | 8427854252 | 2652477535 | 8427860541 | 2652477612 | 6289 | 77 | 81.675325

AMD Radeon Pro 555X 

Set | cpuTimestamp1 |  gpuTimestamp1 | cpuTimestamp2 | gpuTimestamp2 | cpuDelta | gpuDelta | cpuDelta / gpuDelta
------|-------------------|--------------------|-------------------|-------------------|-----------|-----------|--------------------
1 | 856666942140968 | 233796689480 | 856666942147645 | 233796696280 |6677 | 6800 | 0.981912
2 | 856666957002165 | 233811551160 | 856666957009643 | 233811557200 | 7478 | 6040 | 1.238079
3 | 856666973814103 | 233828361680 | 856666973819905 | 233828369080 | 5802| 7400 | 0.784054
4 | 856666990680678 | 233845228640 | 856666990686820 | 233845236160 | 6142 | 7520 | 0.816755
5 | 856667007767874 | 233862316560 | 856667007772565| 233862322160 | 4691| 5600 | 0.837679

`cpuDelta` = `cpuTimestamp2 ` - `cpuTimestamp1`, same to `gpuDelta `.

The average of five `cpuDelta/gpuDelta` on Intel is 83.327339, close to the 83.333 on  Vulkan and D3D12, and relatively stable. But on AMD, the average is 0.931695, larger error ratio than 1 on other backends. I'm not sure whether measure more times and average the results can reduce the error ratio, or should we derive the linear equation after testing multipe times?

**Comment by Kangz** [comment] 2021-01-18 09:34
Thanks @haoxli for the investigation! From your tests it seems fairly safe to assume 83.333 on Intel and 1 on AMD (and Apple GPUs given @litherum's comment). Since these numbers are mostly informational for developers, it's ok if they are not 100% correct on specific HW / OS versions imho.

**Comment by litherum** [comment] 2021-01-20 23:11
@Kangz

> assume 83.333 on Intel and 1 on AMD

This is not safe to assume in the general case.

@haoxli 

> [MTLDevice.sampleTimestamps()](https://developer.apple.com/documentation/metal/mtldevice/3650248-sampletimestamps) is supported from macOS 11.0+, should we use [MTLDevice sampleTimestamps:gpuTimestamp:](https://developer.apple.com/documentation/metal/mtldevice/3194378-sampletimestamps?language=occ)

These are the same function. The only difference is the Swift overlay changed. The Objective-C function is the same.

> should we use ... [mach_timebase_info()](https://developer.apple.com/documentation/driverkit/3433733-mach_timebase_info?language=occ) to convert (cpu_timestamp_delta/gpu_timestamp_delta) to nanoseconds?

This is how you convert CPU timestamps to nanoseconds, but not how you convert GPU timestamps to nanoseconds.

Another note: this "compute a linear regression" business is intended to be done throughout the lifetime of the application, on encoder boundaries. It's not intended to be done just once at application startup.

**Comment by haoxli** [comment] 2021-01-21 11:48
Thanks @litherum. The results collected after the application warms up are more linear (Intel: `83.327931`\~`83.337599`, AMD: `0.982987`\~`1.002036`), no matter whether they're collected on the same encoder. If it must be on encoder boundaries, we don't think we can expose it on adapter limits or queue, which will be more complex.

**Comment by litherum** [comment] 2021-01-25 04:23
Just to be clear - I don't think the WebGPU API should require web authors to compute linear regressions. The browser should handle all this business internally and expose an API that is much simpler.

Given that Metal's API requires calculating linear regressions on encoder boundaries throughout the lifetime of the application, I don't think we can expose a WebGPU API that is a simple tick count & tick rate. I think we have to expose nanoseconds instead.

**Comment by haoxli** [comment] 2021-01-25 09:20
> Given that Metal's API requires calculating linear regressions on encoder boundaries throughout the lifetime of the application

Does it mean we need to record the linear regressions for each query on encoder boundaries when writing queries?  So that we could get matched factor in the conversion if we can’t simply set it to a fixed value on each platforms.

**Comment by Kangz** [comment] 2021-01-25 10:56
> Just to be clear - I don't think the WebGPU API should require web authors to compute linear regressions. The browser should handle all this business internally and expose an API that is much simpler.

Isn't `GPUCommandBuffer.executionTime` the simpler API already? However there's a need to have more detailed information while developing WebGPU pages (for example TF.js uses timestamps to time each dispatch for their model to know what to optimize). Timestamp queries are an optional feature so it doesn't have to be present everywhere and could be available only on systems where the browser feels confident in giving a constant value for ticks. That's the case in D3D12, Vulkan and some Metal devices (and recent / future(?) Metal devices).

**Comment by Kangz** [comment] 2021-03-24 18:05
@litherum @kvark WDYT of Hao's suggestion to just use timestamps? After discussion with Chromium contributors (especially with Hao) we think we should just go with timestamps.

**Comment by kvark** [comment] 2021-03-24 19:54
@Kangz you mean the "nanosecond" timestamps specifically?

I believe the biggest downside of this is the need to run compute dispatches to convert the results. This is extra work, and it may negatively affect the results of the queries. We also haven't discussed in detail the exact way an efficient implementation is supposed to do this. Would it dispatch on `resolveQuerySet`? Or do a combined dispatch on `CommandEncoder::finish()`? Would it need to have a mask of which entries need to be converted, and which are left from the previous resolve? Etc.
This is a bit too hand-wavy at this point.

The compromise solution we haven't really discussed here could be to have an `Promise<ArrayBuffer> QuerySet::resolve(...)` method instead of relying on `CommandEncoder::resolveQuerySet` for timestamps. It would allow an implementation to do any necessary conversions on CPU side.

Being clear about these questions (details on compute dispatches, the option to do CPU-only path) would help with reaching consensus.

**Comment by haoxli** [comment] 2021-03-25 06:53
@kvark  Yes, the timestamps I suggested is the converted timestamps in nanosecond.

> This is extra work, and it may negatively affect the results of the queries.

It does require extra work, but it would not effect the correctness of the query results we simpled. Because the timestamps have been stored in query set when `writeTimestamp` is called. The logic of `resolveQuerySet` is to read the results of query set into destination buffer, here we have the original timestamps in buffer, then encode the compute dispatches to convert these timestamps to nanoseconds. It increases the post-processing time,  not the timestamp results.

> Would it dispatch on resolveQuerySet? Or do a combined dispatch on CommandEncoder::finish()?

I think it should dispatch on `resolveQuerySet`, but just encode the compute dispatch.

> Would it need to have a mask of which entries need to be converted, and which are left from the previous resolve?

There are two steps in `resolveQuerySet` for timestamps, first step is call native resolve methods (D3D12: `ResolveQueryData`, Vulkan: `vkCmdCopyQueryPoolResults`, Metal: `resolveCounters`) to read the timestamps to the destination buffer. The  `queryCount` and `destinationOffset` in `resolveQuerySet` determine which values will be written into the destination buffer, the previous resolved values will be overwritten. The second step is run compute dispatch to convert the resolved data in `[destinationOffset, destinationOffset  + queryCount * sizeof(uint64)]` in the destination buffer.

**Comment by haoxli** [comment] 2021-03-25 08:40
For the conversions on CPU side, the benefits I can think of are that no compute shader is needed, the timestamp calculated by u64 is more accurate (In compute sharder, u32 is used instead, there is a loss of accuracy of about 2 thousandth), timestamps are directly available on CPU side.

But only Vulkan supports to read timestamps to CPU by `vkGetQueryPoolResults` directly, on D3D12 and Metal, we also need to resolve the timestamps into the buffer, then read them back for conversions. And compared with GPU parallel computing, it may bring more overload to CPU when converting thousands of queries.

I have some questions here:
- Do we need keep the resolve path (without compute dispatch) on GPU if do the convertion on CPU side? 
- Does it allow to call `QuerySet::resolve()` in encoder and pass? The `QuerySet::resolve()` is resolved asynchronously, does it need to wait for `writeTimestamp` is completed? or just returned current values in QuerySet?

**Comment by Kangz** [comment] 2021-03-25 09:28
@kvark since you're curious, the logic for resolving with a compute shader can be found in [Dawn's QueryHelper.cpp](third_party/dawn/src/dawn_native/QueryHelper.cpp). It's only a couple hundred lines. IMHO it is ok to keep this as the only path, and not add a duplicate path to resolve on the CPU. It is a second path to do the same thing so it can be done post-MVP.

**Comment by kvark** [comment] 2021-03-25 14:08
@Kangz the link is broken, but it's ok.
Thank you @haoxli for explanation!
This sounds fine to me.

**Comment by Kangz** [comment] 2021-03-25 14:14
Fixed the link!

**Comment by haoxli** [comment] 2021-03-30 01:20
@kvark @Kangz can we move this forward and keep timestamps in nanoseconds in GPU side?

**Comment by Kangz** [comment] 2021-03-30 08:14
Seems like yes.

**Comment by Kangz** [comment] 2021-04-09 16:27
I think we have consensus here. Closing.

**Closed by Kangz** 2021-04-09 16:27 UTC
Labels: question
