### ISSUE TITLE
Rust-flavored syntax breaks interoperability with existing C and C++ code

### ISSUE THREAD

**Issue by jeremyong** [gpuweb/gpuweb#601] opened 2020-03-11 13:15 UTC
A common pattern in the industry is to mirror the definitions of structures, types, and even functions between C and shader code. Both GLSL *and* HLSL are amenable to this technique, and with macros or preprocessing, it's easy to extend the interoperability further to support reflection, automatic static descriptor/root-signature tables, and more.

I just wanted to mention this as a standalone callout in case it wasn't already considered.

**Comment by dj2** [comment] 2020-03-11 13:18
Duplicate of #593

**Closed by dj2** 2020-03-11 13:18 UTC
Labels: wgsl

**Comment by jeremyong** [comment] 2020-03-11 13:20
Is it? I saw that issue but expected that this was an entirely separate matter worth considering. Are the plans to support reflection or interoperability through other means? @dj2

**Comment by dj2** [comment] 2020-03-11 13:25
Reading the title and description, this sounds like it's specifically talking about the `struct` syntax and the types on the right, which seems like a duplicate of the other issue.

Is that not what this issue is about? What do you mean by interoperability? We will have to work with the buffer data provided to us.

What is provided for reflection seems like a separate issue, but it has not been discussed as of yet.

**Comment by jeremyong** [comment] 2020-03-11 13:31
What I mean specifically is you can have "header" files that are perfectly valid to `#include` in existing C and C++ code as well as prepend to `GLSL` or `HLSL` code. Using a preprocessor (builtin or otherwise), the embedding of shader code in C++ or vice versa can be extended in a variety of ways, and reflection is just one of these capabilities you might get.

**Comment by dj2** [comment] 2020-03-11 13:37
There are no plans to support structs and declarations which match C/C++ syntax. The syntax of providing the type on the right makes parsing simpler and reduces the chances of browser incompatibilities.

**Comment by jeremyong** [comment] 2020-03-11 13:43
> The syntax of providing the type on the right makes parsing simpler and reduces the chances of browser incompatibilities.

As someone that has written parsers for GLSL, HLSL, and plenty of other languages (including toy languages that have the type on the right), I find this claim somewhat disingenuous. Not to mention that browsers are fully already compatible with WebGL1 which already has this syntax.

**Comment by kvark** [comment] 2020-03-11 14:10
Having the language compatible with C-defined structs was never raised up as a goal. We'll need to discuss that with the group. It would help to have concrete code by hand that needs to be ported.

**Comment by jeremyong** [comment] 2020-03-11 14:27
Thanks, I think my motivation for creating the issue was to raise the fact that the major problem every vendor needs to solve when integrating a shading language is how data gets bound from the host language. With the current direction, it seems like the "blessed path" is to use something like spirv-cross and reflect there as opposed to source-level reflection. Vendors not currently operating in this fashion will need to adapt. If this wasn't the intention, I think it is worth consideration or you'll have a lot of boilerplate in the wild of everyone solving the same problem.

**Comment by kainino0x** [comment] 2020-03-11 18:14
The #include compatibility argument only makes sense to me in contexts where the program contains C, and the program is producing WGSL directly (not going through GLSL/HLSL). I think most programs containing C will have no problem including glslang or DXC, but they do increase binary size. So I think this problem is mainly limited to WASM apps using C/C++, which are willing to put significant extra work in to reduce their binary size for Web. And it would be alleviated by the existence of a smaller-even-if-less-conformant GLSL-to-WGSL compiler (be it in C/C++ or JS).

**Comment by jeremyong** [comment] 2020-03-11 19:06
I think that's true, but stepping, back, there are many engines that exist today that could probably go straight to a WebGPU backend assuming there isn't much friction. The hope for WebGPU was that there would be a reasonable mapping to post-GLES3 hardware/drivers. Regardless of how many individual programmers there are that are working with this toolchain, the big picture is that making a painless migration process for say, Unity, or UE4, would immediately open the platform up to a host of existing users that currently do not deploy to the web.

Or. The alternative is an insular stack that requires many hoops to jump through, specialized knowledge on how to debug things, unduly expensive time needed to keep toolchains up-to-date and running.

**Comment by dj2** [comment] 2020-03-11 19:16
We're building SPIR-V to WGSL tooling. If you're toolchain already targets SPIR-V, you can generate WGSL from that output.

**Comment by kainino0x** [comment] 2020-03-11 19:22
For native apps compiling from Emscripten, I think it's likely we'll add an Emscripten option that enables a SPIR-V extension on Web, by compiling that SPIR-V-to-WGSL translator into the WASM build.

For e.g. Unity, I think the engine developers should/will handle the necessary tooling and make it automagic to all Unity users.
