### ISSUE TITLE
wgsl: permit certain resource variables to overlap

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3266] opened 2022-07-28 21:24 UTC
There's a discrepancy between WGSL and the API.

- WGSL says that two variables with overlapping lifetimes do no have overlapping memory locations.
- The API does not make that guarantee
   - It's very common to bind different ranges of the same buffer to distinct bindings
   - It's unpalatable to check for overlapping ranges among those for each draw/dispatch.   So implementations will not check that, and will accept the same resource bound to multiple bindings, subject to binding layout compatibility rules.

Google proposes that we loosen WGSL to make it match the API spec (and implementations).

The fact that "bad things happen" if you have racy writes is already covered by the memory model rules:  distinct agents must coordinate via some kind of synchronization when they access the same location and at least one of those accesses is a write.

The newly permitted kinds of overlaps are between any two resource variables in the shader that already satisfy the API constraints. In particular, each resource is exactly one kind of Resource Type (e.g. GPUBufferBinding), which also determines which kind of GPUBindGroupLayoutEntry  it is compatible with.  The [createBindGroup](https://gpuweb.github.io/gpuweb/#dom-gpudevice-createbindgroup) validation implies the following partition of resource kinds, from WGSL's perspective

- buffer (storage buffer and uniform buffer)
- sampler_comparison
- (non-comparison) sampler .  (comparison vs. non-comparison samplers have incompatible bind group layouts)
- storage texture (STORAGE_BINDING usage)
- external texture
- non-"external" sampled texture  (TEXTURE_BINDING usage)

**Comment by dneto0** [comment] 2022-07-28 21:29
FYI.

Races can occur only when at least one of the bindings is writable.  So: 
- read-write buffer vs. other buffers
- storage texture vs. other storage textures.

Consider a buffer resource exposed through variables X and Y in the shader.
A write through X is not visible to a read via Y.    

In the Vulkan memory model, the two resource variables denote a "memory model reference".  Making that a write via one memory model reference visible to an access in a distinct memory model reference requires  an intervening "domain" operation, which is not expressible inside a shader.  Domain operations are done only via API-side synchronization (barriers in the command stream).

**Comment by litherum** [comment] 2022-08-02 02:47
This issue is a dup of https://github.com/gpuweb/gpuweb/issues/1842 which has a resolution (but isn't closed yet because there's a pending TODO)

**Comment by litherum** [comment] 2022-08-02 03:00
(Note: this is *NOT* a dup of https://github.com/gpuweb/gpuweb/issues/889, which is about overlapping binding _numbers_ in the shader source, not about overlapping _regions_ of buffers)

**Comment by kdashg** [comment] 2022-08-03 17:16
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-02-minutes#wgsl-permit-certain-resource-variables-to-overlap-3266">WGSL meeting minutes 2022-08-02</a></summary>

* This is a duplicate of [https://github.com/gpuweb/gpuweb/issues/1842](https://github.com/gpuweb/gpuweb/issues/1842)

</details>

**Comment by kdashg** [comment] 2022-08-23 05:58
Closing as dupe of https://github.com/gpuweb/gpuweb/issues/1842.

**Closed by kdashg** 2022-08-23 05:58 UTC
Labels: wgsl
