### ISSUE TITLE
timestamp-query is unimplementable on TBDR architectures

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2046] opened 2021-08-18 02:21 UTC
The WebGPU spec [says](https://gpuweb.github.io/gpuweb/#timestamp):

> Timestamp query allows application to write timestamp values to a GPUQuerySet by calling writeTimestamp() on GPUComputePassEncoder or GPURenderPassEncoder or GPUCommandEncoder.

Metal is more complicated than this. Each `MTLDevice` has a function, [`supportsCounterSampling()`](https://developer.apple.com/documentation/metal/mtldevice/3564459-supportscountersampling) which exposes the points at which the device is capable of writing timestamp values. It returns true/false in response to an [enum value](https://developer.apple.com/documentation/metal/mtldevice/3564459-supportscountersampling) passed by the application:

- `atBlitBoundary`: ... between blit commands ...
- `atDispatchBoundary`: ... between kernel dispatches ...
- `atDrawBoundary`: ... between draw commands ...
- `atStageBoundary` ... at the start and end of a render pass’s vertex and fragment stages, and at the start and end of compute and blit passes ...
- `atTileDispatchBoundary`: ... between tile dispatches ...

Therefore, in order for WebGPU's timestamp queries to be implementable on Metal, the device would need to report true for the `atBlitBoundary`, `atDispatchBoundary`, and `atDrawBoundary` enum values.

Apple Silicon devices do not return true for any of these values. Indeed, any TBDR renderer wouldn't be able to return true for `atDrawBoundary` because draw calls are not discrete items; all the vertex processing of all the draw calls in the render pass execute together, in parallel with all the fragment processing of all the draw calls in the render pass.

Apple Silicon devices only return true for `atStageBoundary`; all the other enum values return false. The way it's works is for the application to pass [additional data](https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor/3564463-samplebufferattachments) into the render pass description. The additional data includes, for that render pass, which indices into which sample buffers that timestamps should be written into for the beginning and end of vertex and fragment processing. Indeed; there is no `sampleCounters()` call on any object which is available to Apple Silicon devices; the only way to get fine-grained timestamp data is using this declarative mechanism on the render pass descriptor.

One possible path forward here is to just say "well then I guess all TBDR renderers don't get to advertise the timestamp-query feature." This would be quite unfortunate, though, as I believe TBDR renderers represent a significant portion of the WebGPU group's target devices.

(Above, when I say "Apple Silicon devices", I'm referring to devices which support querying - I tested and verified iPhone 11, iPhone 12, and M1. Some older devices don't support querying at all - those shouldn't advertise support for timestamp-query feature.)

**Comment by kvark** [comment] 2021-08-18 16:45
This is almost a dupe of #1956, but much more detailed (thank you for filing!).
Timestamp queries were already a bit controversial with regard to reporting the actual time (have to derive the time/tick ratio, and it affects future execution on some Apple devices). And now we have this difference in how it's exposed and activated.
Maybe it's time to go back to the drawing board and reconsider exposing this at all in WebGPU MVP?

**Comment by kainino0x** [comment] 2021-08-23 20:10
Meeting: starting to converge on a direction. For render passes, change the API to declarative: ask for timestamps in beginRenderPass, instead of in commands.

**Comment by kainino0x** [comment] 2021-08-23 20:11
cc @haoxli

**Comment by kainino0x** [comment] 2021-08-23 20:13
Vulkan links:
> vkCmdWriteTimestamp latches the value of the timer when all previous commands have completed executing as far as the specified pipeline stage, and writes the timestamp value to memory. When the timestamp value is written, the availability status of the query is set to available.
https://www.khronos.org/registry/vulkan/specs/1.2/html/chap17.html#queries-timestamps
https://www.khronos.org/registry/vulkan/specs/1.2/html/chap7.html#VkPipelineStageFlags

I didn't find anything to control this in D3D12. I think this is still a gap where D3D12 doesn't represent TBDR well.

That's also a good reason that Vulkan has this very complicated API with vkCmdWriteTimestamp that is a command, with very fine-grained control over how the implementation handles platform differences.

I think it's OK if we don't expose that kind of control, and only give timing info for entire render passes, as I think that abstracts over backends and architectures more smoothly.

**Comment by kainino0x** [comment] 2021-08-23 20:20
Unfortunately I think the Vulkan API can't tell us a "top of fragment stage" time, only a "bottom of vertex stage" time.

**Comment by mrshannon** [comment] 2021-08-23 20:48
Did some testing, pipeline, vertex buffers, and index buffer changes have no overhead. Bind group changes are significant (more expensive than medium complexity draws). This test was done on Vulkan with 25,000 draws, with and without changing pipeline, vertex/index buffers, and bind groups between draws. Performance was measured in aggregate, no timestamp query.

If I get some time I will see about putting timestamp queries around the bind group changes and draws individual.  Though it sounds like that is not going to work anyways. Which is a problem currently because the spec makes it sound as it should and as shown by my tests, bind group changes are expensive.

**Comment by mrshannon** [comment] 2021-08-23 22:37
When using the current timestamp-query only draw calls show up, pipeline, bind group, and vertex buffer changes show 0. So whether this is because they are essentially free or the `writeTimestamp` calls are getting reordered around them I do not know. 

There is a difference between a timestamp written just before creating the render pass and one created as the first command on the render pass. In my testing this ranges from 2% to 40% depending on scene complexity, with the 40% rendering a single triangle and the 2% having 1000 draw calls. Therefore, I think it would be fine to make time queries run at the pass level, and not be able to run them within a pass.

Though, I think we need to make it clear that the old charts of how much a given command costs is no longer valid, otherwise we will have people like me from the OpenGL and WebGL world thinking that sub pass timestamps are important.

**Comment by haoxli** [comment] 2021-08-24 09:58
On Metal, the ways of sampling counters at command boundaries and stage boundaries are [different](https://developer.apple.com/documentation/metal/counter_sampling/sampling_gpu_data_into_counter_sample_buffers?language=objc),  sampling at stage boundaries needs to pass the sample buffer in render pass descriptor's [sampleBufferAttachments](https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor/3564463-samplebufferattachments?language=objc). If we plan to only support timing entire render passes, the `writeTimestamp` will not be needed, we need set query set in render pass descriptor instead (same for non pass and compute pass).

**Comment by Kangz** [comment] 2021-08-24 10:00
Exactly! In the meeting @litherum said he would do a proposal shortly.

**Comment by kvark** [comment] 2021-08-24 14:08
Hmm. If we want to support timestamps on render pass boundaries, does it still have to be a feature, or can we just have it for everybody? The metal implementation could split WebGPU command buffer into multiple Metal command buffers if it sees a render pass that needs to be timed, thus getting the time out of the command buffer.

**Comment by litherum** [comment] 2021-08-25 00:04
> The metal implementation could split WebGPU command buffer

I think this would be novel, and the CG has stayed away from doing this until now. There is some (probably small, but still nonzero) cost with splitting command buffers, because the command buffer is the object which resource tracking operates on inside the Metal driver. More command buffers means more resource tracking.

If you think it's worth investigating, I'm happy to gather some metrics / data to try to understand the costs of doing it.

**Comment by haoxli** [comment] 2021-08-25 01:38
>  there's also the fact that Metal exposes command buffer execution duration via a getter on the CPU 

Do you mean the [GPUStartTime](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1639924-gpustarttime?language=objc) and [GPUEndTime](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1639926-gpuendtime?language=objc) on `MTLCommandBuffer`, this is not related to `GPUQuerySet`, we have a separate [executionTime](https://gpuweb.github.io/gpuweb/#dom-gpucommandbuffer-executiontime) on command buffer.

**Comment by litherum** [comment] 2021-08-25 05:01
So I think the proposal would be:

### Part 1: Blits

We already split blit command encoders arbitrarily, so `GPUCommandEncoder.writeTimestamp()` can probably stay. No change here.

### Part 2: Render passes

Metal distinguishes between the start/end time of vertex processing and fragment processing, but desktop GPUs don't, so I think that means we have to just expose the beginning of the entire render pass and the end of the render pass. So, `GPURenderPassEncoder.writeTimestamp()` gets removed, and replaced with:

```
enum RenderPassTimestampLocation {
    "beginning",
    "end",
    // Maybe more here in the future! Exciting!
}

dictionary RenderPassTimestampAttachments {
    GPUQuerySet querySet;
    GPUSize32 queryIndex;
    RenderPassTimestampLocation location;
}

partial dictionary GPURenderPassDescriptor { // I don't think "partial dictionary" is actually a thing, but you get the idea anyway...
    sequence<RenderPassTimestampAttachments> timestampAttachments;
}
```

`GPURenderPassDescriptor. timestampAttachments` corresponds to:
- Metal: [`MTLRenderPassDescriptor.sampleBufferAttachments`](https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor/3564463-samplebufferattachments?language=objc)
- D3D12: [`ID3D12GraphicsCommandList::EndQuery()`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-endquery), called (possibly a number of times) at the beginning and end of the render pass.
- Vulkan: [`vkCmdWriteTimestamp()`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdWriteTimestamp.html), again called (possibly a number of times) at the beginning and end of the render pass.

### Part 3: Compute passes

Metal's `atStageBoundary` field says:

> at the start and end of compute .. passes

So I think the best we can do here is similar to render passes above. So, `GPUComputePassEncoder.writeTimestamp()` gets removed, and replaced with:

```
enum ComputePassTimestampLocation { // Intentionally a distinct type from RenderPassTimestampAttachments
    "beginning",
    "end",
}

dictionary ComputePassTimestampAttachments {
    GPUQuerySet querySet;
    GPUSize32 queryIndex;
    ComputePassTimestampLocation location;
}

partial dictionary GPUComputePassDescriptor {
    sequence<ComputePassTimestampAttachments> timestampAttachments;
}
```

`GPUComputePassDescriptor` is actually empty right now - this kind of addition is exactly why it exists. So that was a neat bit of foresight.

`GPUComputePassDescriptor.timestampAttachments` is parallel to `GPURenderPassDescriptor.timestampAttachments`, and therefore works similarly:

- Metal: [`MTLComputePassDescriptor.sampleBufferAttachments`](https://developer.apple.com/documentation/metal/mtlcomputepassdescriptor/3564436-samplebufferattachments?language=objc)
- D3D12: [`ID3D12GraphicsCommandList::EndQuery()`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-endquery), called (possibly a number of times) at the beginning and end of the compute pass.
- Vulkan: [`vkCmdWriteTimestamp()`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdWriteTimestamp.html), again called (possibly a number of times) at the beginning and end of the compute pass.

This proposal intentionally differentiates between `RenderPassTimestampLocation` and `ComputePassTimestampLocation` because we may want to add "beginning of fragment processing" or "end of vertex processing" values to `RenderPassTimestampLocation`, but not `ComputePassTimestampLocation`.

**Comment by Kangz** [comment] 2021-08-25 11:39
Thank you for the detailed proposal! It looks great overall.

> Part 2: Render passes

I think we can already add the distinction between vertex and fragment processing: many desktop GPUs are (soft-)tilers nowadays and Vulkan's `vkCmdWriteTimestamp` can measure the difference between the VS ending and the FS ending. However it can't measure the difference between VS and FS starting: implementations can just put the same timestamp twice. Likewise for D3D12 we could just write the same timestamps for VS and FS both for the beginning and the end. For both D3D12 and Vulkan we can then use a better API if one comes out in the future. WDYT? It might just be slightly confusing to developers that sometimes VS and FS are always in sync and sometimes not.

nit: the "attachment" terminology is a bit weird for timestamp imho. What about `timestampWrites: sequence<GPURenderPassTimestampWrite>`

> Part 3: Compute passes

Another option here is to keep `writeTimestamp`. Implementation on Metal devices without `atDispatchBoundary` would just split the compute pass in at this boundary. Like you said, this could have some cost because the state tracking is at pass boundary in Metal. However if we do what you suggested, then developers will have to manually split compute passes if they want to sample timestamps between dispatch, causing the same split of encoder, but on all Metal device, and with more work for the developer. So I think keeping `GPUComputePassEncoder.writeTimestamp` is marginally better.

**Comment by litherum** [comment] 2021-08-30 20:47
Here are (I believe) the counterproposals from the past 2 meetings:

1. The proposal [above](https://github.com/gpuweb/gpuweb/issues/2046#issuecomment-905184438)
2. Don't change anything, and but allow implementations to silently float `writeTimestamp()` to the beginning / end of passes
3. Don't change anything, and force TBDR implementations to split render passes and compute passes at the sites of `writeTimestamp()`
4. Accept only part 2 of the [above proposal](https://github.com/gpuweb/gpuweb/issues/2046#issuecomment-905184438), and force implementations to split just compute passes at the sites of `writeTimestamp()`
5. Remove `writeTimestamp()` on `GPUComputePassEncoder` and `GPURenderPassEncoder`, but leave it on `GPUCommandEncoder`. If an application wants to know how long a pass took, it can just call `GPUCommandEncoder.writeTimestamp()` directly before and after the pass

If I've forgotten any, please feel free to add to this list.

**Comment by litherum** [comment] 2021-08-30 20:56
Regarding the list in the previous post,

1. This would be unfortunate because it would mean all iPhones and the M1 chip wouldn't support this optional feature. It's particularly unfortunate, because those devices _do_ have a way to measure GPU time more finely than an entire command buffer.
2. There were some counterarguments to this proposal because some people want to be able to measure the duration of individual draw calls (which is fundamentally incompatible with TBDR)
3. This silently makes it look like some draw calls took 0 time, but only on some devices. It seems silently misleading
4. I believe everyone in the CG agrees that splitting render passes is bad for performance
5. We (at least) believe that splitting compute passes is bad for performance
6. This produces data that is noisier than necessary on Metal (because the `writeTimestamp()` calls are in an unrelated pass) and doesn't allow for (theoretical) future advances, like adding an end-of-vertex-processing value to the `RenderPassTimestampLocation` enum.

**Comment by kainino0x** [comment] 2021-08-30 22:43
The editors discussed this and we're tentatively in favor of moving timestamp (and perhaps pipeline statistics) queries into a separate document until such time as we actually intend to ship these extensions on user machines. However we are reaching out for some developer feedback first.

**Comment by mrshannon** [comment] 2021-08-31 21:02
I discussed this with some other developers at work and our primary concern is to have timestamp and pipeline statistics queries remain available for developers to profile their applications. We would prefer this shipped as it would allow us to collect performance information from user’s machines but at a minimum, we would like to use timestamp queries and pipeline statistics in house during application development.

Furthermore, because the primary use case is in house profiling, we would be happy with a timestamp interface which was different between desktops and TBDR such as iPhone.

I propose some sort of experimental feature prefix such as used with OpenGL, in this way certain features could be released in an un-finished/subject to change state (probably behind a flag). That way we can make use of them in development and testing, but without the spec having to be finalized.

**Comment by litherum** [comment] 2021-09-01 06:32
@mrshannon

> for developers to profile their applications

Is [`GPUCommandBuffer.executionTime`](https://gpuweb.github.io/gpuweb/#dom-gpucommandbuffer-executiontime) sufficient for that? It's not optional.

**Comment by litherum** [comment] 2021-09-01 07:02
I gathered some data about splitting compute passes. Here is a sample program that compares the runtime of a set amount of work in a set number of dispatches, but executed two different ways:

1. 100 dispatches in a single compute pass
2. 100 dispatches spread among 100 compute passes - 1 dispatch per pass

I'm making an extreme example here, so the shader is intentionally small: it just calls `cos()` 20 times. You can expect real-world results to be less extreme than those posted here, but the data here still shows a reproducible case that any developer could have written.

The data measures GPU time, gathered from [`MTLCommandBuffer.gpuStartTime`](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1639924-gpustarttime) and [`MTLCommandBuffer.gpuEndTime`](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1639926-gpuendtime).

Here is the sample program: [SplitComputePass.zip](https://github.com/gpuweb/gpuweb/files/7088823/SplitComputePass.zip) and here are the results: [Splitting Compute Encoders Performance.zip](https://github.com/gpuweb/gpuweb/files/7088828/Splitting.Compute.Encoders.Performance.zip)

1. Apple A14 GPU: 95.2% overhead

<img width="565" alt="Screen Shot 2021-08-31 at 11 54 18 PM" src="https://user-images.githubusercontent.com/918903/131625766-38de884f-e9bd-4ab2-b8fd-318882a81684.png">

2. Apple M1: 96.7% overhead

<img width="565" alt="Screen Shot 2021-08-31 at 11 54 50 PM" src="https://user-images.githubusercontent.com/918903/131625827-45e6db25-3f17-439e-b501-1fcbcad24a59.png">

3. AMD Radeon Pro Vega 56: 69.1% overhead

<img width="558" alt="Screen Shot 2021-08-31 at 11 55 18 PM" src="https://user-images.githubusercontent.com/918903/131625896-d60d50e2-d803-49db-91e8-d4555bfe82e9.png">

4. AMD Radeon HD - FirePro D500: 0.9% overhead

<img width="561" alt="Screen Shot 2021-08-31 at 11 55 48 PM" src="https://user-images.githubusercontent.com/918903/131625966-774ec741-6274-4f6e-a34b-1e394dc6609e.png">

5. AMD Radeon RX 570: 24.2% overhead

<img width="560" alt="Screen Shot 2021-08-31 at 11 56 14 PM" src="https://user-images.githubusercontent.com/918903/131626014-1add4ecd-7663-4b10-a6e7-1ad1a1dd3202.png">

6. AMD Radeon Pro 560: 35.3% overhead

<img width="561" alt="Screen Shot 2021-08-31 at 11 56 40 PM" src="https://user-images.githubusercontent.com/918903/131626074-3eb4e36f-b221-44f1-bd4d-43fd82c6180e.png">

7. Intel(R) HD Graphics 630: 34.3% overhead

<img width="564" alt="Screen Shot 2021-08-31 at 11 57 10 PM" src="https://user-images.githubusercontent.com/918903/131626141-431c3e78-4873-4f2c-8702-59cd75d401e1.png">

8. NVIDIA GeForce GT 750M: 41.1% overhead

<img width="564" alt="Screen Shot 2021-08-31 at 11 57 39 PM" src="https://user-images.githubusercontent.com/918903/131626221-c8c29ee7-4dcd-47f4-9089-15b24eab1788.png">

Based on this data, it seems fairly clear that we shouldn't silently be splitting compute encoders.

**Comment by kvark** [comment] 2021-09-01 15:07
@litherum This is great stuff, thank you for gathering the stats!
On a tangent, I wonder what the overhead would look like for the blit pass.

**Comment by Kangz** [comment] 2021-09-01 19:20
Thank you for all the data. I thought it might be because the shaders could run in parallel and spit passes would force wait-for-idle but looking at the sample there's a data dependency so that must not be it. It is really surprising that splitting passes is so expensive on Apple GPUs >_>

Anyways I think it makes a compelling point, but one thing I don't understand is that we are just making it harder for developers to get timestamps inside render passes because they have to do the split themselves and that is more refactoring of their code it seems. Why can't the browser do it for them? it will be as good or better than what developers can do. The only benefit (though it is a big one) is that it makes the cost apparent if developers know that individual compute passes can be expensive on some hardware.

**Comment by mrshannon** [comment] 2021-09-01 19:48
As a follow-up to my post from yesterday. The developers where I work have determined that per pass resolution is enough for our use case. Furthermore, we probably don't care if it's MVP because some other performance features are likely not going to be MVP as well and thus optimization efforts on our code cannot being until post MVP anyways.

**Comment by litherum** [comment] 2021-09-01 20:42
@Kangz 

> that is more refactoring of their code

Right - the problem is deception. Seeing WebGPU code like

```
...
computePassEncoder.setPipeline(...);
computePassEncoder.setBindGroup(...);
computePassEncoder.dispatch(...);
```

**Comment by haoxli** [comment] 2021-09-09 01:28
As this extension is a development-only feature, I think we can support sampling both timestamps between cmds and timestamps per passes according to the hardware support.

> 4. Don't change anything, and force TBDR implementations to split render passes and compute passes at the sites of `writeTimestamp()`

Agree with this proposal, but we may not need to force TBDR implementations  to split passes. A different opinion is implement timestamps on pass level for both TBDR GPUs and immediate GPUs.  So that we can keep the capabilities of immediate mode devices, also can use the timestamps on TBDR devices, just like what Metal did which support both of them.

Proposal suggestion:
- Keep current `writeTimestamp()` implementation, and disable it on TBDR devices.
-  Blits/Compute passes
```
enum TimestampLocation {
    "beginning",
    "end",
}
	
dictionary TimestampAttachments {
    required GPUQuerySet querySet;
    required GPUSize32 queryIndex;
    required TimestampLocation location;
}
	
partial dictionary GPUCommandEncoderDescriptor {
    sequence<TimestampLocation> timestampAttachments;
}
	
partial dictionary GPUComputePassDescriptor {
    sequence<TimestampLocation> timestampAttachments;
}
```	

- Render passes
```
enum RenderPassTimestampLocation {
    "beginning",
    "end",
    // Maybe more here in the future! Exciting!
}
	
dictionary RenderPassTimestampAttachments {
    required GPUQuerySet querySet;
    required GPUSize32 queryIndex;
    required RenderPassTimestampLocation location;
}

partial dictionary GPURenderPassDescriptor {
    sequence<RenderPassTimestampAttachments> timestampAttachments;
}
```

**Comment by litherum** [comment] 2021-09-10 17:38
I'm worried that if we expose two independent extensions for MVP, devs will choose the one that doesn't work on TBDR, because they both would be present on the author's development machine.

If we can avoid it, we shouldn't offer two different APIs: one for desktop and one for mobile. Doing so is an anti-pattern on the web in general. And we can avoid it here - one extension is implementable everywhere, and useful, and the other isn't implementable everywhere.

I'm not saying we should _never_ have two independent extensions; just that it's extra important to just have one in the first release of WebGPU. Best practices for the API haven't been established yet across the industry, and we run the risk of them being established poorly if we choose the wrong path here.

**Comment by haoxli** [comment] 2021-09-14 02:23
> I'm worried that if we expose two independent extensions for MVP, devs will choose the one that doesn't work on TBDR, because they both would be present on the author's development machine.

Developers could detect which one is supported on their platforms, because they're both extensions, we need to check whether an extension is supported before use it. 

> If we can avoid it, we shouldn't offer two different APIs: one for desktop and one for mobile. Doing so is an anti-pattern on the web in general. 

I don't think the two different APIs are conflict. Just like the exectionTime on command buffer, they are the timestamps at different level. The timestamps against TBDR also can be supported desktop, I think.

**Comment by kainino0x** [comment] 2021-09-14 04:52
> I don't think the two different APIs are conflict. Just like the exectionTime on command buffer, they are the timestamps at different level. The timestamps against TBDR also can be supported desktop, I think.

+1. But I also think all signs are pointing toward making timestamp-query a command-line-flag-only extension that probably lives in a separately maintained specification document. In fact, both of these features _could_ probably be command-line-only, but I think we should probably keep timestamp-attachments in the main spec.

**Comment by haoxli** [comment] 2021-09-28 01:29
Agree that V1 features should support both desktop and mobile, we can discuss desktop-only timestamp query after V1. Thanks for keeping `writeTimestamp` in middle of passes in Chromium/Dawn, it's important to our automated performance profiling.

**Comment by haoxli** [comment] 2022-07-25 08:08
> Part 1: Blits
We already split blit command encoders arbitrarily, so GPUCommandEncoder.writeTimestamp() can probably stay. No change here.

Currently we use MTLBlitPassDescriptor.sampleBufferAttachments to implement writeTimestamp on command encoder on Metal backend for the devices support GPU counter sampling at stage boundary, but it cannot sample any counter values if there is no blit command on the blit encoder.

```
commandEncoder.WriteTimestamp(querySet, queryIndex);
```

We encode the command on Metal:
```
MTLBlitPassDescriptor* descriptor = [[MTLBlitPassDescriptor alloc] init]
descriptor.sampleBufferAttachments[0].sampleBuffer = querySet->GetCounterSampleBuffer();
descriptor.sampleBufferAttachments[0].startOfEncoderSampleIndex = MTLCounterDontSample;
descriptor.sampleBufferAttachments[0].endOfEncoderSampleIndex = NSUInteger(queryIndex);
id<MTLBlitCommandEncoder> blit = [commandBuffer blitCommandEncoderWithDescriptor:descriptor];
[blit endEncoding];
```

The value at `queryIndex` is 0 which is expected to be GPU counter value.  If we add a fill command `[blit fillBuffer rang:NSMakeRange(0,1) value: 0]` to the blit encoder, we can get correct value. If this is not a Metal bug, we need to remove `WriteTimestamp` API on command encoder and use `timestampWrites` instead, because we cannot add any blit commands to the blit encoder for implementing `WriteTimestamp`, which will eventually affect the correctness of the timestamp.

@litherum Could you help to double check if this is a bug? I reported it to Apple Feedback Assistant, but no reply yet.

**Comment by litherum** [comment] 2022-08-04 21:36
This is a bug in metal; I reported it back in April at rdar://91371767. Empty encoders never hit the GPU at all, and we aren’t counting the presence of timestampWrites as sufficient for non-emptiness.

The workaround is just to encode some dummy blit command (but only in empty encoders which have timestampWrites specified).

**Comment by litherum** [comment] 2022-08-04 21:40
> I reported it to Apple Feedback Assistant

What’s the FB number?

**Comment by Kangz** [comment] 2022-08-09 17:06
Closing again since it is confirmed to be a bug. @haoxli can you also provide the feedback number?

**Closed by Kangz** 2022-08-09 17:06 UTC

**Comment by haoxli** [comment] 2022-08-11 04:27
FB10510636

**Comment by haoxli** [comment] 2022-08-11 04:28
> > I reported it to Apple Feedback Assistant
> 
> What’s the FB number?

FB10510636
