### ISSUE TITLE
Optional feature request: filterable 32-bit float textures

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#3601] opened 2022-11-17 00:05 UTC
This is a pretty common WebGL extension: https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_float_linear

**Comment by kainino0x** [comment] 2022-11-17 01:48
Technically should go in the "Polish post-V1" milestone, but given it's for WebGL parity, and very small, I'd tentatively say we should try for V1.

**Comment by kainino0x** [comment] 2022-11-30 19:18
Just realized I think this is a duplicate of #3556.

> See also https://github.com/gpuweb/gpuweb/issues/3601.

@magcius That is this issue, did you mean to link to another?

**Comment by magcius** [comment] 2022-11-30 20:50
Oops, I meant to link #3001

**Comment by kainino0x** [comment] 2022-12-01 00:15
Sorry for some reason I looked at the two and thought they said the same thing. Brain tired.

In any case, group accepted for v1, moving to editorial to add this.

**Comment by kainino0x** [comment] 2023-02-16 00:50
Hardware support for filtering r/rg/rgba32float (it's the same for all 3):

- Metal family Apple2-8: Never (except on Mac)
- Metal family Mac2: Always
- D3D12 (FL11_0+): Always
- Vulkan: Optional (of course)
  - Vulkan Desktop: Always
  - Vulkan Adreno: Never
  - Vulkan Mali: Sometimes

Worth noting this qualifies for a feature per:
https://github.com/gpuweb/gpuweb/blob/main/process/RequirementsForAdditionalFunctionality.md

**Closed** 2023-03-02 18:12 UTC
Labels: feature request, editorial, needs-cts-issue

**Comment by kainino0x** [comment] 2024-09-06 23:26
For the record, there's some investigation going on into whether this _can_ actually be supported on iOS (despite what the Metal Feature Set Tables say). Discussion starting here:
https://github.com/gpuweb/gpuweb/issues/3556#issuecomment-2334477162
