### ISSUE TITLE
Buffer operations: Questions about order of destroy/unmap calls and mapping promise settling

### ISSUE THREAD

**Issue by JusSn** [gpuweb/gpuweb#212] opened 2019-02-19 01:09 UTC
_Part 1_
```javascript
buffer.mapWriteAsync().then(ab => { // [1]
    fill(ab); // [3]
});
buffer.mapWriteAsync().then(ab => { // [2]
    fill2(ab); // [4]
});
```

Due to how promises work, the numbers also indicate execution order.
**Q 1**: Is buffer in the `mapped` state as soon as [1] returns?

If the answer is no, then [3] executes, but what about the promise returned on line [2]? 
**Q 2**: Should that one reject since the first callback failed to call `buffer.unmap()`?

If Q 1's answer is yes, then [2] returns a promise that rejects and [3] executes as expected. However, this leads me to:

```javascript
buffer.mapWriteAsync().then(ab => { // [1]
    fill(ab); // [3]
});
buffer.unmap(); // [2]
```

The `unmap()` call will reset the state of the buffer to `unmapped` before its promise settles. 
**Q 3**: Is this intended, and what happens to the promise then? (My guess is that it rejects?)

**Q 4**: If the answer to **Q 1** is yes, but **Q 3** is not, then do we need another state, `pending`, to represent buffers that have created a mapping promise, but that promise has yet to settle? Calling any function on a `pending` buffer other than `destroy()` would be an invalid operation.

_Part 2_
```javascript
buffer.mapReadAsync().then(ab => {
    read(ab); // [2]
});
buffer.destroy(); // [1]
```
**Q 5**: Both `mapReadAsync()` and `destroy()` calls are valid, but the mapRead promise should reject, correct?

If it does, this means the implementation must defer promise settling to the end of the task boundary to prevent resolving promises with arrayBuffers of destroyed GPUBuffers, which leads me to:

```javascript
buffer.mapReadAsync().then(ab => {
    read(ab); // [2]
});
Promise.resolve().then(() => {
    buffer.destroy(); // [1]
});
```

If the implementation defers mapping promises like described above, but not other promises, this is the order the promises will settle. 
**Q 6**: With that knowledge, I'd expect the mapRead `promise` to reject, but without, I'd be very confused. Is this a problem?

**Comment by Kangz** [comment] 2019-02-19 09:36
**A 1**: The buffer is in the mapped state immediately.

**A 2**: It should reject but the problem isn't that the first callback failed to call unmap. It is that at the time the second `mapReadAsync` is called the buffer is in the mapped state.

**A 3**: It is intended and the promise should reject. [BufferOperations.md](https://github.com/gpuweb/gpuweb/blob/master/design/BufferOperations.md) says the following for `unmap`: "*Upon success the buffer is put in the unmapped state, its mapping detached or a pending mapping promise rejected.*"

**A 5**: The promise should reject because `destroy()` contains an implicit call to `unmap()` in [BufferOperations.md](https://github.com/gpuweb/gpuweb/blob/master/design/BufferOperations.md): "*Calling GPUBuffer.destroy on a buffer with the MAP_READ or MAP_WRITE usage flags contains an implicit call to GPUBuffer.unmap.*"

**A 6**: It would likely reject. AFAIK promises are always resolved after the end of the current task. Also [BufferOperations.md](https://github.com/gpuweb/gpuweb/blob/master/design/BufferOperations.md) tries to provide timeline guarantees for `map*Async`: "* The promise will settle before signals for the completion of follow-up unbuffered commands.*" but also the intent (and previous versions of the text) is that the promise will settle after the signals for the completion of previous unbuffered commands.

**Comment by JusSn** [comment] 2019-02-19 19:41
Thank you @Kangz, this helps a lot.

**Comment by JusSn** [comment] 2019-02-26 01:09
> The promise will settle before signals for the completion of follow-up unbuffered commands.

Can you elaborate on this a bit more? What's a "signal for completion?" Does this mean that all unbuffered commands have to wait on the promise to resolve, and only buffered commands should be executed on that same Web GPU thread until the promise is settled by the implementation?

**Comment by Kangz** [comment] 2019-02-26 08:52
Basically `mapAsync` acts a bit like a fence where you can see the progress of GPU execution. What this overly complicated and underspecific sentence meant is that the promises for `mapAsync` and `GPUFence.onCompletion` are resolved in the order of the GPU execution.

**Closed** 2019-09-21 23:34 UTC
Labels: question
