### ISSUE TITLE
GPUAdapter.name considered harmful

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2191] opened 2021-10-16 08:12 UTC
Identifying the user's device by name is an anti-pattern on the web.

There are 2 reasons:
1. Tracking/fingerprinting. `GPUAdapter.name` is particularly insidious because it can indicate the user's socioeconomic status.
2. Correctness: Consider the User-Agent string, and all the strife that has caused. For example, we don't want websites to say `if (adapter.name.indexOf("NVIDIA") != -1) { /* enable bells and whistles because we know we're on a fast device */ }`. These kind of assumptions about device manufacturers always end up being wrong in the long term.

If an application needs to know whether or not they have to work around some bug on some driver, the way they should be doing that is by observing if the bug actually occurs, not by reading the device's name.

It is not sufficient to defend `GPUAdapter.name` by saying that browsers can just lie. Doing so is misleading the app developer; making them think they have access they don't actually have.

**Comment by magcius** [comment] 2021-10-17 02:29
There's often very few ways of detecting these bugs other than reading back textures from the GPU. Doing this at startup is slow and costly, and often these bugs need to be detected before the rest of the rendering algorithm is built.

The comparison with User-Agent is basically spot on; while there is a lot of content that uses the User-Agent for bad purposes, and is meant to be used with last resort, I have personally encountered multiple issues that require me to use its presence, after all other approaches have been exhausted. And due to the more prickly nature of GPU drivers, I expect this to be a much bigger concern in practice.

**Comment by raphlinus** [comment] 2021-11-01 15:42
Information about the adapter (and driver!) is important to applications, primarily for the purpose of implementing blocklists. Long experience proves the need for them, and I don't think WebGPU is going to fundamentally change that.

In addition, it is straightforward to extract a *lot* of information through litmus testing, especially in the presence of atomics. I'll give one example, that correlates well with socioeconomic status as stated in the original comment - and which I have already [made public](https://raphlinus.github.io/gpu/2021/04/28/slow-shader.html) in a different context, specifically trying to understand a performance issue. Write a shader that simply counts the number of resident workgroups, by incrementing an atomic counter on entry, doing a small dummy load, and decrementing on exit. Read out the maximum value (atomicMax) at the end. Run multiple trials at different workgroup sizes, and that will reveal information at least as much as SIMD width and approximate dollar cost.

My personal belief is that attempts to hide or obscure adapter information are theater.

**Comment by kenrussell** [comment] 2021-11-03 17:14
> @kenrussell: you collected a list of uses for the WebGL unmasked renderer strings is there a summary or a doc we can share?

Apologies for the long delay replying.

Khronos' WebGL working group surveyed a group of companies including Esri, Figma, NVIDIA, OnShape, Photopea, Scirra, Sketchfab, Uber, and Unity, as well as Google's Maps team.

- "Despite all of the progress that WebGL has made, we still regularly hit WebGL bugs where things render incorrectly, especially on Windows...[w]ithout this information, we would have been unable to debug and fix these WebGL implementation bugs that we've been encountering. For example, just earlier this week we used this to determine that all users encountering weird GPU issues were using a specific GPU. Jamie was then able to ask over Twitter for someone with that hardware configuration and then reproduce the problem himself: https://twitter.com/jlfwong/status/1123363319602040832...

  We also use this information inside Figma at runtime to enable workarounds for WebGL implementation bugs. The workarounds are not enabled by default because they are slower, and in some cases actually even incorrect (but less incorrect than when the bug is triggered). For example, we have an alternative implementation of glClear for 7 specific Intel cards that draws a quad to do the clear instead. This is noticeably slower on mobile devices so we only want to do this if we absolutely have to...

  Both Figma and Chrome are heavily invested in creating a stable cross-platform GPU-accelerated experience, and this information is critical to being able to do that successfully. I sympathize with the privacy argument but I don't see how we can solve these problems any other way.”

- "I use it to detect and work around known bugs in drivers, like Apple not supporting row-major matrices (https://bugs.chromium.org/p/angleproject/issues/detail?id=2273), as well as providing better error messages to users (e.g. 'Google SwiftShader'). The immediate impact if this extension was removed would be that all Apple devices would fail to render."

- "At Onshape we use WEBGL_debug_renderer_info for a few purposes:

  1. To work around driver-specific interactions with our system.  More often than not this involves disabling a feature of our renderer that is exhibiting poor performance on a particular platform/GPU combination.  If possible, we will try to find an alternative solution that performs well on all platforms, but this is not always feasible.

  2. To inform users when they may be experiencing reduced performance due to the use of an integrated GPU over a discrete one.  We have seen a significant number of users complain about rendering performance only to discover later that they have a more powerful, discrete GPU going unused.  We try to shorten this pain period by detecting systems that may have a discrete GPU alongside an integrated one, and notify the user when degraded rendering performance is detected.  We are looking forward to a wider implementation of the powerPreference option so the guesswork of which GPU is running will be avoided."

- "We build a HTML5 game engine and have used the unmasked renderer for:

  1) Identifying GPUs affected by driver bugs, and working around it (e.g. 'Mali' on Android)
  2) Analytics on the unmasked renderer to identify the impact of such bugs and help us decide how to respond
  3) Identifying which GPU is really in use on dual-GPU systems
  4) Displaying it to the user as a diagnostic (also for them to identify which GPU is in use).”

- "It's very useful for Sketchfab; here are our two main use cases:

  1) We use it very extensively to report user GPU in our automatic error reporting tools. When we need to reproduce shader bugs it's invaluable. We found many shader bugs directly linked to specific GPU vendors/renderers. From visual artifact to compilation errors all tied to very specific vendor/renderer (Intel branching error, PowerVR glsl compiler not supporting vec4 arrays as function parameter, implicit cast fails in some cases on Mali, etc...). And Compiler Error messages are not enough 'Internal compiler error: Too many vertex shader constants' (Adreno/android4.x.x favorite)

  2) We also use it to warn users when they are switched to 'software webgl acceleration' (Due to too many GPU crashes and Chrome reverting to SwiftShader)...otherwise users might think the Sketchfab renderer is very slow, where just restarting/reloading chrome fixes it."

- “Currently luma.gl and deck.gl use this feature to activate nVidia/Intel specific GLSL workarounds (to defeat compilers optimizing out code or too low precision in built-in math). We mainly use those workarounds in our 64-bit floating point emulation library."

- “In addition to using exact GPU info for what [Scirra] mentions, we [Unity] are also using exact GPU info+device+OS+browser to use as an additional bit of info to identify weak fillrate systems for whether to use 'SD' or 'HD' rendering (i.e. whether to render to 1:1 CSS pixels, or 1:1 with device pixels/retina resolution).”

The concern of revealing the user's socioeconomic status via the GPU type has never been raised before in a decade of working on WebGL. On the other hand, Google Meet's WebGL-based background blur and replace feature has absolutely been a socioeconomic equalizer for students learning from home during the pandemic. Reliable deployment of GPU-based features like this requires exposing information about the GPU type to the web application.

I reject the framing "GPUAdapter.name considered harmful". Information about the GPU type is required in order for WebGPU to be adopted at scale by real-world applications. Different splitting, factoring and bucketing of the GPU type can certainly be considered in order to minimize the number of bits of entropy revealed about the user's configuration.

**Comment by krogovin** [comment] 2021-11-10 16:20
I am going to likely join the chorus of many graphics developers:
- Knowing the GPU architecture is key for performance. Just the difference between a tile based renderer and an immediate renderer are significant for what is good and what is bad for performance. However, that is not enough because various patterns that are good for one GPU can be really bad for another. I cannot emphasize this enough.
- Knowing the "power" of the GPU is also important in terms of what level of fidelity to deliver for a smooth experience, that means the GPU model number as well. For some algorithms it is a really good idea to know the power "balance" between the CPU and GPU as well.
- Driver version can be pretty important sometimes too in order to workaround known driver bugs. Sadly, this also likely means knowing what browser version implementation of WebGPU to work around bugs there as well.

Another thing to keep in mind is this: if the information is provided privacy might actually be better. This is because, without an interface for getting those numbers, developers will fall back to running micro benchmarks to figure it out anyways which will then grow to commercial libraries for that exact purpose. Running the micro benchmarks will then give even more information often as well. This observation is not even mine originally, I remember someone else stating this in another jazz on WebGPU, but I cannot remember who, where or when (I think it was someone from Google).

I, as Ken Russel stated before me, also reject the framing "GPUAdapter.name considered harmful".

**Comment by Kangz** [comment] 2021-11-10 17:30
Summarizing this issue, it's clear that there are legitimate use-cases for wanting more detailed information about the adapter and that `GPUAdapter.name` is not purely harmful. At the same time it's clear that browsers must be allowed to expose no information about the system if they don't want to.

A long debate about `GPUAdapter.name` yes or no doesn't seem like it will much progress. Instead I suggest that we look for concrete proposals of mechanisms for exposing information in a way that's 1) useful to developers and 2) lets browsers be in control of their privacy story.

(Chromium-hat) based on the feedback in this thread and what @kenrussell quoted, a proposal of "force browsers to expose no info" would fail to address many important needs from developers and would be much less usable. It's important to find a tradeoff that protects user's privacy while enabling developers to do more. I piggy-backed on @beaufortfrancois's proposals in #2195 with some more concrete items. Please discuss it or come up with alternatives!

**Comment by toji** [comment] 2021-11-17 23:47
On today's call @litherum put forward some of the reasoning why Apple doesn't see the need to expose this information, but unfortunately we ran out of time before we could discuss many of the points in depth. As such I'll offer my responses and questions here in hopes of keeping the dialog going. Forgive me if I paraphrase any of Apple's concerns incorrectly, as I only have my own notes about what was said to work from here.

First I wanted to acknowledge the point that was made that WebGL is currently used more for fingerprinting than for actual 3D graphics. I do not have any numbers in front of me to confirm if that's true or not but it's an easy thing to believe. I am in favor of any steps we can take to mitigate drive-by fingerprinting without harming the utility of the API. I'm not convinced, however, that avoiding any form of GPU identification is the right response, or would even solve the problem fully. 

Any suggestions that have been made in this thread of methods developers could use to identify bugs also represent fingerprinting opportunities, simply with a higher cost of production. It's a mistake to assume that sites that want to fingerprint users would ignore an avenue to do so simply because it takes longer to execute or uses more resources. But that overhead is something that many legitimate use cases are sensitive to. If we're harming developers attempting to create positive experiences with our API in favor of mildly inconveniencing those who want to abuse it we're on the wrong path. I would much rather see effort put into allowing developers and users to control how and when the API can be used. For example, it's not clear to me if we've discussed how WebGPU integrates with the [Permissions Policy spec](https://w3c.github.io/webappsec-permissions-policy), which would allow pages to block WebGPU from being used by embedded Iframes that are often a source of trackers.

Next, I wanted to again ask for clarity on Apple's stance on returning strings that identify the GPU in any manner. On the call it was stated that "Giving out the Metal name string to anyone who asks for it is a 'Non-starter'", but when I asked for clarification I feel like the same thing was just repeated. I'd really like to be clear on what Apple means by this, because it affects how we should be discussing this topic. It seems obvious that it indicates an opposition to reporting identifying strings unconditionally, but when asked if this also represented an opposition to reporting that information in more limited situations, such as upon getting user consent, the reply was effectively "it's complicated."

If it's Apple's position that a GPU identifier must never be reported to the page under any circumstances I'd appreciate that to be stated plainly. If that's not the case and there are circumstances where it would be viewed as permissible I'd like to establish that now, even if the exact circumstances under which that might be considered are still in flux.

Another point I'd like to address is that Myles made the comment that with WebGPU, browsers are acting as an intermediary between developers and the hardware/drivers and as such should take steps to mitigate driver issues when they appear. I agree with this sentiment! It's exactly what browsers have been doing with WebGL since its inception, and something we fully intend to continue doing with WebGPU for the foreseeable future. I can't speak for all browser teams, but I know on the Chrome GPU team (and the ANGLE team) we're pretty aggressive about identifying driver bugs and working around them or, in the most dire cases, blocking drivers whose behavior cannot be worked around. Take a look at Chromium's [gpu_driver_bug_list.json](https://source.chromium.org/chromium/chromium/src/+/main:gpu/config/gpu_driver_bug_list.json) to get a sense of the type and scope of issues we're actively mitigating in the browser.

However, given that browser teams have finite resources there will always be some number of bugs that we aren't able to address. Even in cases where we do, there is going to be some latency in how quickly those fixes are shipped to users. This is especially true for browsers that have a release cadence of approximately once per year.

Additionally, there are classes of issues that applications may encounter that don't qualify as "bugs", but do affect their performance. For example, if rendering to cube maps is significantly slower on some devices than others, but the rendered results are still accurate that's not a bug, and it's likely that a large number of applications can run without ever being affected by it even if they use the feature in question, but an application that dynamically renders multiple cube maps per-frame may want to adjust their code to account for the performance hit on that device.

Simply put, it's expected that browsers will continue to actively identify and address bugs, but that alone does not replace the need for developers to be able to identify and respond to GPU differences.

A final point I wanted to address was @litherum's assertion that there "isn't and can't be a demonstrated need" for this information because the API hasn't shipped. I firmly reject this framing, and assert that we have nearly a decade of directly applicable experience from WebGL that says otherwise. Neither WebGPU nor the underlying native APIs are somehow immune to buggy drivers, large performance deltas, or behavioral quirks. Ideally they should be better positioned than with OpenGL for various reasons, but there are still fallible human beings and physical limits at every level of this stack. We have to be realistic about the fact that no matter how hard we as browser, OS, or GPU vendors try, developers will still encounter situations where their applications perform differently for some subset of their users. We know this. Ignoring that fact would be a massive disservice to the developers that have worked so hard for years now to embrace the web as a viable platform for GPU development.

I still believe there is a reasonable middle ground to be found between "report full GPU details to every page with impunity" and "Tell developers they never need to know", and would advocate that we focus this conversation on finding appropriate methods to deliver that information in a manner that is both useful and privacy sensitive rather than to argue about whether or not it's even necessary. We already know that it is.

**Comment by gyagp** [comment] 2021-11-18 09:22
Personally, I think it's hard to find a middle ground to be both useful and privacy sensitive for such kind of information. This is like we always have 2 sides to everything. Some people see more on one side, while the others see the opposite. Even specific for one person, they may change the focus from time to time.
At the same time, this is a rising and maybe the most concerning problem for the web platform, and we see similar debates here and there. Different browsers choose different stands, which results in bigger and bigger divergence. We need to have a systematic way to solve this.
I like the idea of permission system. It is not new, but very mature in mobile systems, like iOS and Android. So why not categorize info into different groups, and create the web spec to be fully aware of the permission system? Then for a specific origin (counterpart of a native app), users' permission must be granted first before access to them. And browsers' implementation guarantees all the permissions listed clearly and turned on/off easily by the users. If some browser vendors choose not to expose some info, they may simply list the usage of information, but the permission is never granted. 
In this way, we hand over the final decision to users, which may be a middle ground in general for all browser vendors.

**Comment by krogovin** [comment] 2021-11-18 13:30
I think there can be middle ground and some of post from @toji has starts of it already:
- iframe gets no GPU info; in all honesty I'd really like that iframe does not even get WebGPU or WebGL even. I've always hated iframe and it is the most susceptible to abuse.
- a browser can be configured to give a generic no-information answer down to the finest details, perhaps a minor spec of what the level details?
- a webpage wants more info it can issue a request to ask for it and the browser makes a dialogue box asking for the info. This option needs to be protected against a rogue page spawning tons of these dialogue boxes though.

I personally very much like the idea that a user controls how much info they give to a webpage (and this is why I view that iframe should get nothing, since that it not a webpage the user explicitly visited)

**Comment by juj** [comment] 2021-11-18 15:23
>     * iframe gets no GPU info; in all honesty I'd really like that iframe does not even get WebGPU or WebGL even. I've always hated iframe and it is the most susceptible to abuse.

This would unfortunately not be possible, for at least two major reasons:
 1. iframe is the only sandbox mechanism available to web developers. All major web gaming portals (Facebook, itch.io, Kongregate, etc.) are 100% based on iframe. Likewise for all web ad frameworks. All dynamic cross-origin content are loaded inside iframes to be able to restrict their access to the parent site context, and other web APIs available to it.
 2. Web has a decades old wide-standing problem that most web specifications are written to be "initialize-only" with no well-defined unload/deinit/shutdown semantics. ( https://github.com/WebAssembly/threads/issues/176 is the most recent example that I can recall) Web APIs are often specced from a perspective of only being meant to be loaded in, and either don't have a way to deinitialize, or deinitializing is implicit with GC (which is notoriously hard to develop to work, because general JS programming is filled with closures, and a very innocent-looking newly introduced closure can from-a-distance accidentally keep alive very unexpected chains of the site, and [different browsers have different behaviors with respect to what is referenced alive by which APIs](https://bugzilla.mozilla.org/show_bug.cgi?id=1540101)). The only sure way to unload web content is to wrap it inside an iframe and kill the iframe.

Restricting an iframe to not be able to query WebGPU device info would mean that none of the big gaming portals will able to benefit from reliability and optimizations. If they are using e.g. Unity web builds, having the carefully placed Adreno-3xx-crashes-or-is-super-slow-on-doing-X checks fall through whenever Unity web build content gets deployed on Facebook, and not get caught by game devs when testing locally would be a disaster. (they wouldn't even know they'd be missing out, since there are multiple code authoring parties involved)

>     * a webpage wants more info it can issue a request to ask for it and the browser makes a dialogue box asking for the info

Half a decade ago I was a big proponent of this as well, though ever since the cookies & gdpr site UX fiasco I have begun to sway in the other direction. Web sites have proven to create really bad experiences with these kinds of permission queries, and even if it is a browser-defined popup, it will be then be one more popup to see on a page, and web pages will mutate the experience to a vomit-inducing dumbed down "please accept the dialog above for an optimized and reliable site experience to continue." messaging. Users should not be asked to opt in to get reliability or optimization, but that is what would possibly happen with introducing popups.

**Comment by toji** [comment] 2021-11-18 16:09
iframes are _both_ a useful tool and a potential source of abuse, so while we don't want to limit them entirely it is a good idea to offer pages control on how they are used. Fortunately there are already mechanisms in the web platform for dealing with it!

Using the Permissions Policy spec that I linked earlier, you can control what features an iFrame embedded in your page has access to, like so:

```html
<iframe src="https://example.com/embed" allow="geolocation"></iframe>
```

This would create an iframe that explicitly allows geolocation features, which would be necessary if you were, say, embedding a map, but not if you were embedding a social media "like" button. You can see the current list of which features can be controlled this way here: https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md

**Comment by doug-moen** [comment] 2021-12-07 17:25
The experts who are in charge of privacy, security and fingerprint prevention in web browsers need to be told in no uncertain terms that it is 100% guaranteed impossible to prevent fingerprinting when the WebGPU API is used. They need to stop asking the WebGPU designers to solve this problem for them.

The responsibility for preventing fingerprinting needs to be removed from the WebGPU spec, and pushed upstairs, because it can only be solved at a level above WebGPU. It's great that we are having a discussion about webappsec-permissions-policy as it applies to iframes, because that sounds like an appropriate level where this problem could be solved. But this is outside the scope of WebGPU.

**Comment by krogovin** [comment] 2021-12-07 19:57
The truth is that as soon as JS is running, fingerprinting can happen. The debate is really coming down to this: does WebGPU pretend to prevent fingerprinting by not providing GPU data or does it make developer's life easier by providing the data. Desperate developers (i.e. all graphics developers) will find a way to compute the GPU anyways (at cost of battery and developer pain).

**Comment by doug-moen** [comment] 2021-12-07 20:48
What's needed is a GPU finger printing API that directly addresses the needs of graphics developers in choosing control paths based on bugs, the behavioural variation allowed by the standard, and performance differences. The discussion we should be having is: what does this API look like? Should it be a tuple identifying GPU vendor, GPU architecture, model ID, driver name and version? Or can we design a capability-based fingerprint that is generally useful across apps? (The answer is probably: both.) It would be better to incorporate this API directly into WebGPU, but if that's not politically possible, then it could be developed in a separate open source library.

Also, I think it would be great if there was more direct representation from experienced graphics developers on the WebGPU design committee. I know that the committee has been working with developers, soliciting feedback, and I appreciate that, but there seems to be a bit of a communications gap on this issue.

**Comment by krogovin** [comment] 2021-12-08 08:28
If the GPU is not identified, the alternative will come down to:
- listing bugs of a GPU and driver _**known**_ by the browser
- listing performance idiosyncrasies  of a GPU and driver _**known**_ by the browser

Which is not really going to fly very well since different complicated graphics application will hit different bugs and performance issues on different GPU's. The browsers essentially track the issues they encounter in rendering 2D content. 

The part that I find really frustrating about the entire conversation here is that once one has JS and a graphics API, the device can be fingerprinted anyways. Thus, not providing that data does not prevent any fingerprinting but just makes life a pain. Worse, if the data is not provided, libraries to perform GPU fingerprinting will be developed.

**Comment by doug-moen** [comment] 2021-12-08 16:52
@krogovin I agree with what you said.

BUT as an indy (single person) developer,
* I don't want to have to test the GPU identifier directly in my own code. This goes against what makes WebGPU compelling to me: an easy to use, high level, *portable* API that lets me code against a single interface and deploy to desktops, mobile and web. I don't have the resources to test my code against all of the popular GPU/driver/platform combinations, and write 'if GPU-id then' code that works on all those combinations. Any such code that I did write would only work reliably with machines I have personally tested.
* Litherium's assertion that I should simply "observe if the bug actually occurs" is insane. This code is not easy to write, and may have a serious performance cost, as others have noted. With WebGPU set to become the universal high level GPU API, I hope that this will lead to the availability of high level WebGPU libraries, so I don't have to code everything from the ground up. How do these libraries "observe if the bug actually occurs"?
* The biggest problem with this suggestion: once you start writing behavioural testing code to fingerprint a GPU, then you are engaged in an arms race against the browser makers, who will be looking for live examples of behavioural testing code on the web, and updating their browsers to prevent the code from working.
* What I want is a standard GPU capability database that lets me write *portable* code for working around bugs, behaviour and performance variances. Using this standard database, I can write code that is impervious to problems that I haven't experienced in my own testing. Testing the GPU ID directly (as opposed to indirectly through a high level 3rd party library) is a last resort that I would only use reluctantly.

You are right that we can't expect browser developers to provide this capability database. They aren't game developers, they don't have the knowledge or expertise to know what capabilities need to be listed.

So maybe this GPU capability database should be a third party open source project. It will test the GPU id and populate a capability database. To make this code simple and efficient, WebGPU should provide an API exposing a GPU ID in a format that facilitates this.

**Comment by kenrussell** [comment] 2021-12-08 17:53
Folks, please be respectful. Derogatory comments about others' statements are not acceptable.

I'm not sure that continuing this conversational thread will be fruitful at this point. Let me suggest closing this issue in favor of deciding on a better framework for exposing GPU information in #2195 .

**Comment by krogovin** [comment] 2021-12-08 18:20
I don't know what was disrespectful by anyone.

@doug-moen has a pretty good point that it is a major PAIN to test against GPU ID to make work arounds. I admit that the idea of a bug database sounds really nice, but the way GPU and driver bugs come up, the manifestations of bugs is really hard to describe ... often shader compiler bugs are immensely hard to isolate to a simple case (and that is even when knowing the implementation of the shader compiler!). Hardware bugs can be even more tricky to specify (they are hard to isolate in a driver and oodles much harder to isolate from application).

I think that the promise that "it will just work" is not the the case for dealing with GPU's unless one is doing relatively simpler things. Cutting edge techniques with cutting edge features is where so much pain is at typically.

**Comment by kenrussell** [comment] 2021-12-08 18:34
Saying that so-and-so's point of view "is insane" is disrespectful and won't be tolerated in our community.

**Comment by krogovin** [comment] 2021-12-08 20:39
I suppose I can see that; however, I don't think closing the discussion from that single line is proportional. Others had objected to the same point, but with nicer words.

I have found the discussion quite educational for myself, in particular the responses from @toji and @juj about iframes have made me realized that iframes have their important uses and shutting them out which I advocated is not a feasible (or even a good idea).

I do admit that the closing of the issue leaves a very bad taste in my mouth.

**Comment by greggman** [comment] 2021-12-09 23:51
My 2¢, 

Back in the WebGL days I was also very much against providing this info. My position was browsers should work around the bugs or blacklist the drivers. My position changed though as I saw both how many bugs there are and how long it takes for a work around to reach end-users.

### Devs need the info otherwise they can't support their customers.

Some website that uses GPU (WebGL or WebGPU) needs to support all of its users. If one day a driver is updated and 5% of their users can no longer use the site, it's not reasonable to tell them "We'll work on this and maybe in 3 to 6 months we'll have a workaround for those users." In the meantime what are they supposed to do? Some will say "test, if the test fails then don't use that feature", but is it really an acceptable solution to tell them to add .5 to 3 seconds of startup time to their app for all users just so it doesn't have issues on those 5%? And what if, as others have found, there is no good and performant way to test for the issue?

### Parsing strings considered harmful

Let me also get more controversial though, after seeing this set of bugs ([chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1171998), [firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1655285), [safari](https://bugs.webkit.org/show_bug.cgi?id=213622)) I'm leery of returning a string that could in any way be parsed. I'd push for either a record of separated values `{vendor: "Intel", device: "32"}` with no spaces, periods, dashes, underscores nor mixed alphanumerics. In other words, anything returned must pass this regular expression `/^[A-Za-z]+|[0-9]+$/` so there's nothing to parse (no "Intel 630", no "NVidia234", no "32.0.12". Or, arguably better, just ints. `{vendor: 0x8086, device: 0x3e9b}`. If we let devs parse they will parse and they'll parse incorrectly.

I get the concern that some dev might go do

```
const kNVIDIA = 0x10DE;
if (gpuAdaptor.vendor === kNVIDIA) {
  // do fast thing
} else {
  // do slow thing
}
```

But to me that's a self solving problem as they're intentionally giving some of their customers a bad experience and therefore it's bad for their bottom line so it seems eventually self correcting, one way or another.

### Fingerprinting

As others have pointed out, to some degree these APIs lets you fingerprint without this info. I tested an iPhone6S+, iPhone11Pro and iPhone13Pro on WebGL and all 3 returned different results for filtering such that without a device ID I could tell which was which, this is even without adding in limits (maxTextureSize etc...) to the signature. Adding in that info increased the fingerprinting, and of course, adding in screen.width, screen.height, preferred language, local time, prefered color scheme, and other device specific things, even without the device info it would be pretty easy to fingerprint. That's not to say we shouldn't try to prevent fingerprinting, but like others have suggested, if your browser is trying to prevent fingerprinting it has to happen at a higher level (let the user disable the API, prompt the user, let the user set per site permissions, etc....) The absence of vendor/device is not some magic bullet that fixes this issue.

**Comment by kainino0x** [comment] 2021-12-11 01:31
> But to me that's a self solving problem as they're intentionally giving some of their customers a bad experience and therefore it's bad for their bottom line so it seems eventually self correcting, one way or another.

I absolutely agree with this. Devs doing suboptimal vendor/device checks was one of the points Myles brought up against exposing vendor/device info. While I agree it's a problem, it's absolutely dwarfed by the need for developers to access (even limited) vendor/device info in order to serve their users. In particular:

> 2\. if (adapter.name.indexOf("NVIDIA") != -1) { /* enable bells and whistles because we know we're on a fast device */ }

We can't guard against all bad code on the entire internet. We make significant efforts to prevent people from writing code that **looks OK but works poorly**. This code doesn't look OK - it's obviously bad, and I don't think we should worry about guarding against it.

> #2195 is a really great example of a developer doing it wrong. They're trying to say "if I'm on Nvidia Kepler, use this shader which I've pre-optimized for that architecture" without any thought as to devices that are not Nvidia Kepler. What happens if the Nvidia-Kepler-optimized shader runs faster on M1? They should be saying "does X shader run faster than Y; if so, use X."

I don't think it should be our business to prevent developers from doing this. If there were no detriment, sure, but the value of vendor/device info to developers has been conclusively shown. Firstly, the detriment of this scenario occurring is minuscule: the code will just run a bit less optimized on some hardware. I think it will almost never be more than a small performance difference - architecture specific optimizations are *extremely* sensitive to the exact architecture (for bank conflict optimizations for example). And the hardware that benefits is going to be inherently rarer, because those developers who are optimizing for particular architectures _already_ are the same ones who are testing on diverse architectures.

**Comment by litherum** [comment] 2022-01-06 23:54
https://twitter.com/adamdbradley/status/1479210939425636355 :(

**Comment by kdashg** [comment] 2022-01-22 01:25
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-01-19#gpuadaptername-considered-harmful-2191-timebox-20m">WGSL meeting minutes 2022-01-19</a></summary>



* (And discuss [Brandon's proposal](https://github.com/gpuweb/gpuweb/issues/2195#issuecomment-992739992) in Exposing GPU hardware information to web developers in WebGPU [#2195](https://github.com/gpuweb/gpuweb/issues/2195))
* BJ: we have the #2191 post, going over reasons why Apple didn't want to expose GPU name, but more generally identifying info for the GPU. Other issue linked here is proposals for how we could expose GPU info in a more user friendly way, and less immediately fingerprintable way.
* BJ: for the group right now, I think over the course of these discussions we've expressed pretty well the reason for this information. So whether we expose any information at all about the GPU is probably well discussed. I think we could close #2191 and focus on concrete proposals. For people concerned about fingerprinting (everybody?), focus on exposing the info in a way as user centric / privacy preserving as possible.
* MM: I don't think we should close #2191. Reason: I don't understand why we have 2 issues in the first place. 1 discussion with 2 issues. Closing half of the issues doesn't make sense either.
* MM: we have relaxed a little bit since last discussion. Previously position I described is that we should not expose this for initial version, but wait for devs to tell us they need it in WebGPU. Now we're willing to have this discussion before V1 ships, but only if TAG / PING (ideally those two, but not necessarily specifically them) are involved.
* MM: one option - there's a spectrum - one result is, no browser exposes any information. That's one end of the spectrum, but it is on the spectrum. We shouldn't close out any concern until we've consulted with experts.
* KG: what forum would that be in?
* MM: historically - held in joint meetings. Two groups will join the same call. Doesn't have to be that way.
* KG: this sounds reasonable to me. There's a desire for more expertise from people who we'll need to satisfy anyway. Shouldn't have too prolonged a discussion here if we have to take it to another group and have the discussion again there.
* KG: to that end, it sounds like the first step - the PING, rather than the TAG. Sounds like their reason for being.
* KG: concurrently, useful to brainstorm ideas. Maybe don't get caught up on making a decision when we aren't the final decision makers.
* BJ: seems reasonable reflection of how I'd like it to go. My experience with the TAG has been that most effective communication with them is putting up a proposal, or a couple of different options and saying: here's the direction we're trending, and let them critique. Don't want to figure out all technical details if we think it'll change. But if they can see where our thinking's going it'll facilitate the conversation better.
* KG: don't want to invite them to join a debate. Point well taken.
* MM: at one point there was a proposal in this group - timestamps or similar- didn't know the form it would take, moved into a separate document, then planned to move back - that would be valuable from our point of view.
    * related: [https://github.com/gpuweb/gpuweb/pull/2301](https://github.com/gpuweb/gpuweb/pull/2301)
* KG: is this something we could use branches for, or other docs / explainers in the repo?
* MM: we don't have any opinion about that.
* BJ: I've seen explainers used successfully for that in the past. Focused on a single topic. It's conducive to bouncing ideas off groups like the TAG.
* KG: good idea. Don't want TAG to have to trace through our massive spec just to handle this issue. Will have to go to them with the whole thing eventually. Like the idea of a separate explainer.
* MM: it'd be an explainer instead of what's currently in the spec right now.
* KG: was imagining it, we point them to the explainer and say ignore what's in the spec right now. Do you want to affirmatively remove things from the spec first?
* MM: just because there's a prior example. I think it was pipeline statistics. We have 3 different proposals.
* BJ: I think GPU name exists in the spec today. I don't' have any particular opposition to removing that. Don't think anyone will implement what's in the spec right now. Pulling up the explainer in its place seems reasonable. I'm happy to draw up a first draft of the explainer unless someone wants to jump in. Will pull in the discussions so far, why we want the feature, and a skeleton of a proposal, and we can discuss it in the group before going to the PING.
* MM: sounds reasonable. This is an issue we've discussed "maximally" - we've talked up and down the management chain in our company. Have come up with 17 different ways it could work. I've intentionally refrained from proposing them because I didn't want to have the discussion. But since we've relaxed a bit, writing that document would be helpful, but we'll probably add a bunch to it before the TAG/PING get involved.
* KG: suggest to make this a HackMD or Google Doc rather than initially a text file in the repo for ease of initial collaboration. That way we don't need tons of PRs - need brainstorming.
* MM: if I understand correctly - we agree that Brandon will start writing a document, then I'll make a tentative PR removing GPUAdapter.name and add a comment pointing to the discussions in the other document.
* KG: I'll talk with Corentin and Domenic about reaching out to the PING.


</details>

**Comment by toji** [comment] 2022-01-24 17:26
As requested during the last call, I've put together an explainer capturing my proposal from #2195 and put it up as a HackMD document for easy collaboration here: https://hackmd.io/@Toji/S1rvjZD6t

As we discussed, the goal should be to use this document to work out any broad issues with the proposal as a group (For example, I expect the exact structure of the interface we return will undergo some changes vs. what I've put there initially.) Then, once any large concerns have been addressed we'll loop in the PING and work out the remaining details with their input.

**Comment by toji** [comment] 2022-01-26 21:06
At @litherum's request in today's call, the above document has been mirror into this repo at https://github.com/gpuweb/gpuweb/blob/main/design/AdapterIdentifiers.md to facilitate pull requests.

**Comment by Kangz** [comment] 2022-04-26 12:47
Tentatively closing since the [explainer](https://github.com/gpuweb/gpuweb/blob/main/design/AdapterIdentifiers.md) landed and the group agreed that it is a possible direction forward. Works is now happening in iteration of the [GPUAdapter identifiers PR](https://github.com/gpuweb/gpuweb/pull/2660).

**Closed by Kangz** 2022-04-26 12:47 UTC
