### ISSUE TITLE
wgsl: Restrict `modf` and `frexp`pointer parameter storage classes

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#1846] opened 2021-06-16 19:27 UTC
Attempting to generate HLSL for `modf` or `frexp` when the pointer is to a storage buffer is extremely messy to implement, due to storage buffers likely being implemented as a `RWByteAddressBuffer`.

For non-intrinsic functions, [we restrict the pointer types](https://www.w3.org/TR/WGSL/#function-restriction) to `function`, `private` and `workgroup` storage classes.

We should probably do the same for the `modf` and `frexp` intrinsics.

Note: This is a non issue if we go with https://github.com/gpuweb/gpuweb/issues/1480 instead

**Comment by ben-clayton** [comment] 2021-07-08 11:19
It also seems that MSL is missing overloads of some of these intrinsics for pointer parameters of `workgroup` (`threadgroup`) storage class.

**Comment by kvark** [comment] 2021-07-08 14:55
Right, I just tried that and got `No matching function for call to 'frexp'`:
```cpp
kernel void testShader(threadgroup int& param) {
    int other;
    frexp(4.4, other); // passes
    frexp(4.4, param); // fails
}
```

**Comment by jdashg** [comment] 2021-09-23 00:17
Dupe of  #1851?

**Closed by jdashg** 2021-09-23 00:17 UTC
Labels: wgsl
