### ISSUE TITLE
Task: Samplers

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#668] opened 2020-04-01 03:37 UTC
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

The spec needs to define samplers.

See also: https://github.com/gpuweb/gpuweb/issues/573

**Comment by dj2** [comment] 2020-04-01 12:40
Duplicate of https://github.com/gpuweb/gpuweb/issues/574

**Closed by dj2** 2020-04-01 12:40 UTC
Labels: wgsl
