### ISSUE TITLE
Resource Capabilities

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#37] opened 2017-11-02 02:12 UTC
## Background
Direct3D 12 and Vulkan have the concept of a resource which has a set of (conceptual) capabilities.

In one example, there may be a resource in these APIs which exists in a region of memory which the CPU can access, but is slow to use on the GPU. There may be another resource in these APIs which is fast to use on the GPU, but the CPU cannot access.

In another example, there may be a texture in these APIs which is tiled such that it can be sampled from in a fragment shader, but CPU-side code wouldn't know where to read/write data to update the contents of the texture (because the exact nature of the tiling is undefined). There may be another texture in these APIs which is not tiled so its contents can be updated by the CPU, but the fixed-function sampling hardware used in the fragment shader cannot sample from it.

Because a resource may not have all the capabilities an application requires, it is common practice to create "staging" resources. When an application wants to, for example, use the CPU to write to a texture which doesn't have CPU access, it writes to a staging texture that does have CPU access, and then enqueues a GPU command to copy the data from the staging texture to the destination texture. Indeed, this is so common that Direct3D 12 itself even has a [helper function](https://msdn.microsoft.com/en-us/library/dn899212(v=vs.85).aspx) for it.

## Recommendation
The WebGPU API should not have a concept of individual resource capabilities. Instead, every WebGPU API resource should have the same set of capabilities, which includes CPU reading and writing, GPU reading and writing, sampling, etc. On platform APIs where no such resource is available, the browser will need to use staging resources. This is possible because each CPU-side access will be associated with a particular point in the device's command queue (there was consensus during the Nov. 1 call about this). This point is the point where the runtime may emit GPU-side copy commands or synchronization commands.

There are a few reasons for this approach:
1. **Convenience** Developers of existing APIs use staging resources because they have to, not because they want to. If every developer is going to have to emit commands to use these staging resources, the browser should just do it for them.
2. **Portability** On some devices (for example, UMA devices), staging buffers are entirely unnecessary. On other devices (for example, discrete desktop graphics cards), staging buffers are a requirement to have good performance. The web developer should not be writing code which works on the device they're testing on, but doesn't work on other types of devices. The browser knows much more about the currently-running hardware than the web author.
3. **Performance** In an API which has a concept of resource capabilities, poorly-authored applications may use resources in a non-optimal manner. For example, a poorly-authored application might upload once into a CPU-visible resource, and then only sample from it every frame thereafter from the GPU. Removing the API concept of resource capabilities gives the browser the freedom to move the resource to a faster region of GPU memory.
4. **Fingerprinting** The properties of resource capabilities are intrinsic to the raw hardware of the device running the web application. The web platform has avoided giving hardware-specific knowledge to any running webpage.

**Comment by Kangz** [comment] 2017-11-02 20:35
Having all resources have all capabilities would be ideal but it isn't possible in practice.

For textures a problem would be that a texture with all capabilities would require more memory than a more constrained texture. That's why all APIs, and even Metal (in MTLTextureDescriptor) ask the developers to pre-declare what usage they will make of the texture. See for example [Intel's Vulkan driver's `make_surface` function](https://github.com/mesa3d/mesa/blob/master/src/intel/vulkan/anv_image.c#L260) where each call to `add_surface` increases the memory footprint of the texture.

Like you, I was hoping that we could make all buffers have all capabilities. However in Vulkan a buffer's usage influences which memory heaps it can live in. Another [example from Intel's driver](https://github.com/mesa3d/mesa/blob/master/src/intel/vulkan/anv_device.c#L157): vertex and index buffers have to live in a heap that's less than 4GB so there can be a small 1GB heap that allows all usages, and a bigger heap that allows all usages but vertex and index. If buffers had all capabilities, one of two things. Either we would have to allocate buffers in the small heap, running out of memory fast. Or we would allocate buffers in the big heap and have to migrate at runtime if it turns out the buffer is used as a vertex buffer.

The compromise we chose in NXT is that the developers have to declare for each resource which usage they might make of it, then the NXT implementation does all the querying and allocating in heaps on its own. This changes your proposal from "all resource have all capabilities" to "all resources can have all capabilities" and keeps the advantages you listed.

About avoiding the need for staging resources, is this your proposal? [`void HostAccessPass::overwriteBuffer(Buffer& buffer, const std::vector<uint8_t>& newData)`](https://github.com/WebKit/webkit/blob/master/Tools/WebGPUAPIStructure/WebGPU-Common/WebGPU.h#L266)
In order to be well ordered with other commands, all the implementations will have to copy the data in a staging buffer internally then enqueue a copy in the command stream. This is one CPU copy worse than if the application mapped a staging buffer, wrote data to it directly then scheduled a copy. In addition we're always going to need a staging resource when doing texture updates from the CPU because the application cannot know the shape of the swizzling.

(I intentionnally ignored vkCmdUpdateBuffer and Metal's set[Vertex|Fragment]Bytes that should be used for small amounts of data only)

What we suggest we do is expose buffer mapping in a way that's guaranteed to not race with the GPU as well as convenienve functions to update buffer data right now. This way application can choose the most efficient path when they want to, but are still able to quick'n'dirty "update a buffer right now". We haven't spent enough time thinking about UMA yet so there's some use-cases where we don't have the optimal number of copies yet. (CPU-decode video, triple-buffered uniform buffer updates etc.). See the NXT [data uploads investigation](https://docs.google.com/document/d/1Mi9l14zG8HzJ5Z6107SdPhON0mq4d-3SUI8iS631nek/) and ["Buffer mapping" section of the NXT overview](https://docs.google.com/document/d/1-lAvR9GXaNJiqUIpm3N2XuGUWv_JrkpGizDN0bNq7wY/edit#heading=h.shn3dklme5oq) for more details. This is heavy document re-use and I can make a proper "proposal" document instead of you want.

**Comment by litherum** [comment] 2017-11-02 21:47
I think we're discussing two separate issues:
1) Can a WebGPU resource be represented by multiple platform-level resources
2) Is it possible for the CPU to access a buffer when the GPU is using it

My intention was for this issue to be about the first one. I recommend opening a second issue for the second issue.

**Comment by Kangz** [comment] 2017-11-03 17:55
Agreed, and I was mostly trying to discuss 1) with the opinion that a single WebGPU resource should correspond to a single backing resource. In the first half of the answer I tried to explain why a 1-1 mapping will require the applications to declare what usage it will make of resources. And in the second half I argued against implicit staging resources that are per-resource and instead think that mapping + one staging buffer in the device is enough (which ties into 2) a little bit).

What I didn't make clear is that with what I suggested, we keep the advantages you listed:

 - **Convenience**: Declaring usage ahead of time should be easy because hopefully the developer knows if they will use a texture as a render-target or not when you create it. Uploading to a buffer "right now" is valuable for debugging etc and I agree it should be part of the API, which should keep the convenience there.
 - **Portability**: With usages declared things are even more portable. Resource updates or just as portable.
 - **Performance**: On UMA systems there are still some resource upload cases that don't have a portable optimal number of copies. But what you suggested didn't either so we still need to work that out.
 - **Fingerprinting**: The application doesn't query the system so there are no concerns there.

**Comment by kvark** [comment] 2017-11-06 16:15
@litherum 

> Indeed, this is so common that Direct3D 12 itself even has a helper function for it.

D3D12 has a helper function in order to assist migration from D3D11 (which had an equivalent [UpdateSubresource](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476486(v=vs.85).aspx)). I don't see this approach being idiomatic to D3D12 or Vulkan.

> This is possible because each CPU-side access will be associated with a particular point in the device's command queue (there was consensus during the Nov. 1 call about this). 

Hmm, I don't recall this being a consensus, but rather just a proposal from your side (even though might connection was flaky). How does this make sense in the presence of multiple hardware queues?

As for @Kangz 's proposed approach (declaring the capabilities up-front) - I believe it is sound.
We should also consider explicit memory types discovery/binding like Vulkan model does. In short, this would imply:
  - device exposes multiple types of memory mapped to multiple memory heaps. We can omit the notion of the latter for now, focusing on the memory types only.
  - user declares an image or a buffer that is not attached to any memory. Device provides the requirements for the allocation size, alignment, and the mask of supported memory types (!).
  - user allocates memory chunks of particular memory types (one memory allocation may then contain multiple resources)
  - user binds declared resources to the allocated memory, after which the resources can be used for rendering/computing
  - mapping is done at the memory allocation level (`VkDeviceMemory`) as opposed to resource level (like D3D12/metal)

Finally, about our priorities. *Convenience* should probably be discussed last, not first. *Fingerprinting* deserves a dedicated policy before we'd use it for more specific API aspects like this one. In particular, exposing different queues and their capabilities would also be a fingerprinting issue. In general, it seems to be conflicting with low-level API approach. Thus, if we as a group declare fingerprinting an issue to solve in scope of *Security*, that would force us to sacrifice performance and adopt a higher-level API direction that is more abstracted and opaque to scanners.

**Comment by kvark** [comment] 2019-02-27 18:57
I believe this issue is becoming actual again, now that the buffer uploads are merged and we have the MAP_READ/MAP_WRITE usages, users would try (well, I tried) to create buffers that can do a lot, and the backends don't necessarily support that directly.
@Kangz what is the plan for exposing those usage combinations that are valid?

**Comment by Kangz** [comment] 2019-02-27 19:40
What combination / backend doesn't work? I believe the Vulkan spec guarantees that you can create buffers that do everything.

**Comment by kvark** [comment] 2019-02-27 19:49
@Kangz upon further reading on Vulkan spec, I can confirm your belief:
> If buffer is a VkBuffer not created with the VK_BUFFER_CREATE_SPARSE_BINDING_BIT bit set, or if image is linear image, then the memoryTypeBits member always contains at least one bit set corresponding to a VkMemoryType with a propertyFlags that has both the VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT bit and the VK_MEMORY_PROPERTY_HOST_COHERENT_BIT bit set. In other words, mappable coherent memory can always be attached to these objects.

So this is indeed not a problem, at least for Vulkan and Metal (phew!).

**Comment by Kangz** [comment] 2021-09-02 11:47
Tentatively closing this since the CPU read/write capabilities of resources has coalesced in WebGPU. `writeBuffer` and `writeTexture` also solve some of the problem this was (I believe) trying to solve. We can open a new issue based on the current state of the spec for further proposals.

**Closed by Kangz** 2021-09-02 11:47 UTC
