### ISSUE TITLE
Development-only API features

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#814] opened 2020-05-27 20:56 UTC
> I think these values are intended to measure relative complexity of different parts of applications and get insights into the GPU operations while performance tuning. So how about add description to reminder users like this:
> Note: These values are intended to measure relative statistics generated by operations of the device. Be careful to use these values in the release version of applications, because various device architectures may count these values differently.

_Originally posted by @haoxli in https://github.com/gpuweb/gpuweb/issues/794#issuecomment-634608095_

Hypothetically, if we were to create a class of API features that are only for development (have to be enabled by the end user, e.g. through a dev-tools UI), what could we put in that class? I think we should seriously consider having such a class, so we can provide useful tools without creating portability and fingerprinting hazards.

- Pipeline statistics queries
- Higher precision timers (if we lower the precision of timers)
- Source-mapped shader error locations (file/line/column) (probably unnecessary, apps can do userspace source mapping)
- Synchronously-thrown validation errors
- Possibly additional error information, e.g. more detailed/fingerprintable error messages
- Other fingerprintable things?
- ?

**Comment by kainino0x** [comment] 2020-05-27 20:59
Having these features exposed to the application (instead of just adding dev tools, or designing write-only APIs like debug labels) allows web developers to develop additional custom tooling around the features in an engine/application-specific way.

**Comment by kvark** [comment] 2020-05-28 17:06
I agree that these features are good to offer to users in some way, but not by default. They need to opt into this somehow, with a permission prompt, or by flipping a "dev mode" switch on the browser.
And the rigor level of specification for these can be much lower, therefore, than for the main spec. These two aspects made me suggest to have it separately, in https://github.com/gpuweb/gpuweb/issues/794#issuecomment-635466957.

**Comment by kainino0x** [comment] 2020-05-28 17:31
I considered a permission prompt, but we don't want sites actually prompting users. It would have to be a reject-by-default permission that users can manually enable. And if it's going to be that, I think it should be hidden in dev tools.

**Comment by kainino0x** [comment] 2020-05-29 20:21
This isn't an API feature, but implementations should consider an end-user-enabled option to pass any debug names into the underlying driver. This would reduce concern about the need to sanitize debug names for security in #784.

**Comment by litherum** [comment] 2020-06-01 18:20
See: https://github.com/w3ctag/design-principles/issues/209

**Comment by kainino0x** [comment] 2020-06-01 19:09
It doesn't expose whether dev tools is open; it exposes whether the dev tools user has enabled a particular option which is off by default. There are already at least options where it *can* be detected (such as "Disable Cache" which is necessary for page load performance testing).

**Comment by kainino0x** [comment] 2021-02-01 21:01
Meeting: Resolved to keep timestamp queries as an optional feature in the core spec doc, enabled for all users, but with quantization for privacy (and the expectation that a compute shader will run to do the quantization and unit conversions).

I don't think we had a resolution on pipeline statistics queries as none of us are very confident about who needs them / when they need them.

**Comment by jdashg** [comment] 2021-02-01 21:02
I think we may be able to just quantize pipeline stats too.

**Comment by kainino0x** [comment] 2021-02-01 21:04
> * Source-mapped shader error locations (file/line/column) (probably unnecessary, apps can do userspace source mapping)

Not needed for reason stated.

> * Synchronously-thrown validation errors

Not needed because dev tools can implement "Breakpoint on error" instead of this.

> * Possibly additional error information, e.g. more detailed/fingerprintable error messages
> * Other fingerprintable things?

Up to the user agent.

**Comment by kvark** [comment] 2021-02-01 21:15
The conclusion from todays call was: we can ship them in WebGPU, but spec in a way that allows (and suggests) the processing of the results (by pipeline statistics and timestamps) by a compute shader.
My main concern with this is: how do we specify what the values are? How do we test it?

For example, if there isn't a test for them, can an implementation return ticks instead of seconds for the timestamp? (Obviously, when running in a trusted development environment, not hostile).

**Comment by kainino0x** [comment] 2021-02-02 00:32
I don't think we can practically conformance-test it. But we could try to write a test that warns if performance.now() time deltas aren't in the same ballpark (after unit conversion) as timestamp query deltas.

**Comment by litherum** [comment] 2021-02-02 01:09
> For example, if there isn't a test for them, can an implementation return ticks instead of seconds for the timestamp?

I think the spec should specify the units of the number, and the unit should be an SI unit (not ticks).

> (Obviously, when running in a trusted development environment, not hostile).

If a browser wants to expose ticks inside their development tools, they can go right ahead.

**Comment by Kangz** [comment] 2021-02-02 12:59
> I think the spec should specify the units of the number, and the unit should be an SI unit (not ticks).

Forcing nanoseconds means that we are forced to use a compute shader in Vulkan and D3D12 even when the browser chooses to give the application high-precision timestamps. This could change the timings a bit compared to the production usage so I think it would be much better to have the API expose ticks and have a tick-to-ns scalar somewhere on the `GPUDevice` or `GPUAdapter`.

Of course browsers are still free to use a compute shader to convert to ns when they need to (Metal's linear regression stuff) and to quantize the values when they expose the feature without wanting to give high-precision timers.

**Comment by kvark** [comment] 2021-02-02 14:18
I'm still a bit concerned about the API for the timestamps and pipeline statistics. If the idea is "we expose it, but it may not do anything", then I think there is a problem: both of these would end up in GPU buffer data, which can be fed easily to the shaders or indirect draw calls. So having the data in the GPU buffers *encourages* the use of the data that's not an intended use, according to our latest discussion.

The main problem @Kangz raised on the call was: how can an user build a RenderDoc-style debugger/profiler for WebGPU?
And this use case wouldn't require the quirky resolve data to be in GPU buffers. Therefore, I think we have an opportunity here to make it better, and to resolve the "tick vs ns" debate once and for all.

How about we make these developer features only resolve to the CPU side? I.e. basically expose `vkGetQueryPoolResults`:
```idl
interface QuerySet {
  promise<sequence> resolve(u32 start_query, u32 queryCount);
}
```

This would mean we can spec it in actual time, and the constant multiplication and quantization are done by CPU.

**Comment by Kangz** [comment] 2021-02-02 14:49
> I'm still a bit concerned about the API for the timestamps and pipeline statistics. If the idea is "we expose it, but it may not do anything", then I think there is a problem: both of these would end up in GPU buffer data, which can be fed easily to the shaders or indirect draw calls. So having the data in the GPU buffers encourages the use of the data that's not an intended use, according to our latest discussion.

That's an extremely unlikely usecase and even less likely than usage of occlusion queries for the same type of GPU-driven logic, and it would only work in developer-mode or have different results between developer-mode and regular mode. If developers are doing this I think it's ok to expect them to take into account a tick to ns conversion.

If the browser does quantization for example with milliseconds (like it's done for performance.now in Firefox I believe), it makes the result of timestamp queries completely unusable as they try to measure things that are in the order of microseconds in some cases.

That's why I don't think timestamp queries or pipeline statistics will be exposed outside of "developer mode" in Chromium so there's no reason to make them special-cased (or with redundant resolve paths) to make them slightly easier to use correctly.

**Comment by litherum** [comment] 2021-02-03 02:05
If Chrome wouldn't implement the spec's notion of timestamp queries (i.e. exposed to the web at large), why does Chrome have an opinion on whether or not the spec requires nanoseconds vs ticks?

**Comment by Kangz** [comment] 2021-02-03 11:27
The intent is not that Chromium will not implement the spec's notion of timestamp queries. What I'm asking is that the specification doesn't force the usage of compute shaders on D3D12 and Vulkan where there is no guarantee that the ticks are nanoseconds (contrary to Metal running on Apple GPU which wouldn't need a compute shader).

At the same time I'm asking that we stop routinely breaking new ground with WebGPU by adding new ways to do things that aren't in other APIs (async resolving of queries doesn't exist anywhere), because that has multiple costs including delaying when WebGPU can get released.

**Comment by Kangz** [comment] 2021-11-10 20:16
Resolved: we can have some APIs as separate non-normative documents.

**Closed by Kangz** 2021-11-10 20:16 UTC
