### ISSUE TITLE
Buffer Offset issue in buffer-texture copies with depth stencil textures

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#3185] opened 2022-07-18 06:25 UTC
On Windows10 (Version 10.0.19042.1645) Intel Skylake GPU (HD530, i7-6700K, 0x1912) with latest Intel driver (30.0.101.1994) , when we call CopyTextureRegion() to copy between a depth stencil texture and a buffer at a non-zero offset, a device lost will occur when offset is not a multiple of D3D12_TEXTURE_DATA_PLACEMENT_ALIGNMENT (512), but such issue cannot be reproduced on Intel Gen12 GPUs (Win11) or Nvidia 2080Ti (Win10 Version 10.0.19044.1706).

I think there are two options:
1. Add a restriction on the 'offset' parameter of  buffer-texture copies with depth stencil textures (offset must be a multiple of 512)
2. On the affected platforms, implement such buffer-texture copy into two copies with an internal buffer so that we can ensure the offset of the internal buffer passed in CopyTextureRegion() is always a multiple of 512. 

More discussions can be found through [this link](https://bugs.chromium.org/p/dawn/issues/detail?id=727).

For example, when running below D3D12 code, D3D12 debug  layer will generate an error.
```C++
// The format of depthTexture is DXGI_FORMAT_D16_UNORM, and its size is {1, 1, 1}
// The valid data in uploadBuffer is at offset 2 and 3.
 D3D12_RANGE range = { 0, 8 };
void* mappedUploadBufferPtr = nullptr;
uploadBuffer->Map(0, &range, &mappedUploadBufferPtr);
uint8_t* uint8Ptr = static_cast<uint8_t*>(mappedUploadBufferPtr);
uint8Ptr[2] = 204;
uint8Ptr[3] = 204;
uploadBuffer->Unmap(0, &range);

D3D12_TEXTURE_COPY_LOCATION textureLocation, uploadBufferLocation;
textureLocation.pResource = depthTexture.Get();
textureLocation.Type = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;
textureLocation.SubresourceIndex = 0;

uploadBufferLocation.pResource = uploadBuffer.Get();
uploadBufferLocation.Type = D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;
uploadBufferLocation.PlacedFootprint.Offset = 0;
uploadBufferLocation.PlacedFootprint.Footprint.Width = 4;
uploadBufferLocation.PlacedFootprint.Footprint.Height = 1;
uploadBufferLocation.PlacedFootprint.Footprint.Depth = 1;
uploadBufferLocation.PlacedFootprint.Footprint.Format = DXGI_FORMAT_D16_UNORM;
uploadBufferLocation.PlacedFootprint.Footprint.RowPitch = 256;
D3D12_BOX region = {};
region.left = 1;
region.right = 2;
region.bottom = 1;
region.back = 1;
commandList2->CopyTextureRegion(&textureLocation, 0, 0, 0, &uploadBufferLocation, &region);
```

The error message is as below:
```
D3D12 ERROR: ID3D12CommandList::CopyTextureRegion: Resources with either DXGI_SAMPLE_DESC::Count greater than 1 or that use 
D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL can only copy the entire subresource at a time, where the subresource dimensions 
must match. pSrcBox must be NULL, or specify the entire subresource. The source subresource 1 samples. The destination 
subresource has 1 samples. pSrcBox left is 1, top is 0, front is 0, and all must be 0; right is 2, bottom is 1, and back is
1. But, the source subresource has 4 width, 1 height, and 1 depth. [ RESOURCE_MANIPULATION ERROR #873: 
COPYTEXTUREREGION_INVALIDSRCBOX]
```

**Comment by Kangz** [comment] 2022-07-18 14:33
Note that in the latest D3D12, there is an optional feature that drivers can expose that signals that these alignment restrictions are no longer applied: [`UnrestrictedBufferTextureCopyPitchSupported`](https://devblogs.microsoft.com/directx/agility-sdk-1-602-0/#buffer-texture-copy-pitch-and-offset-alignment). Because of this, because basically all hardware that supports D3D12 also supports Vulkan, and because Vulkan doesn't have such a restriction, I think we should go with 2) and skips the extra copy when `UnrestrictedBufferTextureCopyPitchSupported` is true.

**Comment by kainino0x** [comment] 2022-07-20 04:42
To clarify, am I correct in understanding that this isn't a driver bug, but a limitation of an older D3D12 spec that has been (optionally) lifted in newer versions of D3D12?

**Comment by jenatali** [comment] 2022-07-20 19:32
This is a limitation that's relaxed by the [programmable MSAA](https://microsoft.github.io/DirectX-Specs/d3d/ProgrammableSamplePositions.html#copy-depthstencil-partial-subresource) feature, rather than `UnrestrictedBufferTextureCopyPitchSupported`. The error message pasted above isn't about the 512-byte alignment, it's about the source box specifying a portion of the depth texture.

Support for that can be detected by [`D3D12_FEATURE_DATA_D3D12_OPTIONS2`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_feature_data_d3d12_options2)`::ProgrammableSamplePositionsTier` not being set to `D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_NOT_SUPPORTED`.

**Comment by kainino0x** [comment] 2022-07-20 20:04
Meeting: resolved to not change spec, workaround with copy (IIUC only required when neither programmable MSAA nor UnrestrictedBufferTextureCopyPitchSupported is supported)

**Comment by kainino0x** [comment] 2022-07-20 20:05
Does the CTS have tests for the case that would require that copy or do we need to add them?

**Comment by Kangz** [comment] 2022-07-20 20:06
> Meeting: resolved to not change spec, workaround with copy (IIUC only required when neither programmable MSAA nor UnrestrictedBufferTextureCopyPitchSupported is supported)

Actually waiting on confirmation from @jimblandy or @cwfitzgerald for wgpu.

**Comment by kainino0x** [comment] 2022-07-20 20:18
Oh yes, tentatively resolved.

**Comment by magcius** [comment] 2022-07-24 02:19
I'm confused. The attached Direct3D 12 code does not use a buffer offset (it assigns `PlacedFootprint.Offset = 0`), and uploads a sub-region rectangle which is definitely not allowed under Direct3D 12.

Texture copies to buffers have always required an alignment of 512 on D3D12, and I feel that copyTextureToBuffer with a buffer offset is unique & special-case enough that we can mandate that in the specification. What would this workaround copy look like? Creating a new temporary buffer resource, copying to it, and then copying to the destination buffer?

**Comment by Kangz** [comment] 2022-07-25 07:55
> I'm confused. The attached Direct3D 12 code does not use a buffer offset (it assigns PlacedFootprint.Offset = 0), and uploads a sub-region rectangle which is definitely not allowed under Direct3D 12.

(copy pasted answer from Matrix): In D3D12 to do copies between buffers and textures, you do a copy between two textures, one that's the real texture and one that's laid out linearly in in the buffer. The constraint is that the offset of the first pixel in that texture must be alignment to 512. The bug is that it's possible to work around it for color textures but not for depth-stencil because you need to copy whole resources.

> What would this workaround copy look like? Creating a new temporary buffer resource, copying to it, and then copying to the destination buffer?

Exactly, unless the D3D12 device supports some optional features that make this workaround not needed.

**Comment by jimblandy** [comment] 2022-07-25 17:19
Implementing the intermediate-buffer workaround shouldn't be a problem for Firefox.

**Comment by Kangz** [comment] 2022-08-02 15:52
Closing as agreed to in the meeting since Mozilla confirmed it'd work for them.

**Closed by Kangz** 2022-08-02 15:52 UTC
Labels: needs-cts-issue

**Comment by lokokung** [comment] 2022-11-30 01:59
Removing 'needs-cts-issue' label with update under draft issue named: `op: command_buffer,image_copy`
