### ISSUE TITLE
support blending 32 bit float textures

### ISSUE THREAD

**Issue by mighdoll** [gpuweb/gpuweb#3556] opened 2022-10-30 21:45 UTC
32 bit float textures are available as blendable render targets via an extension in webgl 1 and webgl 2, but not in webgpu. See WEBGL_color_buffer_float, EXT_color_buffer_float, OES_texture_float.

Without 32 bit blend support, webgpu web apps are at a disadvantage compared to webgl. 16 bit floats may introduce unacceptable inaccuracies e.g. for scientific visualization. 

Without 32 bit blend support, I suppose it’s possible to reorient rendering to blend in workgroup tiles. But that seems likely to be slower, complicated, and limited by the lack of floating point atomics.

(An older comment in the webgpu chat claimed that apple silicon doesn’t support 32 bit float textures. Is that true? 32 bit float textures work on my current m1 mac, and an older intel mac I checked. https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf suggests support on older silicon as well.)

**Comment by kdashg** [comment] 2022-10-31 04:39
Unfortunately, no AppleN generation listed in those tables claims to support "Blend" for RGBA32Float, though they do support Blend for RG32Float and R32Float. Only "Mac" supports Blend for RGBA32Float.

**Comment by mighdoll** [comment] 2022-10-31 05:29
that's great news! r32float is the format I'd want most. I can imagine that other computational uses would also be happy with one or two channels. Shoehorning single channel data into 4 channel textures is a big hassle in webgl. Great that webgpu r32float support could potentially extend to older devices.

**Comment by kainino0x** [comment] 2022-10-31 16:40
I queried https://github.com/kainino0x/gpuinfo-vulkan-query relative to what's required for core WebGPU, and got these results:

```py
    def blendable(info, fmt):
        return format_supported_with_optimal_tiling_features(info.fmts, fmt, vk.FormatFeature.COLOR_ATTACHMENT_BLEND)
    add_rq('r32float blend', lambda info: blendable(info, vk.Format.R32_SFLOAT))
    add_rq('rg32float blend', lambda info: blendable(info, vk.Format.R32G32_SFLOAT))
    add_rq('rgba32float blend', lambda info: blendable(info, vk.Format.R32G32B32A32_SFLOAT))
```

```
Requirement "r32float blend" loses 19 (and partially loses 3) further deviceNames:
  In ALL reports (19 deviceNames):
    x Adreno (TM) 504: 6 (8629 9137 10642 11160 11664 12378)
    x Adreno (TM) 505: 26 (4259 4457 4489 4824 6129 7394 7550 8516 8922 9025 9063 9355 9501 9798 10174 10776 11057 11789 12203 12269 12277 12342 13211 14230 14771 14913)
    x Adreno (TM) 506: 48 (3851 4541 4680 4724 4916 4956 5006 5250 5990 6044 6058 6151 6814 7023 7137 7612 8841 9054 9060 9935 10294 10314 10414 10431 10513 10542 10810 10941 10997 11017 11346 11423 11493 11526 11656 12201 12360 12454 12578 12618 12636 12785 12953 13423 13426 13508 13618 14282)
    x Adreno (TM) 508: 9 (4452 6680 8652 10383 10442 10589 12379 13414 14872)
    x Adreno (TM) 509: 14 (4924 6120 8358 9062 9064 11486 11487 11488 11673 11820 12108 12678 13230 14911)
    x Adreno (TM) 510: 1 (6786)
    x Adreno (TM) 512: 38 (3724 4394 4400 4683 4768 5679 6063 6787 7385 8566 8697 10195 10204 10546 10608 10638 10656 10700 10775 11177 11237 11326 11399 11452 11475 11605 11663 11933 12813 13364 13421 13578 13616 13837 14233 14625 14716 14916)
    x Adreno (TM) 530: 48 (3183 3597 3603 3765 3907 4359 4363 4773 4999 5019 5103 5210 5314 5399 5402 6072 6100 6215 6285 6560 6841 6885 7313 7542 7601 8268 8483 8544 9061 9332 10486 10681 10827 10838 10958 11034 11724 11874 12263 13278 13802 13934 13964 14311 14312 14364 14491 15081)
    x Adreno (TM) 540: 63 (3422 3450 3532 3571 4071 4145 4433 4503 5102 5150 5215 5259 5383 5632 5811 5866 6046 6068 6083 6163 6208 6405 6796 7584 8603 8977 9008 9251 9354 9705 10284 10347 10597 10728 10752 10784 10786 10819 10844 10908 11101 11225 11338 11350 11485 11498 11665 11669 12292 12489 13097 13246 13294 13482 13577 13751 14142 14175 14369 14844 15188 15241 15257)
    x Mali-G52: 6 (10194 11056 11982 12062 14045 14925)
    x Mali-G57 MC3: 1 (13858)
    x Mali-G610: 1 (15222)
    x Mali-G610 MC6: 1 (15244)
    x Mali-G68 MC4: 1 (15101)
    x Mali-G710 MC10: 3 (14684 14922 15223)
    x Mali-G72: 48 (2742 3448 3781 3863 4392 4602 4756 4871 5540 6158 6561 6593 6839 7335 10185 10297 10316 10409 10500 10561 10593 10737 10797 10922 10933 11060 11071 11078 11188 11226 11267 11313 11330 11537 11559 11660 12179 12319 12371 12372 12427 12742 13255 13521 13785 14167 15084 15242)
    x Mali-G76: 26 (5370 5374 5917 6110 6227 6737 7441 9760 10520 10553 11165 11601 11649 11650 11848 11853 12326 12373 12894 13326 13822 14108 14263 14563 14701 15110)
    x Mali-G77: 14 (8046 9711 10290 10312 10346 10643 11929 12347 12879 13607 13648 13668 13818 14609)
    x Mali-G78: 13 (10390 10395 10699 11648 12368 12788 12851 13091 13271 14501 14514 15142 15143)
  In SOME reports (3 deviceNames):
    ~ Adreno (TM) 615: 3 of 15 (5944 6088 7898; ok: 6436 7927 8903 9147 9184 9422 10427 11275 12085 12583 12996 13171)
    ~ Adreno (TM) 616: 5 of 14 (4986 5287 6492 9756 11712; ok: 7806 10393 10604 11072 12858 13327 13564 14753 14828)
    ~ Adreno (TM) 630: 48 of 110 (2801 3024 3138 3305 3442 3665 3687 3754 3755 3795 3810 3927 4134 4140 4249 4270 4366 4403 4413 4486 4525 4563 4599 4628 4632 4915 4926 5175 5253 5800 6032 6038 6056 6107 6162 6234 6266 6704 6996 7057 8585 8951 10285 11026 12775 13424 13749 13963; ok: 5886 6434 6788 6987 7108 7374 7949 8473 8577 8907 9097 9267 9471 10287 10291 10300 10302 10303 10351 10371 10424 10460 10551 10672 10678 10730 10770 10813 10966 11016 11035 11120 11464 11602 11670 11695 11914 11922 12213 12280 12363 12429 12430 12667 13256 13428 13552 13642 13675 13676 13752 13991 14092 14393 14463 14523 14608 14610 14611 14717 14751 14806)
Requirement "rg32float blend" loses no further reports!
Requirement "rgba32float blend" loses no further reports!
```

The last line is curious, because this database has MoltenVK devices in it. I'm guessing this is a MoltenVK bug?

```
At least one of each of the following was still supported:
...
  + Apple M1
  + Apple M1 Max
  + Apple M1 Pro
...
```

**Comment by mighdoll** [comment] 2022-11-01 00:02
Interesting. So if I understand correctly, recent high spec laptops, desktops and iPads can support r32float blending. That's a pretty useful set of devices to target for computational visualizations.

**Comment by shmookey** [comment] 2022-11-30 17:16
To add to the scientific visualization case - just having the r32float support would be a great help for radio astronomy imaging, its absence is a pain point for me. Producing an image may involve blending many tens of thousands of layers generated in a single render pass, so blending them separately in a compute shader is impractical.

**Comment by mighdoll** [comment] 2022-12-05 01:47
+1, hoping for the r32float option. For our app, blending 32 bit floats is the only missing feature from webgl that is potentially blocking.

**Comment by teoxoy** [comment] 2023-02-15 20:22
Summary of backend support:

## D3D FL11

**DXGI_FORMAT_R32_FLOAT**
**DXGI_FORMAT_R32G32_FLOAT**
- Shader sample (any filter): Hardware support is required.
- Blendable RenderTarget: Hardware support is required.

**DXGI_FORMAT_R32G32B32_FLOAT**
- Shader sample (any filter): Hardware support optional; the format may or may not be hardware accelerated.
- Blendable RenderTarget: Required if a related optional feature is supported.

## Metal

**R32Float**
**RG32Float**
- Filter: Mac2
- Blend: All

**RGBA32Float**
- Filter: Mac2
- Blend: Mac2

## Vulkan

- SAMPLED_IMAGE_FILTER_LINEAR: loses all Adreno devices (https://github.com/kainino0x/gpuinfo-vulkan-query/commit/9e6ab0ef148449cdd57a528020fa3dba03e756cc)
- COLOR_ATTACHMENT_BLEND: loses Adreno 5XX devices and all Mali devices (https://github.com/gpuweb/gpuweb/issues/3556#issuecomment-1297367501)

---

_I also included filtering so that we can see if we should bundle the 2 capabilities together._

**Comment by kainino0x** [comment] 2023-02-16 00:55
Thanks for the investigation! I found the same results. Notably non-Mac Apple devices never support filtering \*32float or blending rgba32float.

Unfortunate about the weird disjointness of Adreno and Mali (Mali never supports blending, Adreno never supports filtering). But between that and the Metal results I guess that tells us we can't bundle them.

**Comment by kdashg** [comment] 2023-04-26 17:13
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/Minutes-2023-04-19#support-blending-32-bit-float-textures-3556">GPU Web 2023-04-19 Atlantic</a></summary>

* KR: fyi this is oft-requested support for WebGL. Only support gap is on some mobile hardware which only supports blending 16-bit floats.
* CW: Theo was keen on this one as well.
* KG: we're not pushing this too hard. Not having this represents a regression compared to WebGL.
* KG: use cases presented in the bug so far are folks asking us for a feature that they'll rely on exclusively in their app, rather than being portable - worrisome to us.
* KN: think we have the data we need in the issue. Metal doesn't have RGBA32F blending on mobile. Has to be a separate capability. Don't know the OpenGL story for that format.
* KG: people do use 1-channel textures.
* KN: one person wanted R32F. Could add RGBA32F, but significantly less interesting since it misses iOS.
* KG: wish we could ask for a feature optionally. Warn on desktop - you asked for this, and it's commonly unavailable on mobile.
* MM: you can do that - request 2 devices.
* KG: we don't know the requests are related.
* MM: don't we have other optional features that don't have widespread support?
* KG: yes - not saying no to this proposal, but would be nice to have the app's intent - that they have a fallback path in place.
* MM: could imagine an API structure for this.
* KG: for this concretely - Moz's internal consensus is, that since WebGL has this, we should have it.
* MM: totally fine if there are extensions that don't run on iOS. Bar for optional features is - are there 2 or more impls they run on. 
* KG: nobody's objecting, so if anyone wants this, they can make a proposal.
* CW: on our side, need to discuss a bit more exactly what the use cases are. RGBA32F not being blendable might be the customers' key concern.

</details>

**Comment by mwyrzykowski** [comment] 2023-09-27 19:33
It would be ideal to support R, RG, and RGBA independently as iOS devices can blend R and RG 32bpp float

**Comment by greggman** [comment] 2023-10-14 19:47
I see `float32-blendable` listed here: https://github.com/gpuweb/gpuweb/issues/2630#issuecomment-1738242408

But just thought I'd add, this feature exists in WebGL and is currently missing from WebGPU


https://web3dsurvey.com/webgl2/extensions/EXT_float_blend

**Comment by mighdoll** [comment] 2023-11-08 19:17
Thanks for adding this to the Milestone 1 plans. Yea!

**Comment by kainino0x** [comment] 2024-09-06 21:46
Ah, this is another one of those things where there's a runtime query for it even though it seems like it should be a static capability. I didn't notice the footnote in the feature set tables (if it was there before).

Actually, I can't understand what that footnote is saying at all:

> The GPUs in the Apple7, and Apple8 families that support the Filter and Resolve (or All) texture capabilities for floating-point pixel formats[1] also support float filtering[2]. You can check an individual
GPU’s support for this feature by inspecting the MTLDevice.supports32BitFloatFiltering property at runtime.

- [1] In the table, none of the `*32Float` formats support Filter _or_ Resolve on Apple7 or Apple8 (only Apple9).
- [2] This seems tautological. What is the difference between "support Filter for floating-point pixel formats" and "support float filtering"? Docs say:
    > supports32BitFloatFiltering
    > A Boolean value that indicates whether the GPU can filter a texture with a 32-bit floating-point format.

---

> @kainino0x are you aware of android devices which support R or RG 32-bit floating point blending but not RGBA? If not, we wouldn't need to separate R/RG from RGBA

There don't seem to be any (that are relevant to us, at least, as of 2022). The report [above](https://github.com/gpuweb/gpuweb/issues/3556#issuecomment-1297367501) says:

```
Requirement "r32float blend" loses 19 (and partially loses 3) further deviceNames:
  ...
Requirement "rg32float blend" loses no further reports!
Requirement "rgba32float blend" loses no further reports!
```

Which says: among devices that support r32float blend, all of them also support rg/rgba32float blend.

**Comment by mwyrzykowski** [comment] 2024-09-06 21:57
> > The GPUs in the Apple7, and Apple8 families that support the Filter and Resolve (or All) texture capabilities for floating-point pixel formats[1] also support float filtering[2]. You can check an individual
> > GPU’s support for this feature by inspecting the MTLDevice.supports32BitFloatFiltering property at runtime.
> 
> * [1] In the table, none of the `*32Float` formats support Filter _or_ Resolve on Apple7 or Apple8 (only Apple9).

It means, and indeed I think it is worded wrong or at least in a confusing way, that if `MTLDevice.supports32BitFloatFiltering` is true, then you can filter and resolve that format. I will suggest a rewording since it reads to me like so stated, which is not accurate.

> * [2] This seems tautological. What is the difference between "support Filter for floating-point pixel formats" and "support 

> 
> Which says: among devices that support r32float blend, all of them also support rg/rgba32float blend.

Oh that's great, so we could limit the extension to e r\*32float blending. I guess it would also be interesting if we can combine the r\*32float filtering with r\*32float blending, as we just ran across a case of a site today trying to use blending on an RGBA32Float texture in WebGPU.

**Comment by kainino0x** [comment] 2024-09-06 23:19
> I guess it would also be interesting if we can combine the r*32float filtering with r*32float blending, as we just ran across a case of a site today trying to use blending on an RGBA32Float texture in WebGPU.

Sadly (and weirdly), we can't:

> Unfortunate about the weird disjointness of Adreno and Mali (Mali never supports blending, Adreno never supports filtering).

**Comment by kainino0x** [comment] 2024-09-06 23:24
BTW, regarding filtering, we already landed the `float32-filterable` feature which combines r/rg/rgba32float filtering (issue #3601).

The outcome of new information about filtering would just change whether it gets exposed on iOS or not. (IIUC apple silicon Macs should all support `float32-filterable` because they're in the Mac2 family.)

**Comment by kainino0x** [comment] 2024-09-25 22:28
@mwyrzykowski were you able to confirm that any target Metal devices with r/rg32float blending would also have rgba32float blending? (not filtering)
If so then we'd like to propose adding a `"float32-blending"` feature which covers all three: #4896

**Comment by mwyrzykowski** [comment] 2024-09-25 23:10
> @mwyrzykowski were you able to confirm that any target Metal devices with r/rg32float blending would also have rgba32float blending? (not filtering) If so then we'd like to propose adding a `"float32-blending"` feature which covers all three: #4896

Yes, it confirmed via testing that anywhere r32float or rg32float blending is supported, rgba32float blending is supported, which is all GPU families from the Metal feature sets table.

**Closed** 2024-10-09 18:14 UTC
Labels: texture-capabilities, api

**Comment by mwyrzykowski** [comment] 2024-10-09 18:17
Shall we remove this from the F2F agenda since this is completed @kainino0x ?

**Comment by Kangz** [comment] 2024-10-09 18:34
I removed it!

**Comment by mwyrzykowski** [comment] 2025-06-12 22:10
The documentation is now updated :)
https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf

<img width="963" alt="Image" src="https://github.com/user-attachments/assets/ebd64c03-18d3-4797-8980-ccf8085aa24d" />
