### ISSUE TITLE
Task: Invent a standard library

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#667] opened 2020-04-01 03:36 UTC
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

The spec currently has no notion of a standard library. We need to find the intersection of library functions from HLSL, MSL, and SPIR-V, and specify them in the spec.

Regarding the polyfillable functions: We also need to make a determination about how much polyfilling the implementation is required to do, vs how much polyfilling the author is required to do.

**Comment by litherum** [comment] 2020-04-04 05:24
Here's a spreadsheet I made when designing WSL's standard library: [Shading Language Standard Libraries.numbers.zip](https://github.com/gpuweb/gpuweb/files/4430797/Shading.Language.Standard.Libraries.numbers.zip) This compares the facilities in all the 3 compilation targets. It's probably a good place to start from.

**Comment by Jasper-Bekkers** [comment] 2020-04-06 12:42
I'm not sure how to view the `.iwa` files in that archive. But I have a few comments;

Since WHLSL is more or less an IL (bijective to SPIR-V after all) having a standard library as such probably isn't extremely useful, however it'll need to define a bunch of operations no matter which way you put it. 

Having these operations be the set intersection of operations that HLSL, MSL and other support is probably a mistake. In a lot of the cases you can't the just map operations directly to the compilation targets to begin with. Take the trig functions you've highlighted for example; some of these are occasionally hardware accelerated (take cos/sin on GCN for example) some of the target languages make different guarantees about the precision and range of various ops, so you'll most likely want to define your own each with their own precision and guarantees.

Similarly some of these map directly to control flow (and how they map to control flow is crucial in various corner cases - think of OpKill in SPIR-V for example) so some of this will depend on #674 and #676 and potentially others as well.

**Comment by litherum** [comment] 2020-04-06 21:07
I wonder how much exact precision of trig functions matters for real applications.

**Comment by dneto0** [comment] 2020-04-06 22:13
For "library" functions GLSL and HLSL compile straightforwardly to SPIR-V plus the GLSL.std.450 extended instruction set.  (I'd have to check matrix operations.)
There might be some variation around bit reversal, popcount, detecting the top bit (e.g. reverse + ILsb). 

Floating point accuracy guarantees vary a great deal. As do treatment of denorms, signed zeros, and NaNs.
Generally "graphics" language play very fast-and-loose: basically -fast-math is the default.
 
OpenCL took the opposite tack, trying to address the HPC market, and thus followed more traditional rules that C provides (fp operations not associative etc.).  OpenCL requires pretty tight error bounds for fp math library functions, on FULL_PROFILE, but relaxes those error bounds for EMBEDDED_PROFILE.

**Comment by Jasper-Bekkers** [comment] 2020-04-06 22:24
> I wonder how much exact precision of trig functions matters for real applications.

As someone that's worked in this field for a while, and has had to spend a few good nights debugging issues because platform vendors changed various trig approximations let me assure you that these things matter a lot :-)

> I don't think SPIR-V nor HLSL defines exact IEEE754 compliance for all operations, so there's at least some precedence to leave some amount of wiggle room in the spec.

One does not exclude the other, having precision guarantees for trig and other operations is crucial. The guarantees don't need to be strictly "every op within 1ULP", but one needs to be able to reason around then and rely on them.

**Comment by Jasper-Bekkers** [comment] 2020-04-06 22:27
> Floating point accuracy guarantees vary a great deal. As do treatment of denorms, signed zeros, and NaNs.
> Generally "graphics" language play very fast-and-loose: basically -fast-math is the default.

While that is true, and fast math will keep being the norm, nobody wants to update their render test suite everytime chrome or safari push an update.

**Comment by litherum** [comment] 2020-04-07 08:02
Not even ECMAScript specifies precision of intrinsic math functions. https://www.ecma-international.org/ecma-262/10.0/index.html#sec-function-properties-of-the-math-object It does require 64-bit IEEE floating point, but only fully specifies functions where the exact answer falls out of IEEE.

**Comment by Jasper-Bekkers** [comment] 2020-04-07 08:43
> It does require 64-bit IEEE floating point, but only fully specifies functions where the exact answer falls out of IEEE.

So it does specify them is what you're saying?

Nobody is running massive rendering test suites where a large portion of the screen depends on the output of cos for example. Take normalmap compression (for gbuffer laydown) as an example of where transcendentals and their approximations are widely used, or equirectangular projection for skydome textures. Both of them extremely fault tolerant - you can afford some stretching or incorrect results as long as the approximations used are consistent; if every vendor has different ones and they change occasionally (or frequently) it does pose a problem. If you want to do a good job, this is one of the aspects that you'll need to get right.

**Comment by magcius** [comment] 2020-04-07 09:10
> Not even ECMAScript specifies precision of intrinsic math functions.

Right. It's been pointed out that the following is a completely valid implementation of Math.sin, according to the ECMAScript specification:

```js
Math.sin = function(x) {
    if (x === Infinity || x === -Infinity)
        return NaN;
    return x;
};
```

Real-world bugs have been caused by precision issues in sin/cos. Most famously, this one: https://bugs.chromium.org/p/v8/issues/detail?id=3006

**Comment by grorg** [comment] 2020-06-16 18:19
Discussed at the [2020-06-16 meeting](https://docs.google.com/document/d/11RW9hpfzSvZYpLGBm3uhKwoXDvJI42N7jWP_nOB-k2E/).

@litherum will come to next week's F2F will a collection of stdlib functions from D3D, Vulkan and Metal.

**Comment by litherum** [comment] 2020-06-23 17:57
Sorry for being late.

Here are some logical groupings of functions that we could have in the first version of a standard library:

### Trigonometry

- `acos()`
- `asin()`
- `atan()`
- `atan2()`
- `cos()`
- `cosh()`
- `sin()`
- `sincos()`
- `sinh()`
- `tan()`
- `tanh()`

### Vector

- `all()`
- `any()`
- `cross()`
- `determinant()`
- `distance()`
- `dot()`
- `faceforward()`
- `length()`
- `normalize()`
- `reflect()`
- `refract()`
- `transpose()` (Does this really belong here?)

### Barrier

_See https://github.com/gpuweb/gpuweb/issues/862_
- `AllMemoryBarrierWithGroupSync()`
- `DeviceMemoryBarrierWithGroupSync()`
- `GroupMemoryBarrier()`
- `GroupMemoryBarrierWithGroupSync()`

### Reinterpretation

- `as<>()`

### Math

- `ceil()`
- `abs()`
- `clamp()`
- `popcount()`
- `exp()`
- `exp2()`
- `clz()`
- `ctz()`
- `floor()`
- `fma()`
- `fmod()`
- `fract()`
- `frexp()`
- `isfinite()`
- `isinf()`
- `isnan()`
- `ldexp()`
- `mix()`
- `log()`
- `log10()`
- `log2()`
- `max()`
- `min()`
- `modf()`
- `pow()`
- `radians()`
- `reverseBits()`
- `round()`
- `rsqrt()`
- `saturate()`
- `sign()`
- `smoothstep()`
- `sqrt()`
- `step()`
- `trunc()`
- `isFinite()`
- `isInf()`
- `isNan()`
- `isNormal()`

### Derivatives

_Note the lack of the `Coarse` versions_
- `dpdx()`
- `dpdy()`
- `width()`

### Atomic

_Deferred to https://github.com/gpuweb/gpuweb/issues/673_

### Texture

_Deferred to https://github.com/gpuweb/gpuweb/issues/573_

### Quad

_Deferred to https://github.com/gpuweb/gpuweb/issues/78_

### Pack

- `packFloatToSnorm4x8()`
- `packHalfToSnorm4x8()`
- `packFloatToUnorm4x8()`
- `packHalfToUnorm4x8()`
- `packFloatToSnorm2x16()`
- `packHalfToSnorm2x16()`
- `packFloatToUnorm2x16()`
- `packHalfToUnorm2x16()`
- `unpackSnorm2x16ToFloat()`
- `unpackSnorm2x16ToHalf()`
- `unpackUnorm2x16ToFloat()`
- `unpackUnorm2x16ToHalf()`
- `unpackSnorm4x8ToFloat()`
- `unpackSnorm4x8ToHalf()`
- `unpackUnorm4x8ToFloat()`
- `unpackUnorm4x8ToHalf()`

**Comment by litherum** [comment] 2020-06-23 18:11
(See https://github.com/gpuweb/gpuweb/issues/600#issuecomment-648330186)

**Comment by johnkslang** [comment] 2020-06-23 18:29
Vulkan does not pin down everything, but GLSL, Vulkan, and OpenGL all share pretty closely what the Vulkan spec. lays out in Appendix A, under "Precision and Operation of SPIR-V Instructions".  Trig is missing, but there is quite a lot said, which can be leveraged, and the parts said are quite far from being fast-and-loose.

**Comment by grorg** [comment] 2020-06-23 20:11
Discussed at the [2020-06-23 Virtual F2F meeting](https://docs.google.com/document/d/1WI9PzwXy39fFHuZLUnEQtSplwfmFaZ2oVb0gXJsA2P4/)

**Comment by dneto0** [comment] 2020-06-23 20:28
Thanks for collecting this.

I'd like a standard way of doing conversions between   2xHalf into uint32 and back.
In SPIR-V, these are 

* PackHalf2x16   :  converts 2 floats into 2 half values, then cram them into 32-bit uint
* UnpackHalf2x16: goes the other way.

From https://www.khronos.org/registry/spir-v/specs/unified1/GLSL.std.450.html

There are also details to handle, e.g. denorms.

**Comment by dneto0** [comment] 2020-06-23 22:49
To me `as<>` is core to the language, like reinterpet_cast is in C++.

The other ones do fall into nice nameable categories that I think we should consider preserving.

* trig
* sync (for barriers and atomics)
* bits (for clz, ctz, reversebits, popcount)
* pack
* fp  (frexp, ldexp, signbit, isinf, isfinite, isnan, isnormal, step)
* math (sqrt, trunc, floor, ceil, mix, pow, fma, fmod, exp, log,   ...)
* vector (length, normalize, ...)

This is related to potentially versioning subsets of the "standard" library. See option 7a in https://github.com/gpuweb/gpuweb/issues/600#issuecomment-648413521

**Comment by johnkslang** [comment] 2020-06-24 08:39
`transpose()` could be a matrix function, if you want a matrix category, which potentially also includes:

- vector X matrix
- matrix inverse
- determinant

If no matrices, then no `transpose()`.  SPIR-V classifies `transpose` as a memory operation.

**Comment by Kangz** [comment] 2021-11-16 11:28
WGSL has a fairly comprehensive standard library at the moment. Could we close this and track further work in individual issues such as #2130 ?

**Closed** 2022-02-08 20:59 UTC
Labels: wgsl
