### ISSUE TITLE
Add support for 3D compressed textures.

### ISSUE THREAD

**Issue by mrshannon** [gpuweb/gpuweb#3183] opened 2022-07-15 17:16 UTC
In #1522 it was decided to not support 3D compressed textures until someone came up with a strong case for why it is needed.

In our engine we use 3D compressed textures as part of the volumetric cloud system. Naturally these are decently large textures (being 3D) which is where compressed textures can really be beneficial. On desktop BCn compression easily reduces these volumetric textures to a quarter of their uncompressed size, with ASTC 3D block footprints giving even better reductions on mobile. Given memory limitations on many devices (and browsers) we need to take any compression advantages we can get.

**Comment by julhe** [comment] 2022-09-26 17:32
I think there are actually quite some use cases where 3D compression would be beneficial:

- Flipbooks (like for pre-computed fire or smoke)
- Signed Distance Fields
- Pre-Computed procedural noise (Perlin and such)
- 3D Lightmaps

I think it's also realistically to say that no support for 3D compression will force users to emulate 3D with compressed 2D slices, which has worse performance, bandwidth and space usage.

**Comment by kainino0x** [comment] 2022-09-29 00:33
This is great, thank you! We'll definitely be considering this feature again after V1 is complete.

**Comment by kainino0x** [comment] 2024-03-29 00:42
Bumped by issue #4537. I will retriage this into M2 I guess, since I _think_ it will go in core?

I'll make a quick note here: the 3d compressed formats (like 3x3x3) barely exist (Vulkan doesn't even have an extension for them), so I don't think we're likely to pursue them anytime soon.

Using 2d compressed formats with 3d is relatively straightforward though.

**Comment by kainino0x** [comment] 2024-03-29 00:43
"needs investigation" into what the backend support for this is (so, whether it will be core or not - I'm pretty sure it's widespread enough that it warrants inclusion in the first place)

**Comment by mehmetoguzderin** [comment] 2024-03-29 01:45
@kainino0x Does that mean this issue has milestone 2 for 2D compressed blocks supporting 3D textures and taking 3D blocks out of consideration? Or does that mean this issue will be multiple steps for compressed 3D textures as a whole, first solving 2D compressed blocks feature regression here, not closing, and re-triaging for future 3D blocks? I think this issue makes an excellent point for 3D blocks, following up on the issue preceding this, but as we point out here and the issue I recently made, there is a lack of support.

I will return an investigation into this matter in detail soon, but I just want to make sure that doing so does not discard a consideration of this issue.

Thank you.

**Comment by mehmetoguzderin** [comment] 2024-03-29 01:46
(and by this matter, I meant 2D compressed blocks for 3D textures, not entirety encompassing 3D compressed blocks)

**Comment by kainino0x** [comment] 2024-03-29 02:32
> Does that mean this issue has milestone 2 for 2D compressed blocks supporting 3D textures and taking 3D blocks out of consideration?

This one.

Upon quick investigation, _zero_ of our 3 target native APIs have support for 3D block ASTC formats. So they're a non-contender.

**Comment by mehmetoguzderin** [comment] 2024-03-29 02:36
@kainino0x Then I'll follow-up here, thanks a lot

**Comment by mehmetoguzderin** [comment] 2024-03-30 00:33
# Brief Investigation of Support for 3D Textures with 2D Compressed Blocks

The GPU APIs that power WebGPU have reasonable support for using 2D Compressed Block formats for 3D Textures. This support is a key enabler for many scientific visualization applications, though implications are broader given the bandwidth and storage gains. However, WebGPU API (currently) prohibits the creation of 3D Textures with 2D Compressed Block formats. For reference, please see: https://gpuweb.github.io/gpuweb/#texture-creation

In validation for 3d: "descriptor.format must not be a compressed format or depth-or-stencil format"

## Test Applet

With native APIs, I was using 3D Textures with 2D Compressed Blocks without any issues, so, to begin with, I thought of making a sample. But given how unproblematic it was for me for a long time, I thought maybe even WebGL 2 allows such use. I made an attempt in WebGL 2, and indeed, WebGL 2 as a starting point does not prohibit the use of 2D Compressed Blocks for 3D Textures for both BC and ASTC/ETC2 (hence, this validation causes an API-side feature regression for WebGPU with respect to WebGL 2):

![Untitled](https://github.com/gpuweb/gpuweb/assets/5333693/1b377679-e625-431d-b84e-e0b633accb86)

Since this example is just a test, it loads a very basic binary containing volumetric data with 2D Block Compression of either ASTC or BC7, depending on your device (caveat: for some reason, Firefox on M1 does not expose ASTC or BC7; hence, please try on WebKit or Chromium if you run macOS with Apple Silicon). The data is just a combination of spherical shells of varying radius and thickness.

```math
r_{\text{inner}, i} < \sqrt{(x - h)^2 + (y - k)^2 + (z - l)^2} \leq r_{\text{outer}, i}
```

To run this example, please clone, move into the directory, and serve the directory with an HTTP server such as `python -m http.server`: https://github.com/mehmetoguzderin/webgpu-202403-compress3d

## API Support

Given the concrete test of the API request, let's briefly list what underlying APIs tell us about their support, considering WebGPU targets from https://github.com/gpuweb/gpuweb/issues/1069 issue.

### Direct3D 12

Direct3D supports Texture3D up to BC7, starting from Feature Level 11. Please refer: https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/format-support-for-direct3d-11-0-feature-level-hardware#dxgi_format_bc7_unorm-fcc-98

I was not able to find the DXGI_FORMAT_ASTC_4X4_UNORM support value in these feature-level tables, and I don't have a device to test this.

### Metal

Metal supports "Compressed volume texture formats" for most devices except Common1/Apple2. Please refer: https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf

### Vulkan

For BCn, Vulkan is very clear for its compatibility: "Mandatory format support: BC compressed formats with VkImageType VK_IMAGE_TYPE_2D and VK_IMAGE_TYPE_3D". Please refer: https://docs.vulkan.org/spec/latest/chapters/formats.html#formats-mandatory-features-bcn

But for ASTC/ETC2, the same is "Mandatory format support: ETC2 and EAC compressed formats with VkImageType VK_IMAGE_TYPE_2D" without mention of VK_IMAGE_TYPE_3D. I could not find a further listing of VK_IMAGE_TYPE_3D support per hardware, but I came across this OpenGL page: https://www.khronos.org/opengl/wiki/ASTC_Texture_Compression#OpenGL_image_formats

> ASTC formats cannot be used for 1D textures or Rectangle Textures. They are able to be used with all other textures, including 1D Array Textures.

So, at least for OpenGL, the 3D Texture support is quite clear for ASTC.

## Conclusions

Given the existing case with WebGL 2 and support of underlying APIs, I think it only makes sense to change this validation to not block 2D Compressed Block formats for 3D Textures.

Last but not least, I would like to reiterate that in this comment, and hopefully, as a direction of progress, I just focus on 2D Compressed Blocks for 3D Textures, not 3D Compressed Blocks. That is not to ignore their benefit, but they are, unfortunately, not practical for the time being, given the underlying API situation.

Thank you for your consideration; I hope we can relax this validation rule to enable applications to run on WebGPU, empowering more use cases that WebGL 2 can already run with the integration of compute and more.

**Comment by kainino0x** [comment] 2024-04-24 02:57
There's a bunch of spec text that will need to be updated for this, but here's a little head start on finding them:
https://github.com/gpuweb/gpuweb/pull/4590/files#r1577170610

**Comment by Kangz** [comment] 2024-05-07 15:31
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-04-10#add-support-for-3d-compressed-textures-3183">GPU Web CG 2024-04-10 Atlantic-time</a></summary>

* MOD: In most of the native APIs we can use 2D compressed blocks for 3D textures. This is useful for scientific visualization. Already available in WebGL2. 
    * Metal: we don't target Apple2 or Common1 (?) feature sets any more
* CW: WebGPU - texture size has to be multiple of the block size. D3D constraint. Would carry over for 3D compressed textures using a 2D compressed texture format. But depth wouldn't have that constraint.
* JB: Moz thinks this is a relatively straightforward addition
* CW: this would be core
* JB: that's fine.
* BJ: in favor of anything that makes us not regress from WebGL. :)
* KN: reason we didn't do this initially is there were issues with 3D texture formats like 4x4x4, didn't do the work to understand what's supported. Now we know, those aren't supported anywhere.
* MW: think we should add compressed 3D texture support.
* CW: OK, now just need to implement, test, add to the spec.
* KG: PRs welcome. High-level approval.
* KN: need to test it. M1 target?
* CW: yes. Regression w.r.t. WebGL.
* JB: yes.
* CW: thanks for nice investigation, made things easy.

</details>

**Comment by teoxoy** [comment] 2024-05-29 15:00
> But for ASTC/ETC2, the same is "Mandatory format support: ETC2 and EAC compressed formats with VkImageType VK_IMAGE_TYPE_2D" without mention of VK_IMAGE_TYPE_3D.

This is what I found as well, there is also https://github.com/KhronosGroup/Vulkan-Docs/issues/926. My takeaway being that Vulkan doesn't require creation of 3D Textures with these formats to work but some drivers/hardware support it. There also doesn't seem to be a way to get the set of `VkImageType`s a particular format supports.

Despite the WebGL example above working on the main 3 browser engines, the WebGL extensions that add support for various compressed formats also don't mention 3D Texture support, only 2D.

[EXT_texture_compression_bptc](https://registry.khronos.org/webgl/extensions/EXT_texture_compression_bptc/)
[EXT_texture_compression_rgtc](https://registry.khronos.org/webgl/extensions/EXT_texture_compression_rgtc/)
[WEBGL_compressed_texture_astc](https://registry.khronos.org/webgl/extensions/WEBGL_compressed_texture_astc/)
[WEBGL_compressed_texture_etc](https://registry.khronos.org/webgl/extensions/WEBGL_compressed_texture_etc/)
[WEBGL_compressed_texture_etc1](https://registry.khronos.org/webgl/extensions/WEBGL_compressed_texture_etc1/)
[WEBGL_compressed_texture_pvrtc](https://registry.khronos.org/webgl/extensions/WEBGL_compressed_texture_pvrtc/)
[WEBGL_compressed_texture_s3tc](https://registry.khronos.org/webgl/extensions/WEBGL_compressed_texture_s3tc/)
[WEBGL_compressed_texture_s3tc_srgb](https://registry.khronos.org/webgl/extensions/WEBGL_compressed_texture_s3tc_srgb/)

The only extensions I could find that mention 3D Texture support for ASTC formats are the ones listed in the table of https://github.com/KhronosGroup/Vulkan-Docs/issues/926 and those are for OpenGL ES.

[KHR_texture_compression_astc_sliced_3d](https://registry.khronos.org/OpenGL/extensions/KHR/KHR_texture_compression_astc_sliced_3d.txt)
[KHR_texture_compression_astc_hdr](https://registry.khronos.org/OpenGL/extensions/KHR/KHR_texture_compression_astc_hdr.txt)
[OES_texture_compression_astc](https://registry.khronos.org/OpenGL/extensions/OES/OES_texture_compression_astc.txt)

Browsers are probably using the OpenGL ES extensions and not validating 3D Texture usage with these formats.
Or maybe the WebGL extensions meant to add support for 3D Texture usage as well?

**Comment by mehmetoguzderin** [comment] 2024-05-29 15:11
At least on the Apple M1 GPU that I can test, Metal permits 3D Textures with ASTC but blocks 3D Textures with ETC2. I don't have any other ARM device to test for the ETC2.

**Comment by mwyrzykowski** [comment] 2024-05-29 16:10
Indeed only ASTC and BC formats are supported for 3D compressed formats from my understanding

**Comment by kainino0x** [comment] 2024-05-31 03:41
Trying to summarize what's been discovered so far, with some judgement calls:

- D3D12 guarantees sliced-3D BC, and AFAIK never supports ETC2/ASTC even in 2D (despite the pseudo-existence of ASTC enums like `DXGI_FORMAT_ASTC_4X4_UNORM`. Maybe they're supported on Windows ARM?)
- Metal guarantees 3D compressed textures of some kind (starting with Apple3 and Mac1, which is lower than our requirements in #1069), though I don't know how to definitively determine which formats. It sounds like we're guessing it guarantees sliced-3D ASTC/BC, but never supports sliced-3D ETC2.
- Vulkan guarantees: (2D BC && sliced-3D BC) || (2D ASTC) || (2D ETC2).
  - This probably guarantees that if you have BC, then you have sliced-3D BC. I think technically you could have a device that supports 2D ASTC and 2D BC but not sliced-3D BC, but that seems very unlikely to exist.
  - We can infer from the existence of `GL_KHR_texture_compression_astc_sliced_3d` that Vulkan _will_ sometimes support sliced-3D ASTC.
  - Vulkan would allow an implementation to say it supports sliced-3D ETC2, but I think we can infer from the fact that no such extension exists in OpenGL ES that it's not common. Unfortunately, vulkan.gpuinfo.org doesn't capture fine-grained format capability data.

From all this, Oguz and I discussed and I think this was what we came up with:

1. Fix the spec to only allow sliced-3D with BC, not ASTC/ETC2. (#4685)
2. Introduce a feature for sliced-3D ASTC.
3. Probably not introduce a feature for sliced-3D ETC2 as it seems rare-to-nonexistent, but check some devices to see if they have it.

**Comment by mehmetoguzderin** [comment] 2024-06-01 09:32
@teoxoy There's a way to check with Vulkan but not as convenient as a bitfield (maybe there's such a convenient way I'm not aware of). Example output (I'd expect 1D with BC1 to not be supported but just illustrating):

```
Device 0: NVIDIA GeForce RTX 4060 Laptop GPU
Device supports BC1 RGB UNORM with 3D when optimal tiling
Device does not support BC1 RGB UNORM with 1D when optimal tiling
Device 1: Intel(R) Iris(R) Xe Graphics
Device supports BC1 RGB UNORM with 3D when optimal tiling
Device supports BC1 RGB UNORM with 1D when optimal tiling
```

Code:

```
#include <vulkan/vulkan_raii.hpp>

#include <iostream>
#include <vector>

int main(int argc, char *argv[]) {
  try {
    vk::raii::Context context;
    auto applicationInfo = vk::ApplicationInfo("vulkan-20240601-compress3d", 1,
                                               "vulkan-20240601-compress3d", 1,
                                               VK_API_VERSION_1_1);
    auto instanceCreateInfo = vk::InstanceCreateInfo({}, &applicationInfo);
    auto instance = vk::raii::Instance(context, instanceCreateInfo);
    auto physicalDevices = instance.enumeratePhysicalDevices();
    for (size_t i = 0; i < physicalDevices.size(); ++i) {
      auto properties = physicalDevices[i].getProperties();
      std::cout << "Device " << i << ": " << properties.deviceName << "\n";
      auto format = vk::Format::eBc1RgbUnormBlock;
      try {
        auto imageFormatProperties =
            physicalDevices[i].getImageFormatProperties(
                format, vk::ImageType::e3D, vk::ImageTiling::eOptimal,
                vk::ImageUsageFlagBits::eSampled, {});
        std::cout
            << "Device supports BC1 RGB UNORM with 3D when optimal tiling\n";
      } catch (vk::Error &err) {
        std::cout << "Device does not support BC1 RGB UNORM with 3D when "
                     "optimal tiling\n";
      }
      try {
        auto imageFormatProperties =
            physicalDevices[i].getImageFormatProperties(
                format, vk::ImageType::e1D, vk::ImageTiling::eOptimal,
                vk::ImageUsageFlagBits::eSampled, {});
        std::cout
            << "Device supports BC1 RGB UNORM with 1D when optimal tiling\n";
      } catch (vk::Error &err) {
        std::cout << "Device does not support BC1 RGB UNORM with 1D when "
                     "optimal tiling\n";
      }
    }
  } catch (vk::SystemError &err) {
    std::cout << "vk::SystemError: " << err.what() << "\n";
    exit(-1);
  } catch (std::exception &err) {
    std::cout << "std::exception: " << err.what() << "\n";
    exit(-1);
  } catch (...) {
    std::cout << "unknown error\n";
    exit(-1);
  }

  return 0;
}
```

Repository to just recursively clone and test: https://github.com/mehmetoguzderin/vulkan-20240601-compress3d

**Comment by teoxoy** [comment] 2024-06-03 09:45
Oh yes, I didn't find `vkGetPhysicalDeviceImageFormatProperties`. I got stuck looking at `vkGetPhysicalDeviceFormatProperties` not accepting a `VkImageType` 😅.

**Comment by kainino0x** [comment] 2024-06-10 17:54
With #4685, the spec should be in a good state right now. @mehmetoguzderin will file a new issue for 3D ASTC which will be an optional feature.

**Closed by kainino0x** 2024-06-10 17:54 UTC
Labels: investigation, feature request, texture-capabilities, needs investigation, api

**Comment by Kangz** [comment] 2024-07-09 18:29
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-06-26#3d-compressed-textures-etc-on-macos-is-failing-validation-3183">GPU Web WG 2024-06-26 Atlantic-time</a></summary>

* CW: Where were we on this?
* KG: We discovered that ASTC only supports 2D textures guaranteed and 3D is optional
* CW: Same thing for ETC, right?
* KG: I don’t know.
* KG: ETC2 textures don’t support 3D textures … to some degree. In GLES3 you can use ETC2 textures with 2D arrays, which are 3D arrays with 2D array views in our spec.
* CW: The vulkan spec only guarantees (2D BC && sliced-3D BC) || (2D ASTC) || (2D ETC2)
* CW: WebGPU says 3D only works with BC, and 
* MM: I don’t think the WebGPU group will invent new technology… We should just take the common subset of functionality among all backend APIs and add validation for that.
* KG: &lt;missed>
* KG: We need to be clear what we mean when we say “textures”. As written, this is a regression from OpenGL and WebGL. They work for 3D textures from a 2D array in OpenGL.
    * 2D arrays vs 3D vs 2D slices of a 3D
    * It’s possible there really is a regression here in Vulkan.
    * When we say “only supports 2D textures” or “only supports 3D textures” then it’s not clear what we’re talking about
* KN: WebGPU already supports compressed 2D textures
    * KG: They’re specified via 3D upload signature, but the texture type is 2D
* KN: In WebGPU, you’d make a 2D texture, a 2D texture that has multiple array layers.
* CW: Issue 4705 is the one I filed. I have concerns about guaranteeing … With respect to texture compression, you either get BC, or you get ETC2 + ASTC. If you fall in the BC bucket, then you get 2D compression and sliced 3D compression guaranteed. But if you’re in the other bucket, you don’t get sliced 3D compression. We can guarantee it on the BC branch, so a developer might think it’s good to use on the other branch.. If you update your code to switch from one to the other, then it won’t work.
* KG: There are 2 ways to do this. One is to make it so that you have a different extension that allows you to sliced 3D compressed textures, even on BC (even if it’s supported everywhere). Every implementation of BC will always support that extension. The author is introduced to the concept that it might not always be there (Even though it is always there on BC). Or you could say the ETC2/ASTC suffix has a “-2D” suffix on them.
* MM: No other API separates 2d from 3d-sliced BC, think we shouldn’t either
* CW: WE can’t rename extensions
* KG: You’d add both names, add a console warning and a deprecation for the old one
* CW: This is much harder to do than to change some validation rules.
* CW: Changing the name of the extension for this is asking for a lot. It’s a good solution, but apps have the old names hardcoded.

</details>
