### ISSUE TITLE
Metal is unable to copy depth formats into colors

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1692] opened 2021-04-29 00:37 UTC
Currently the spec allows D32 -> R32 and D16 -> R16 copies.

On Metal, we generally implement copies between different formats by "casting" one of the sides to the other (i.e .[newTextureViewWithPixelFormat](https://developer.apple.com/documentation/metal/mtltexture/1515598-newtextureviewwithpixelformat?language=objc)], followed by the copy command on `BlitCommandEncoder`.

However, Metal defines "cast" only within certain groups, and it places color formats in a separate group from the depth formats. So we end up with:
> source texture pixelFormat (MTLPixelFormatDepth32Float) not castable

I suggest we remove any notion of Depth -> Color copies from the spec, at least for MVP, to address this.

**Comment by kainino0x** [comment] 2021-04-29 00:47
@austinEng I thought Dawn implemented this - did we use another approach or am I misremembering?

**Comment by austinEng** [comment] 2021-04-29 01:25
> @austinEng I thought Dawn implemented this - did we use another approach or am I misremembering?

Dawn requires exact format equality right now. 

https://source.chromium.org/chromium/chromium/src/+/master:third_party/dawn/src/dawn_native/CommandValidation.cpp;l=447;drc=221e331b49dfefadbc6fa40b0c68e6f97606d0b3

**Comment by kainino0x** [comment] 2021-04-29 01:27
OK. Seems like we should make this change then.

**Comment by Kangz** [comment] 2021-04-29 07:35
It seems the spec is already requiring format equality:

>  copyTextureToTexture(source, destination, copySize)
>  ...
>  - source.texture.[[format]] is equal to destination. texture.[[format]].

**Comment by kvark** [comment] 2021-04-29 22:02
The bits that need be fixes are:
> Copies between depth textures can only happen within the following sets of formats:
> depth16unorm, r16uint
> Additionally, depth32float textures can be copied into depth32float and r32float textures

**Comment by kainino0x** [comment] 2021-09-10 01:03
Pretty sure this is a duplicate of #1464

**Closed by kainino0x** 2021-09-10 01:03 UTC
Labels: bug
